### ISSUE TITLE
Not allowed to access thread group via Gremlin

### ISSUE THREAD

**Issue by ELLEXSHEN** [hugegraph/hugegraph#1001]
### Expected behavior 期望表现
hugegraph-studio 中 执行 graph.schema().vertexLabel('person').remove() 执行失败。

### Actual behavior 实际表现
hugegraph-studio 中 执行 graph.schema().vertexLabel('person').remove()，直接报错“ERROR Not allowed to access thread group via Gremlin

### Specifications of environment 环境信息
- hugegraph version: {0.10.4}
- operating system: {lcentos 7.8}
- hugegraph backend: {HBASE v2.2.4}

**Comment by javeme** [comment]
@ELLEXSHEN 可以收集下日志错误信息吗？

**Comment by siam1991** [comment]
@javeme , 我在通过hugegraph-studio建立索引时遇到了同样的问题
执行语句：graph.schema().indexLabel('personByCity').onV('person').by('addr').secondary().ifNotExist().create()
在第一次执行该语句时，直接报错“ERROR Not allowed to access thread group via Gremlin
在第二次执行该语句时，返回数据为
{
"id": "4de84180-d967-430b-a874-91ce51951774",
-"data": [
-{
"id": 6,
"name": "personByCity",
"base_type": "VERTEX_LABEL",
"base_value": "person",
"index_type": "SECONDARY",
+"fields": [ … ]
}
],
"type": "OTHER",
"duration": "118",
"showNum": 1,
"message": "",
-"graph": {
"vertices": [ ],
"edges": [ ],
"styles": { }
}
但通过条件进行节点选取时，获取结果为空列表
以下为我搜集到的日志信息（第一次报错信息）
2020-06-09 14:35:52 75861365 [gremlin-server-exec-3] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Not allowed to access thread group via Gremlin
java.lang.SecurityException: Not allowed to access thread group via Gremlin
	at com.baidu.hugegraph.security.HugeSecurityManager.newSecurityException(HugeSecurityManager.java:357) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.security.HugeSecurityManager.checkAccess(HugeSecurityManager.java:136) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315) ~[?:1.8.0_151]
	at java.lang.Thread.init(Thread.java:394) ~[?:1.8.0_151]
	at java.lang.Thread.init(Thread.java:349) ~[?:1.8.0_151]
	at java.lang.Thread.<init>(Thread.java:678) ~[?:1.8.0_151]
	at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:613) ~[?:1.8.0_151]
	at org.apache.commons.lang3.concurrent.BasicThreadFactory.newThread(BasicThreadFactory.java:206) ~[commons-lang3-3.8.1.jar:3.8.1]
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:619) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:932) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1367) ~[?:1.8.0_151]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[?:1.8.0_151]
	at com.baidu.hugegraph.task.TaskScheduler.submitTask(TaskScheduler.java:188) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.task.TaskScheduler.schedule(TaskScheduler.java:177) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.job.JobBuilder.schedule(JobBuilder.java:85) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.asyncRun(SchemaTransaction.java:465) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.rebuildIndex(SchemaTransaction.java:253) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.schema.builder.IndexLabelBuilder.createWithTask(IndexLabelBuilder.java:127) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.schema.builder.IndexLabelBuilder.create(IndexLabelBuilder.java:139) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.schema.builder.IndexLabelBuilder.create(IndexLabelBuilder.java:51) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.schema.builder.SchemaBuilder$create$0.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.7-indy.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.7-indy.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.7-indy.jar:2.5.7]
	at Script130.run(Script130.groovy:1) ~[?:?]
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:674) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:376) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[?:1.8.0_151]
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by javeme** [comment]
@siam1991 多谢提供日志信息，该问题是一个Bug，在master分枝上已经解决了：https://github.com/hugegraph/hugegraph/pull/892。
如果暂时无法更新代码，可通过关闭敏【感操作检查】绕过该问题，通过`-s false`启动服务即可：`bin/start-hugegraph.sh -s false`
