### ISSUE TITLE
hbase集群后端运行example报错

### ISSUE THREAD

**Issue by jiebaHZ** [hugegraph/hugegraph#1012]
### 
1. {后端hbase三台节点，huge已启动成功}
2. {远程请求server，运行SingleExample报错如下：}

`Exception in thread "main" class java.lang.IllegalArgumentException: Expect empty column name, please ensure hbase serializer is used
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:156)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:133)
	at com.baidu.hugegraph.api.graph.EdgeAPI.create(EdgeAPI.java:50)
	at com.baidu.hugegraph.driver.GraphManager.addEdge(GraphManager.java:200)
	at com.baidu.hugegraph.driver.GraphManager.addEdge(GraphManager.java:216)
	at com.baidu.hugegraph.driver.GraphManager.addEdge(GraphManager.java:207)
	at com.baidu.hugegraph.structure.graph.Vertex.addEdge(Vertex.java:50)
	at graph.Test.main(Test.java:63)`

3. {错误对应代码是在添加边的时候：}
` marko.addEdge("knows", vadas, "date", "20160110", "weight", 0.5);`

**Comment by imbajin** [comment]
你可以确认下配置文件的序列化器的配置正确么, [参考文档](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-server.html#55-hbase) ---`serializer=hbase`


另外如果是有具体报错提示, 尽量给多一点相关的信息,  比如带上你的配置文件. 

最后提过的issue, 如果解决了, 麻烦close一下.

**Comment by jiebaHZ** [comment]
好的，非常感谢，是我粗心了，配置文件没改正确。已解决。
