### ISSUE TITLE
使用GraphManager java api批量插入边，导致系统buff/cache过高，最终报了readTimeout错误，程序退出

### ISSUE THREAD

**Issue by hunter7727** [hugegraph/hugegraph#1015]
### Expected behavior 期望表现
希望通过GraphManager.addEdges批量添加边操作系统buff变化量小一些，不要报readTimeout错误

### Actual behavior 实际表现
使用GraphManager.addEdges批量添加边操作系统buff变化非常快，大概1G/S，运行一段时间后客户端报readTimeout错误，程序退出
报错堆栈信息
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:478)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:736)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:735)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:421)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:327)
	at com.baidu.hugegraph.rest.RestClient.lambda$post$1(RestClient.java:153)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:126)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:151)
	at com.baidu.hugegraph.api.graph.EdgeAPI.create(EdgeAPI.java:59)
	at com.baidu.hugegraph.driver.GraphManager.addEdges(GraphManager.java:234)
	at com.baidu.hugegraph.driver.GraphManager.addEdges(GraphManager.java:226)
	at com.cyberplus.brain.hugeGraph.PaperReferenceEdgeLoad.associatePaper(PaperReferenceEdgeLoad.java:110)
	at com.cyberplus.brain.controller.LoadDataController.paperReferenceAssociate(LoadDataController.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

### Steps to reproduce the problem 复现步骤
我用java程序读取文件中A的定点id和B的顶点id，读取到两顶点id，创建边，将两个顶点关联，用GraphManager.addEdges这个APi每30条一个批次调用添加边，在创建边的过程中系统buff/cache持续增加，最终使得没有内存可用，导致java程序报了read Time out 错误

#### Vertex/Edge summary 数据量
- loaded vertices amount: 
- loaded edges amount: 15000000
- loaded time: 

#### Vertex/Edge example 数据示例

            Edge edge = new Edge("person");
            edge.sourceLabel("a");
            edge.targetLabel("b");
            edge.sourceId(dictServicce.getPaperVIdById(line[0]));
            edge.targetId(dictServicce.getPaperVIdById(line[1]));
        
           //这是创建边的示例，每30个装到list集合中然后调用GraphManager.addEdges进行存储

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system: centos 7.4, 16 CPUs, 128G RAM}
- hugegraph backend: cassandra 3.10, cluster with 3 nodes, 1 x 1TB HDD disk each node

**Comment by javeme** [comment]
@hunter7727 可能是缓存占用过高导致的，可以调小缓存大小试试：
```
vertex.cache_capacity=10000
edge.cache_capacity=1000
```

**Comment by hunter7727** [comment]
请问是在这个配置文件里面设置吗：rest-server.properties

**Comment by hunter7727** [comment]
> @hunter7727 可能是缓存占用过高导致的，可以调小缓存大小试试：
> 
> ```
> vertex.cache_capacity=10000
> edge.cache_capacity=1000
> ```

感谢您的回答，我设置了一下这个参数，还是有相同的问题

**Comment by javeme** [comment]
@hunter7727 不好意思之前我理解为“内存占用高”了。你使用的是cassandra存储吗？buff占用高是否指cassandra所在的机器？ReadTimeout可能是后端存储IO负载高导致的，如果确认是的话可以调优一下Cassandra参数，ReadTimeout如果不是很严重的话也可以采取重试的方法。

**Comment by hunter7727** [comment]
> @hunter7727 不好意思之前我理解为“内存占用高”了。你使用的是cassandra存储吗？buff占用高是否指cassandra所在的机器？ReadTimeout可能是后端存储IO负载高导致的，如果确认是的话可以调优一下Cassandra参数，ReadTimeout如果不是很严重的话也可以采取重试的方法。

好的 谢谢你

**Comment by tmljob** [comment]
在HBase下面批量接口插入数据时，也存在这个问题，如何优化？
com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:128)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:151)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:138)
	at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:56)
	at com.baidu.hugegraph.driver.GraphManager.addVertices(GraphManager.java:83)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:496)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
	at com.baidu.hugegraph.rest.RestClient.lambda$post$1(RestClient.java:153)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:126)
	... 13 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:450)
	... 24 common frames omitted
2020-11-04 13:50:30.087[Job-Execute167] INFO  cn.encdata.cloud.scheduler.job.core.thread.Job[139] Job 1973 finished
2020-11-04 13:50:30.089[Thread-29585] INFO  cn.encdata.cloud.graph.service.impl.TaskExecuteServiceImpl[87] #start-load#人_顶点数据
2020-11-04 13:50:30.091[Thread-29585] INFO  cn.encdata.cloud.graph.service.impl.TaskExecuteServiceImpl[411] #DataBase Connection Info#jdbc:impala://53.80.6.49:25004/theme;AuthMech=1;KrbRealm=HADOOP.COM;KrbHostFQDN=cluster-node-0;KrbServiceName=impala
2020-11-04 13:50:30.110[Thread-29585] INFO  org.apache.hadoop.security.UserGroupInformation[982] Login successful for user ossuser/cluster-node-2@HADOOP.COM using keytab file /opt/client/ossuser.keytab
2020-11-04 13:50:30.140[Thread-29585] INFO  cn.encdata.cloud.graph.service.impl.TaskExecuteServiceImpl[317] Sql:select gmsfzh, xm, xb_mc, xm, gmsfzh, xxrksj from t_dm_ryztb where xxrksj >= ? order by xxrksj
2020-11-04 13:50:48.472[Thread-29585] INFO  cn.encdata.cloud.graph.service.impl.TaskExecuteServiceImpl[327] match-date: Thu Oct 22 09:40:41 CST 1970
2020-11-04 13:51:12.937[Thread-29585] ERROR cn.encdata.cloud.graph.job.LoadDataJobHandler[49] Failed to load data.
com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:128)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:151)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:138)
	at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:56)
	at com.baidu.hugegraph.driver.GraphManager.addVertices(GraphManager.java:83)
	at cn.encdata.cloud.graph.helper.HugeGraphHelper.writeVertex(HugeGraphHelper.java:90)
	at cn.encdata.cloud.graph.service.impl.GraphServiceImpl.writeVertex(GraphServiceImpl.java:180)
	at cn.encdata.cloud.graph.service.impl.TaskExecuteServiceImpl.loadVertexData(TaskExecuteServiceImpl.java:377)
	at cn.encdata.cloud.graph.service.impl.TaskExecuteServiceImpl.loadData(TaskExecuteServiceImpl.java:104)
	at cn.encdata.cloud.graph.job.LoadDataJobHandler.execute(LoadDataJobHandler.java:44)
	at cn.encdata.cloud.scheduler.job.core.thread.Job$1.call(Job.java:87)
	at cn.encdata.cloud.scheduler.job.core.thread.Job$1.call(Job.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:496)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
	at com.baidu.hugegraph.rest.RestClient.lambda$post$1(RestClient.java:153)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:126)
	... 13 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:450)
	... 24 common frames omitted
