### ISSUE TITLE
gremlin(g.V().count())执行报错

### ISSUE THREAD

**Issue by yuyang0** [hugegraph/hugegraph#102]
### Expected behavior 期望表现
`g.V().count()` 这样一个很简单的统计

### Actual behavior 实际表现

>    2018-10-10 21:28:14 78398733 [gremlin-server-worker-1] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Error encountered evaluating script: g.V().count()
    org.apache.tinkerpop.gremlin.process.traversal.util.TraversalInterruptedException: null  
        at  org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:142) ~[gremlin-core-3.2.5.jar:3.2.5]  
        at 
 org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.hasNext(ExpandableStepIterator.java:42) ~[gremlin-core-3.2.5.jar:3.2.5]  
        at 
 org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processAllStarts(ReducingBarrierStep.java:83) ~[gremlin-core-3.2.5.jar:3.2.5]  
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processNextStart(ReducingBarrierStep.java:113) ~[gremlin-core-3.2.5.jar:3.2.5]  
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.2.5.jar:3.2.5]  
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192) ~[gremlin-core-3.2.5.jar:3.2.5]  
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62) ~[gremlin-core-3.2.5.jar:3.2.5]  
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85) ~[gremlin-core-3.2.5.jar:3.2.5]  
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382) ~[gremlin-core-3.2.5.jar:3.2.5]  
        at 
 org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:239) ~[gremlin-server-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:320) ~[gremlin-groovy-3.2.5.jar:3.2.5]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]  
        at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:290) ~[hugegraph-api-0.7.4.jar:0.27.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]  
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

#### Vertex/Edge summary 数据量
数据量大概1000w节点

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {ubuntu 16.04, 32 CPUs, 128G RAM}
- hugegraph backend: {rocksdb}

**Comment by javeme** [comment]
这个错误是因为gremlin语句执行30s超时导致的，count()是属于全表遍历性质的操作（与mysql等传统数据库不一样的地方），对于这类耗时操作建议使用异步gremlin执行（OLAP），详细用法请参考[gremlin-schedule](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-tools.html)。

**Comment by javeme** [comment]
类似的表现：#37

**Comment by yuyang0** [comment]
@javeme 这样直接500，并且抛出异常不太好吧，如果有明确的日志那就完美了

**Comment by javeme** [comment]
@yuyang0 感谢你反馈的建议。确实我们第一次遇到这个异常也很疑惑，但是由于tinkerpop框架中gremlin-server设计的这个流程，所以在hugegraph层面无法修改（可以参考Java Thread Interrupt）。我们后续会尝试往tinkerpop社区提交我们的修改，期待能有一个更加易于理解的错误信息。谢谢。

**Comment by yuyang0** [comment]
@javeme 希望hugegraph越做越好，我打算小范围上线hugegraph，现在唯一的顾虑就是不能部署多台服务器来扩展处理能力，这以后肯定会遇到瓶颈
