### ISSUE TITLE
请问这个是什么错误？从警告变成错误，Not allowed to read file via Gremlin？hugegraph服务还在，但都变得不响应请求了了

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#1032]
```
2020-06-12 13:05:52 3341089 [gremlin-server-exec-18] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /home/chenying5/jdk1.8.0_191/lib/Script63614BeanInfo.groovy
2020-06-12 13:05:52 3341090 [gremlin-server-exec-4] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /home/chenying5/jdk1.8.0_191/lib/Script63613Customizer.class
2020-06-12 13:05:52 3341090 [gremlin-server-exec-18] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /home/chenying5/jdk1.8.0_191/lib/Script63614BeanInfo.class
2020-06-12 13:05:52,714 gremlin-server-exec-29 ERROR Recursive call to appender file
2020-06-12 13:05:52,720 gremlin-server-exec-29 ERROR Recursive call to appender file
2020-06-12 13:05:52,725 gremlin-server-exec-29 ERROR Recursive call to appender file
2020-06-12 13:05:52,725 gremlin-server-exec-29 ERROR An exception occurred processing Appender file java.lang.SecurityException: Not allowed to read file via Gremlin: logs/2020-06
    at com.baidu.hugegraph.security.HugeSecurityManager.newSecurityException(HugeSecurityManager.java:357)
    at com.baidu.hugegraph.security.HugeSecurityManager.checkRead(HugeSecurityManager.java:172)
    at java.io.File.exists(File.java:814)
    at java.io.File.mkdirs(File.java:1340)
    at org.apache.logging.log4j.core.appender.rolling.AbstractRolloverStrategy.getEligibleFiles(AbstractRolloverStrategy.java:112)
    at org.apache.logging.log4j.core.appender.rolling.AbstractRolloverStrategy.getEligibleFiles(AbstractRolloverStrategy.java:98)
    at org.apache.logging.log4j.core.appender.rolling.AbstractRolloverStrategy.getEligibleFiles(AbstractRolloverStrategy.java:90)
    at org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy.purgeAscending(DefaultRolloverStrategy.java:212)
    at org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy.purge(DefaultRolloverStrategy.java:199)
    at org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy.rollover(DefaultRolloverStrategy.java:326)
    at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.rollover(RollingFileManager.java:362)
    at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.rollover(RollingFileManager.java:278)
    at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.checkRollover(RollingFileManager.java:218)
    at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:267)
    at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
    at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
    at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
    at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2005)
    at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1876)
    at org.apache.logging.slf4j.Log4jLogger.warn(Log4jLogger.java:244)
    at com.baidu.hugegraph.security.HugeSecurityManager.newSecurityException(HugeSecurityManager.java:356)
    at com.baidu.hugegraph.security.HugeSecurityManager.checkRead(HugeSecurityManager.java:172)
    at java.io.File.exists(File.java:814)
    at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1334)
    at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:144)
    at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:139)
    at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:286)
    at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:329)
    at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:271)
    at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:969)
    at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
    at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
    at groovy.lang.Script.<init>(Script.java:39)
    at Script63615.<init>(Script63615.groovy)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.codehaus.groovy.runtime.InvokerHelper.newScript(InvokerHelper.java:482)
    at org.codehaus.groovy.runtime.InvokerHelper.createScript(InvokerHelper.java:440)
    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:631)
    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:376)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
    at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

```

**Comment by javeme** [comment]
@597477803 请问是执行的什么语句发生的错误？版本是0.10.4吗？

**Comment by 597477803** [comment]
> 请问是执行的什么语句发生的错误？多次请求时是否都会报这个错？版本是0.10.4吗？

就是查询点，多次请求都会报这个错，错误一般是先报警告“Not allowed to read file via Gremlin”， 等请求量上去了就变error了，然后hugegraph就不响应了，只能重启恢复，版本是0.10.4

**Comment by javeme** [comment]
@597477803 可暂时通过`-s false`启动服务规避该问题：bin/start-hugegraph.sh -s false

@lxb1111 请关注下这个问题，版本是0.10.4

**Comment by lxb1111** [comment]
v0.10.4 通过接口查询点，没有复现。@597477803 能详细说一下复现步骤嘛

**Comment by lxb1111** [comment]
我使用0.10.4的版本验证的时候，通过导入了youtube的公开数据集（113w点，300w边）结果如下：
![image](https://user-images.githubusercontent.com/58289576/84875363-73b60080-b0b8-11ea-903c-4b0f0e757a58.png)

**Comment by javeme** [comment]
> 我使用0.10.4的版本验证的时候，通过导入了youtube的公开数据集（113w点，300w边）结果如下

> 就是查询点，多次请求都会报这个错，错误一般是先报警告“Not allowed to read file via Gremlin”， 等请求量上去了就变error了，然后hugegraph就不响应了，只能重启恢复，版本是0.10.4

@lxb1111 根据描述“等请求量上去了”，试一下并发请求g.V().limit(10)看看？

**Comment by 597477803** [comment]
> @597477803 可暂时通过`-s false`启动服务规避该问题：bin/start-hugegraph.sh -s false
> 
> @lxb1111 请关注下这个问题，版本是0.10.4

@javeme 用了-s false启动，果然没这个警告了了，服务稳定多了

**Comment by 597477803** [comment]
> v0.10.4 通过接口查询点，没有复现。@597477803 能详细说一下复现步骤嘛
就是bin/start-hugegraph.sh启动，请求数据时就有warn日志如下：
2020-06-13 17:18:31 59719503 [gremlin-server-exec-12] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /home/chenying5/jdk1.8.0_191/lib/Script788055BeanInfo.groovy
2020-06-13 17:18:31 59719503 [gremlin-server-exec-14] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /home/chenying5/jdk1.8.0_191/lib/groovy/runtime/metaclass/Script788057MetaClass.class
2020-06-13 17:18:31 59719504 [gremlin-server-exec-12] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /home/chenying5/jdk1.8.0_191/lib/Script788055BeanInfo.class
2020-06-13 17:18:31 59719504 [gremlin-server-exec-12] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /home/chenying5/jdk1.8.0_191/lib/Script788055Customizer.class
2020-06-13 17:18:31 59719505 [gremlin-server-exec-12] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /home/chenying5/jdk1.8.0_191/lib/Script788055Customizer.groovy
2020-06-13 17:18:31 59719505 [gremlin-server-exec-14] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /home/chenying5/jdk1.8.0_191/lib/Script788057BeanInfo.class
2020-06-13 17:18:31 59719505 [gremlin-server-exec-12] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /home/chenying5/jdk1.8.0_191/lib/Script788055Customizer.class

等到请求并发上去后比如并发500、1000等，就会变得服务不响应

**Comment by javeme** [comment]
@597477803 也可以尝试使用新的补丁包：https://github.com/hugegraph/hugegraph/releases/download/v0.10.4/hugegraph-0.10.4_2020-06-19.tar.gz

**Comment by javeme** [comment]
Close due to the lack of activity, feel free to reopen if not fixed in new version.
