### ISSUE TITLE
cassandra NoClassDefFoundError FutureFallback with guava > 19

### ISSUE THREAD

**Issue by javeme** [hugegraph/hugegraph#1043]
```
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
	at com.datastax.driver.core.GuavaCompatibility.selectImplementation(GuavaCompatibility.java:136) ~[cassandra-driver-core-3.2.0.jar:?]
	at com.datastax.driver.core.GuavaCompatibility.<clinit>(GuavaCompatibility.java:52) ~[cassandra-driver-core-3.2.0.jar:?]
	at com.datastax.driver.core.Cluster.<clinit>(Cluster.java:68) ~[cassandra-driver-core-3.2.0.jar:?]
	at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool.open(CassandraSessionPool.java:69) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.open(CassandraStore.java:137) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:76) ~[classes/:?]
```

**Comment by javeme** [comment]
ref:
https://stackoverflow.com/a/40691831/11297548
https://datastax-oss.atlassian.net/browse/JAVA-1328

**Comment by javeme** [comment]
error with guava-28.2-jre:
```
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60) ~[?:1.8.0_111]
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717) ~[?:1.8.0_111]
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419) ~[?:1.8.0_111]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_111]
	at sun.misc.IOUtils.readFully(IOUtils.java:65) ~[?:1.8.0_111]
	at java.util.jar.JarFile.getBytes(JarFile.java:425) ~[?:1.8.0_111]
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193) ~[?:1.8.0_111]
	at java.util.jar.JarFile.getManifest(JarFile.java:180) ~[?:1.8.0_111]
	at com.google.common.reflect.ClassPath$Scanner.scanJar(ClassPath.java:397) ~[guava-28.2-jre.jar:?]
	at com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:384) ~[guava-28.2-jre.jar:?]
	at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:361) ~[guava-28.2-jre.jar:?]
	at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:354) ~[guava-28.2-jre.jar:?]
	at com.google.common.reflect.ClassPath.from(ClassPath.java:119) ~[guava-28.2-jre.jar:?]
	at com.baidu.hugegraph.util.ReflectionUtil.classes(ReflectionUtil.java:90) ~[hugegraph-common-1.7.8.jar:1.7.8.0]
	at com.baidu.hugegraph.plugin.HugeGraphGremlinPlugin.<clinit>(HugeGraphGremlinPlugin.java:48) ~[classes/:?]
```
