### ISSUE TITLE
The id field can't be empty or null when id strategy is CUSTOMIZE for vertex label 'User'

### ISSUE THREAD

**Issue by coooodeXjl** [hugegraph/hugegraph#1059]
vertices has been loaded : 0
ERROR: Failed to load
Exception in thread "main" java.lang.IllegalStateException: The id field can't be empty or null when id strategy is CUSTOMIZE for vertex label 'User'
	at com.google.common.base.Preconditions.checkState(Preconditions.java:172)
	at com.baidu.hugegraph.util.E.checkState(E.java:68)
	at com.baidu.hugegraph.loader.builder.VertexBuilder.checkIdField(VertexBuilder.java:123)
	at com.baidu.hugegraph.loader.builder.VertexBuilder.<init>(VertexBuilder.java:45)
	at com.baidu.hugegraph.loader.builder.ElementBuilder.of(ElementBuilder.java:78)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:159)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:132)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:89)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66)

**Comment by javeme** [comment]
@coooodeXjl please ensure the id field mapping is correct in struct json file.
