### ISSUE TITLE
hugegraph 顶点与边的名称显示的问题

### ISSUE THREAD

**Issue by wisdoms** [hugegraph/hugegraph#1066]
### Expected behavior 期望表现
顶点与边的名称能显示全汉字，不显示数字前缀或英语字母

### Actual behavior 实际表现
顶点名称显示有数字前缀，实际是这样的格式：136：软件  ， 其中 软件为顶点的名称， 边的名称如果要显示中文， 边的 label 就必须是中文， 而 label 不能是单词

### Steps to reproduce the problem 复现步骤
1. 向图库添加顶点与边
2.  查询顶点与边 g.V()
3.  查询结果中，顶点有数字前缀

#### Vertex/Edge summary 数据量
-  小于100条

#### Vertex/Edge example 数据示例
"vertices": [
    {
      "label": "event",
      "id": "14:软件",
      "type": "vertex",
      "properties": {
        "name": "软件",
      }
    }

### Specifications of environment 环境信息
- hugegraph version:  0.10.4
- operating system: center os 7
- hugegraph backend:  cassandra  或 rockdb

**Comment by javeme** [comment]
@wisdoms 由于id的作用是为了唯一区分顶点，显示时建议使用属性，比如上述例子中的”name“。

**Comment by wisdoms** [comment]
好的，hugegraph-studio  在查询出来后，能通过配置来改变顶点的名称吗？ 就是不通过 id 来展示 名称

**Comment by javeme** [comment]
HugeGraph-Hubble是支持自定义展示内容的，预计Q3即将发布release版本。

**Comment by wisdoms** [comment]
如果 有相关的接口设置就更好

**Comment by wisdoms** [comment]
在更新边的属性时，发生了错误，怎么也更新不了， 错误信息如下 ：
	class com.baidu.hugegraph.exception.NotAllowException: Not allowed to update source label for edge label '出生地21', it must be null
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:185)
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:172)
	at com.baidu.hugegraph.api.schema.EdgeLabelAPI.append(EdgeLabelAPI.java:52)
	at com.baidu.hugegraph.driver.SchemaManager.appendEdgeLabel(SchemaManager.java:149)

相关更新代码：
	        for (String str : newPros) {
            if (null == oldPros || oldPros.size() == 0 || !oldPros.contains(str)) {
                schemaManager.propertyKey(str).asText().ifNotExist().create();
                schemaManager.appendEdgeLabel(
                        schemaManager.edgeLabel(labelName)
                                .link(sourceLabel, targegLabel)
                                .properties(str)
                                .nullableKeys(str)
                                .sortKeys("name")
                                .multiTimes()
                                .ifNotExist().build());
            }
        }

**Comment by wisdoms** [comment]
边的更新操作是如何进行的？ 是先删除原有的边，再创建新边吗？

**Comment by wisdoms** [comment]
在更新边的时候，还会莫名其妙报这样的错误： 
class com.baidu.hugegraph.exception.NotAllowException: Not allowed to update frequency for edge label '出生地21'
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:185)
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:172)
	at com.baidu.hugegraph.api.schema.EdgeLabelAPI.append(EdgeLabelAPI.java:52)
	at com.baidu.hugegraph.driver.SchemaManager.appendEdgeLabel(SchemaManager.java:149)

**Comment by javeme** [comment]
@wisdoms 该API支持 [1.3.2 为已存在的EdgeLabel添加properties或userdata，或者移除userdata
](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/edgelabel.html) ，不支持更新边类型的其它域（比如起始顶点类型、终点类型、移除属性等）。另外，注意区分 edge label 和 edge，前者是边类型，后者是边。

**Comment by wisdoms** [comment]
那想问下，边的名称显示 的是默认的 label 名称，那 名称能更改吗？

**Comment by wisdoms** [comment]
在顶点中，把顶点 的属性 name 设置成了主键，那么顶点的name  还能更新吗？

**Comment by javeme** [comment]
@wisdoms 主键意味着不可更改，因为它唯一标识一条记录，更改了就代表一条新的记录。如果需要更改则可能字段不适合用来作为主键。

**Comment by wisdoms** [comment]
边的 label 可以多次使用吗？ 在批量插入大量的顶点与边时， 大概有快50万个数据， 都用的是同一个边的 label , 顶点的 label ,发现刚开始创建的边在最后没了， 这种情况该怎么处理？ 不想每一个关系就创建一个边的 label

**Comment by wisdoms** [comment]
在查询的时候，hugegraph 报错了，报错内容： Invalid limit 2147483647, must be <= capacity ， 我设置了 limit 的最大值 是 int.MaxValue
