### ISSUE TITLE
hugegraph 使用过程中报错

### ISSUE THREAD

**Issue by wisdoms** [hugegraph/hugegraph#1067]
### Expected behavior 期望表现
在运行脚本  init-store.sh  初始化 hugegraph 时，初始化报错

### Actual behavior 实际表现
在 linux 终端下，用 sudo 命令运行 init-store 脚本时， 报错。

### Steps to reproduce the problem 复现步骤
1.  在配置好 hugegraph 的后台数据库 cassandra ,并首先启动 cassandra, cassandra 启动成功
2.  运行 hugegraph  bin 目录下的  init-store.sh 脚本
3.  运行结果直接报错

#### Vertex/Edge summary 数据量
-  小于100条

#### Vertex/Edge example 数据示例
**错误信息如下 ：**

2020-07-01 09:11:28 1307  [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2020-07-01 09:11:28 1444  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'cassandra' for graph 'hugegraph'
2020-07-01 09:11:29 2328  [main] [WARN ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Failed to close cluster after an error
	at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool.doClose(CassandraSessionPool.java:123) ~[hugegraph-cassandra-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.BackendSessionPool.close(BackendSessionPool.java:140) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.open(CassandraStore.java:154) [hugegraph-cassandra-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:73) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:69) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:53) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph.openSchemaTransaction(HugeGraph.java:258) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph.access$700(HugeGraph.java:80) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.getOrNewTransaction(HugeGraph.java:768) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.schemaTransaction(HugeGraph.java:747) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.access$000(HugeGraph.java:622) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph.schemaTransaction(HugeGraph.java:320) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:88) [hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:99) [hugegraph-dist-0.10.4.jar:?]
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87) [hugegraph-dist-0.10.4.jar:?]
2020-07-01 09:11:29 2335  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Close graph hugegraph[hugegraph]
2020-07-01 09:11:29 2351  [task-db-worker-1] [WARN ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Failed to close cluster after an error
	at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool.doClose(CassandraSessionPool.java:123) ~[hugegraph-cassandra-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.BackendSessionPool.close(BackendSessionPool.java:140) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.open(CassandraStore.java:154) ~[hugegraph-cassandra-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:73) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.<init>(GraphTransaction.java:120) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.<init>(TaskScheduler.java:428) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.task.TaskScheduler.tx(TaskScheduler.java:115) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.task.TaskScheduler.lambda$close$4(TaskScheduler.java:221) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
Exception in thread "main" com.baidu.hugegraph.exception.ConnectionException: Failed to connect to Cassandra
	at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.open(CassandraStore.java:158)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:73)
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:69)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:53)
	at com.baidu.hugegraph.HugeGraph.openSchemaTransaction(HugeGraph.java:258)
	at com.baidu.hugegraph.HugeGraph.access$700(HugeGraph.java:80)
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.getOrNewTransaction(HugeGraph.java:768)
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.schemaTransaction(HugeGraph.java:747)
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.access$000(HugeGraph.java:622)
	at com.baidu.hugegraph.HugeGraph.schemaTransaction(HugeGraph.java:320)
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:88)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:99)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.datastax.driver.core.NettyUtil.newEventLoopGroupInstance(NettyUtil.java:136)
	at com.datastax.driver.core.NettyOptions.eventLoopGroup(NettyOptions.java:99)
	at com.datastax.driver.core.Connection$Factory.<init>(Connection.java:774)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1446)
	at com.datastax.driver.core.Cluster.init(Cluster.java:159)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:280)
	at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool$Session.open(CassandraSessionPool.java:215)
	at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.open(CassandraStore.java:142)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.datastax.driver.core.NettyUtil.newEventLoopGroupInstance(NettyUtil.java:134)
	... 21 more
Caused by: java.lang.NoSuchMethodError: io.netty.channel.SingleThreadEventLoop.<init>(Lio/netty/channel/EventLoopGroup;Ljava/util/concurrent/Executor;ZLjava/util/Queue;Ljava/util/Queue;Lio/netty/util/concurrent/RejectedExecutionHandler;)V
	at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:87)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:143)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:68)
	... 26 more

### Specifications of environment 环境信息
- hugegraph version:  0.10.4
- operating system: center os 7
- hugegraph backend:  cassandra

**Comment by javeme** [comment]
@wisdoms 根据错误信息”NoSuchMethodError: io.netty.channel.SingleThreadEventLoop“来看，是netty的版本冲突导致的，请检查是否依赖多个netty版本，通过调整pom确保使用某一个版本。

**Comment by wisdoms** [comment]
netty 是 cassandra 自带的吗？ cassandra 中没有 pom 这个，有点小白

**Comment by javeme** [comment]
是的，cassandra driver依赖netty

**Comment by wisdoms** [comment]
另外，hugegraph  在显示所有的数据时，提示  request time out , 请求超时，数据量大概有 50万条，这样该怎么查询 显示？

**Comment by wisdoms** [comment]
还有个问题，是这样的，一组 vertexLabel ，即顶点 label ，就创建 一个 edgeLabel ， 边的 label ，edgeLabel 中的属性key都相同，edgeLabel 在一个 类型的 vertexLabel 中反复使用，避免大量创建 edgeLabel, 边名称显示的是 edgeLabel 中的 name 属性， 我在同一个 vertexLabel 中插入了很多的数据 ，数据量大约有 1000万个，现在想请教下，我的这种做法合理吗？ 

![image](https://user-images.githubusercontent.com/10112381/87108168-35b19400-c294-11ea-90c8-e8432aa449d7.png)

**Comment by sunlujing** [comment]
我使用 0.10版本遇到同样的问题，话说，我是直接download你们的 tar包，解压运行的。 为什么会出现包冲突的问题啊?

**Comment by sunlujing** [comment]
@javeme 麻烦帮忙看下呢

**Comment by javeme** [comment]
@sunlujing 是否环境中已经有其它依赖了，比如可能是java path中有其它版本的netty

**Comment by sunlujing** [comment]
> @sunlujing 是否环境中已经有其它依赖了，比如可能是java path中有其它版本的netty

IntiStore.sh 我看了没有引用其他包含netty的 path， hugegraph lib 的netty jar 中。
netty-all-4.1.42.Final.jar， 会和其他 4.1.36的包冲突。
我把netty-all-4.1.42.Final.jar，换成 netty-all- 4.1.36.Final.jar 就都ok了。
不知道你们是否能重现这个问题。

-rw-r--r--  1 lujing.sun lujing.sun  4080249 Jul 21 15:42 netty-all-4.1.42.Final.jar
-rw-r--r--  1 lujing.sun lujing.sun   148299 Jul 21 15:42 netty-codec-4.0.44.Final.jar
-rw-r--r--  1 lujing.sun lujing.sun   598069 Jul 21 15:42 netty-common-4.1.36.Final.jar
-rw-r--r--  1 lujing.sun lujing.sun   321759 Jul 21 15:42 netty-handler-4.0.44.Final.jar
-rw-r--r--  1 lujing.sun lujing.sun    32799 Jul 21 15:42 netty-resolver-4.1.36.Final.jar
-rw-r--r--  1 lujing.sun lujing.sun   471155 Jul 21 15:42 netty-transport-4.1.36.Final.jar
-rw-r--r--  1 lujing.sun lujing.sun   141455 Jul 21 15:42 netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar
-rw-r--r--  1 lujing.sun lujing.sun    33428 Jul 21 15:42 netty-transport-native-unix-common-4.1.36.Final.jar
