### ISSUE TITLE
hugegraph 连接 cassandra 启动服务 报错

### ISSUE THREAD

**Issue by wisdoms** [hugegraph/hugegraph#1068]
### Expected behavior 期望表现
能成功启动 hugegraph

### Actual behavior 实际表现
启动失败

### Steps to reproduce the problem 复现步骤
1. 配置好 cassandra ，并成功启动 cassandra , 配置 hugegraph 连接 cassandra  
2. 初始化  hugegtaph ,即运行 init-store.sh 时报错，接着启动服务  start-hugegraph.sh 
3. 启动服务失败

#### Vertex/Edge summary 数据量
小于100

#### Vertex/Edge example 数据示例
报错信息如下 ：
3^C[will@localhost bin]$ sudo ./start-hugegraph.sh 
[sudo] password for will: 
Starting HugeGraphServer...
Connecting to HugeGraphServer (http://0.0.0.0:1242/graphs).............The operation timed out when attempting to connect to http://0.0.0.0:1242/graphs
See /data/cw/install/hugegraph-0.10.4/logs/hugegraph-server.log for HugeGraphServer log output.
[will@localhost bin]$ vim ../logs/hugegraph-server.log 

2020-07-01 09:08:13 1325  [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2020-07-01 09:08:14 1468  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'cassandra' for graph 'hugegraph'
2020-07-01 09:08:14 2355  [main] [WARN ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Failed to close cluster after an error
java.lang.NullPointerException: null
        at com.datastax.driver.core.Cluster$Manager.close(Cluster.java:1676) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.datastax.driver.core.Cluster$Manager.access$200(Cluster.java:1354) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.datastax.driver.core.Cluster.closeAsync(Cluster.java:566) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.datastax.driver.core.Cluster.close(Cluster.java:578) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool.doClose(CassandraSessionPool.java:123) ~[hugegraph-cassandra-0.10.4.jar:?]
        at com.baidu.hugegraph.backend.store.BackendSessionPool.close(BackendSessionPool.java:140) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.open(CassandraStore.java:154) [hugegraph-cassandra-0.10.4.jar:?]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:73) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:69) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:53) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph.openSchemaTransaction(HugeGraph.java:258) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph.access$700(HugeGraph.java:80) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.getOrNewTransaction(HugeGraph.java:768) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.schemaTransaction(HugeGraph.java:747) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.access$000(HugeGraph.java:622) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph.schemaTransaction(HugeGraph.java:320) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:88) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:99) [hugegraph-dist-0.10.4.jar:?]
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87) [hugegraph-dist-0.10.4.jar:?]
2020-07-01 09:08:14 2361  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Close graph hugegraph[hugegraph]
2020-07-01 09:08:15 2377  [task-db-worker-1] [WARN ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Failed to close cluster after an error
java.lang.NullPointerException: null
        at com.datastax.driver.core.Cluster$Manager.close(Cluster.java:1676) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.datastax.driver.core.Cluster$Manager.access$200(Cluster.java:1354) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.datastax.driver.core.Cluster.closeAsync(Cluster.java:566) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.datastax.driver.core.Cluster.close(Cluster.java:578) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool.doClose(CassandraSessionPool.java:123) ~[hugegraph-cassandra-0.10.4.jar:?]
        at com.baidu.hugegraph.backend.store.BackendSessionPool.close(BackendSessionPool.java:140) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.open(CassandraStore.java:154) ~[hugegraph-cassandra-0.10.4.jar:?]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:73) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.<init>(GraphTransaction.java:120) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.<init>(TaskScheduler.java:428) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.task.TaskScheduler.tx(TaskScheduler.java:115) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.task.TaskScheduler.lambda$close$4(TaskScheduler.java:221) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at com.datastax.driver.core.Cluster.close(Cluster.java:578) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool.doClose(CassandraSessionPool.java:123) ~[hugegraph-cassandra-0.10.4.jar:?]
        at com.baidu.hugegraph.backend.store.BackendSessionPool.close(BackendSessionPool.java:140) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.open(CassandraStore.java:154) [hugegraph-cassandra-0.10.4.jar:?]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:73) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph.openSchemaTransaction(HugeGraph.java:258) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph.access$700(HugeGraph.java:80) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.getOrNewTransaction(HugeGraph.java:768) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.schemaTransaction(HugeGraph.java:747) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.access$000(HugeGraph.java:622) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.HugeGraph.schemaTransaction(HugeGraph.java:320) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:88) [hugegraph-core-0.10.4.jar:0.10.4.0]
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:99) [hugegraph-dist-0.10.4.jar:?]
2020-07-01 09:11:29 2351  [task-db-worker-1] [WARN ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Failed to close cluster after an error
java.lang.NullPointerException: null
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.open(CassandraStore.java:154) ~[hugegraph-cassandra-0.10.4.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2020-07-01 09:13:29 121715 [Thread-1] [INFO ] com.baidu.hugegraph.HugeGraph [] - HugeGraph is shutting down
2020-07-01 09:23:18 1680  [main] [INFO ] com.baidu.hugegraph.dist.HugeGremlinServer [] - 3.4.3^M
         \,,,/^M
         (o o)^M
-----oOOo-(3)-oOOo-----^M

2020-07-01 09:23:18 1875  [main] [INFO ] com.baidu.hugegraph.dist.HugeGremlinServer [] - Configuring Gremlin Server from /data/cw/install/hugegraph-0.10.4/conf/gremlin-server.yaml
2020-07-01 09:23:18 2192  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'cassandra' for graph 'hugegraph'
2020-07-01 09:23:18 2258  [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Graph [hugegraph] was successfully configured via [conf/hugegraph.properties].
2020-07-01 09:23:18 2258  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor [] - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
2020-07-01 09:23:19 2938  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor [] - Initialized GremlinExecutor and preparing GremlinScriptEngines instances.
2020-07-01 09:23:24 7955  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor [] - Initialized gremlin-groovy GremlinScriptEngine and registered metrics
2020-07-01 09:23:24 7988  [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the standard OpProcessor.
2020-07-01 09:23:24 7992  [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the session OpProcessor.
2020-07-01 09:23:24 8426  [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the traversal OpProcessor.
2020-07-01 09:23:24 8505  [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executing start up LifeCycleHook
2020-07-01 09:23:24 8527  [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executed once at startup of Gremlin Server.
2020-07-01 09:23:25 8730  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0
2020-07-01 09:23:25 8907  [gremlin-server-boss-1] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Channel started at port 8182.
2020-07-01 09:23:25 8910  [main] [INFO ] com.baidu.hugegraph.server.RestServer [] - RestServer starting...
Jul 01, 2020 9:23:33 AM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:1242]
2020-07-01 09:23:33 16647 [main] [INFO ] com.baidu.hugegraph.server.RestServer [] - Graph 'hugegraph' was successfully configured via 'conf/hugegraph.properties'
2020-07-01 09:23:34 17903 [main] [INFO ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Failed to connect keyspace: hugegraph, try to init keyspace later
2020-07-01 09:23:39 23248 [main] [INFO ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Failed to connect keyspace: hugegraph, try to init keyspace later
main dict load finished, time elapsed 1872 ms
model load finished, time elapsed 67 ms.
2020-07-01 09:23:41 25319 [main] [INFO ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Failed to connect keyspace: hugegraph, try to init keyspace later
Jul 01, 2020 9:23:41 AM org.glassfish.grizzly.http.server.NetworkListener shutdownNow
INFO: Stopped listener bound to [0.0.0.0:1242]
2020-07-01 09:23:41 25414 [main] [ERROR] com.baidu.hugegraph.dist.HugeGraphServer [] - HugeRestServer start error:
com.baidu.hugegraph.backend.BackendException: The backend store of 'hugegraph' has not been initialized
        at com.baidu.hugegraph.core.GraphManager.checkBackendVersionOrExit(GraphManager.java:206) ~[hugegraph-api-0.10.4.jar:0.48.0.0]
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:76) ~[hugegraph-api-0.10.4.jar:0.48.0.0]
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:108) ~[hugegraph-api-0.10.4.jar:0.48.0.0]
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357) ~[jersey-container-grizzly2-http-2.25.1.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:422) ~[grizzly-http-server-2.3.28.jar:2.3.28]
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:314) ~[grizzly-http-server-2.3.28.jar:2.3.28]
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:290) ~[grizzly-http-server-2.3.28.jar:2.3.28]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:62) ~[hugegraph-api-0.10.4.jar:0.48.0.0]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:113) ~[hugegraph-api-0.10.4.jar:0.48.0.0]
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58) ~[hugegraph-dist-0.10.4.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:55) [hugegraph-dist-0.10.4.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:100) [hugegraph-dist-0.10.4.jar:?]
2020-07-01 09:23:41 25426 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[]
2020-07-01 09:23:41 25426 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[session]
2020-07-01 09:23:41 25429 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[traversal]
2020-07-01 09:23:41 25433 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down thread pools.
2020-07-01 09:23:41 25436 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executing shutdown LifeCycleHook
2020-07-01 09:23:41 25437 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executed once at shutdown of Gremlin Server.
2020-07-01 09:23:44 27640 [gremlin-server-stop] [INFO ] com.baidu.hugegraph.HugeGraph [] - Close graph hugegraph[hugegraph]
2020-07-01 09:23:44 27652 [gremlin-server-stop] [WARN ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Exception while closing Graph instance [hugegraph]
java.lang.IllegalStateException: Ensure tx closed in all threads when closing graph 'hugegraph'
        at com.google.common.base.Preconditions.checkState(Preconditions.java:199) ~[guava-19.0.jar:?]
        at com.baidu.hugegraph.util.E.checkState(E.java:68) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
        at com.baidu.hugegraph.HugeGraph.close(HugeGraph.java:503) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$null$7(GremlinServer.java:298) ~[gremlin-server-3.4.3.jar:3.4.3]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_212]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$stop$8(GremlinServer.java:295) ~[gremlin-server-3.4.3.jar:3.4.3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2020-07-01 09:23:44 27653 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Closed Graph instance [hugegraph]
2020-07-01 09:23:44 27655 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Gremlin Server - shutdown complete
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: The backend store of 'hugegraph' has not been initialized
        at com.baidu.hugegraph.core.GraphManager.checkBackendVersionOrExit(GraphManager.java:206)
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:76)
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:108)
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74)
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81)
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357)
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:422)
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:314)
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:290)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:62)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:113)
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58)
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:55)

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system: center os 7
- hugegraph backend: cassandra

**Comment by javeme** [comment]
@wisdoms 这个问题是 #1067 相同的吗？

**Comment by wisdoms** [comment]
是不同的， 1067 是hugegraph 初始化报的错， 初始化报错后，接着 直接 启动 hugegraph , 就出现 这个错误，提示找不到  Opening backend store 'cassandra' for graph 'hugegraph'cassandra

**Comment by javeme** [comment]
如果初始化init-store失败，启动不了是预期的，请先解决init-store再尝试启动服务吧。

**Comment by wisdoms** [comment]
好的，我可以试试
