### ISSUE TITLE
java client连接问题。

### ISSUE THREAD

**Issue by henryji96** [hugegraph/hugegraph#1124]
为何http://10.221.28.118:8008/graphs连接studio后，会回到主页而看不见有多少graph的信息。无论http://10.221.28.118:8008后面接什么都是回到了主页面。

HugeClient hugeClient = new HugeClient("http://10.221.28.118:8008", "hugegraph");
利用java client连接，只返回了主页面的source code，和异常报错。
      at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:193)
	at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41)
	at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45)
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:129)
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:114)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:74)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:61)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:57)
	at SingleExample.main(SingleExample.java:17)

**Comment by henryji96** [comment]
已解决conf/rest-server.properties，restserver.url 配置错误。
