### ISSUE TITLE
执行hugegraph-tools的graph-clear超时失败怎么办？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#1165]
清空图失败，会出现两种情况的报错，详情如下：

（1）一种情况是报超时，日志如下：
Exception in thread "main" com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:128)
	at com.baidu.hugegraph.rest.RestClient.delete(RestClient.java:229)
	at com.baidu.hugegraph.api.graphs.GraphsAPI.clear(GraphsAPI.java:82)
	at com.baidu.hugegraph.driver.GraphsManager.clear(GraphsManager.java:54)
	at com.baidu.hugegraph.manager.GraphsManager.clear(GraphsManager.java:44)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:222)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:379)
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.delete(JerseyInvocation.java:360)
	at com.baidu.hugegraph.rest.RestClient.lambda$delete$6(RestClient.java:230)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:126)
	... 6 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 18 more

（2）另一种情况日志如下：
Exception in thread "main" class com.baidu.hugegraph.backend.BackendException: Failed to truncate table 's_vi' for 's'
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
	at com.baidu.hugegraph.rest.RestClient.delete(RestClient.java:232)
	at com.baidu.hugegraph.api.graphs.GraphsAPI.clear(GraphsAPI.java:82)
	at com.baidu.hugegraph.driver.GraphsManager.clear(GraphsManager.java:54)
	at com.baidu.hugegraph.manager.GraphsManager.clear(GraphsManager.java:44)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:222)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:379)
Caused by: java.io.InterruptedIOException: Interrupt while waiting on Operation: DISABLE, Table Name: hugegraphonline2:s_vi

**Comment by chencjiajy** [comment]
我一般是多执行几次，然后就正常了

**Comment by javeme** [comment]
@597477803 这个主要是因为hbase的truncate操作耗时太长导致，可以调大truncate超时参数减少该问题。
