### ISSUE TITLE
Could not initialize class org.rocksdb.Options

### ISSUE THREAD

**Issue by Jerrick** [hugegraph/hugegraph#1167]
### Expected behavior 期望表现
init成功

### Actual behavior 实际表现
bash bin/init-store.sh
Initing HugeGraph Store...
2020-09-09 00:06:12 1155  [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2020-09-09 00:06:13 1336  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'rocksdb' for graph 'hugegraph'
2020-09-09 00:06:13 1403  [main] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: rocksdb-data/schema
2020-09-09 00:06:13 1561  [pool-5-thread-1] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: rocksdb-data/system
Exception in thread "main" com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
	at com.baidu.hugegraph.task.HugeTaskScheduler.submit(HugeTaskScheduler.java:275)
	at com.baidu.hugegraph.task.HugeTaskScheduler.submit(HugeTaskScheduler.java:268)
	at com.baidu.hugegraph.task.HugeTaskScheduler.close(HugeTaskScheduler.java:172)
	at com.baidu.hugegraph.task.HugeTaskManager.closeScheduler(HugeTaskManager.java:67)
	at com.baidu.hugegraph.HugeGraph.close(HugeGraph.java:416)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:106)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.Options
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.baidu.hugegraph.task.HugeTaskScheduler.submit(HugeTaskScheduler.java:273)
	... 6 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.Options
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.mergeOldCFs(RocksDBStdSessions.java:213)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:95)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:206)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:154)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:134)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72)
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30)
	at com.baidu.hugegraph.backend.tx.GraphTransaction.<init>(GraphTransaction.java:110)
	at com.baidu.hugegraph.task.HugeTaskScheduler$TaskTransaction.<init>(HugeTaskScheduler.java:284)
	at com.baidu.hugegraph.task.HugeTaskScheduler.tx(HugeTaskScheduler.java:99)
	at com.baidu.hugegraph.task.HugeTaskScheduler.lambda$close$3(HugeTaskScheduler.java:173)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Specifications of environment 环境信息
- hugegraph version: {v0.7.4}
- operating system: 
**ARM CPU，not x86.**
cat /proc/version
     Linux version 4.19.85 (lqb@ubuntu) (gcc version 7.4.0 (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1)) #33 SMP Mon Jan 13 12:36:01 HKT 2020
uname -a
     Linux ubuntu 4.19.85 #33 SMP Mon Jan 13 12:36:01 HKT 2020 aarch64 aarch64 aarch64 GNU/Linux
- hugegraph backend: rocksdb

Maybe not  similar to #371, because in this version the rocksdb version is 「rocksdbjni-5.8.6.jar」。

**Comment by javeme** [comment]
please refer to https://github.com/hugegraph/hugegraph/issues/335
