### ISSUE TITLE
 Failed to start Gremlin Server

### ISSUE THREAD

**Issue by kevinliang-123** [hugegraph/hugegraph#1169]
### Expected behavior 期望表现
能够正常启动

### Actual behavior 实际表现
无法启动，出现错误：java.util.concurrent.CompletionException: com.baidu.hugegraph.HugeException: Failed to start Gremlin Server

### Steps to reproduce the problem 复现步骤
1. 在一次用数据初始化时，突然报Failed to do request，
2. 然后使用命令bin/stop-hugegraph.sh
3. 再次使用bin/start-hugegraph.sh 启动后报错：
```
2020-09-09 18:13:06 35585 [main] [ERROR] com.baidu.hugegraph.dist.HugeGraphServer [] - HugeGremlinServer start error: 
java.util.concurrent.CompletionException: com.baidu.hugegraph.HugeException: Failed to start Gremlin Server
        at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) ~[?:1.8.0_11]
        at java.util.concurrent.CompletableFuture$ExceptionCompletion.run(CompletableFuture.java:1255) ~[?:1.8.0_11]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193) ~[?:1.8.0_11]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2361) ~[?:1.8.0_11]
        at org.apache.tinkerpop.gremlin.server.GremlinServer$1.operationComplete(GremlinServer.java:184) ~[gremlin-server-3.4.3.jar:3.4.3]
        at org.apache.tinkerpop.gremlin.server.GremlinServer$1.operationComplete(GremlinServer.java:172) ~[gremlin-server-3.4.3.jar:3.4.3]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:994) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:553) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_11]
Caused by: com.baidu.hugegraph.HugeException: Failed to start Gremlin Server
        at com.baidu.hugegraph.dist.HugeGremlinServer.lambda$startWithInjectTraversal$0(HugeGremlinServer.java:87) ~[hugegraph-dist-0.10.4.jar:?]
        at com.baidu.hugegraph.dist.HugeGremlinServer$$Lambda$226/1490434838.apply(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$ExceptionCompletion.run(CompletableFuture.java:1246) ~[?:1.8.0_11]
        ... 24 more
Exception in thread "main" java.util.concurrent.CompletionException: com.baidu.hugegraph.HugeException: Failed to start Gremlin Server
        at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205)
        at java.util.concurrent.CompletableFuture$ExceptionCompletion.run(CompletableFuture.java:1255)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2361)
        at org.apache.tinkerpop.gremlin.server.GremlinServer$1.operationComplete(GremlinServer.java:184)
        at org.apache.tinkerpop.gremlin.server.GremlinServer$1.operationComplete(GremlinServer.java:172)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:994)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:553)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.baidu.hugegraph.HugeException: Failed to start Gremlin Server
        at com.baidu.hugegraph.dist.HugeGremlinServer.lambda$startWithInjectTraversal$0(HugeGremlinServer.java:87)
        at com.baidu.hugegraph.dist.HugeGremlinServer$$Lambda$226/1490434838.apply(Unknown Source)


```

### Specifications of environment 环境信息
-  v0.10.4
- like centos 7.5, 4 CPUs, 16G RAM
- hugegraph backend: {mysql 5.7}

**Comment by kevinliang-123** [comment]
> @kevinliang-123 在重新启动之前请确保之前的数据库停止成功，并且释放端口。

似的，确实是之前没有正确停止，找到端口号kill掉后，正常启动，谢谢！
