### ISSUE TITLE
load example 时，报错信息如下，核对配置文件暂未发现问题

### ISSUE THREAD

**Issue by williamJia** [hugegraph/hugegraph#1210]
bin/hugegraph-loader -g hugegraph -f example/file/struct.json -s example/file/schema.groovy

ERROR: Failed to load
Exception in thread "main" null: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> The requested resource [&#47;versions] is not available</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.58</h3></body></html>
        at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
        at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100)
        at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:193)
        at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41)
        at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45)
        at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:122)
        at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:108)
        at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:72)
        at com.baidu.hugegraph.loader.util.HugeClientHolder.newHugeClient(HugeClientHolder.java:45)
        at com.baidu.hugegraph.loader.util.HugeClientHolder.get(HugeClientHolder.java:33)
        at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:108)
        at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:85)
        at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66)

**Comment by williamJia** [comment]
有可能找到原因了，我是自定义了 server 的端口，而 loader 去默认的端口号访问是访问不到信息的，那么需要做的或许是同步 loader 访问 server 的端口号就应该可以了，但是这个loader 的配置文件在什么地方有知道的么？
