### ISSUE TITLE
Customized Paths API，接口调用错误？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#1219]
使用该接口：“Customized Paths API，从一批顶点出发，按（一种）模式遍历经过的全部路径”， 发现报错，错误如下：
Traceback (most recent call last):
  File "custome_path.py", line 34, in <module>
    print(cpath_api(["kg_n_user_1432408074"]))
  File "custome_path.py", line 28, in cpath_api
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

因为hugergaph server里又没日志，特别难排查？请问这个有什么办法知道错在哪里？

**Comment by javeme** [comment]
@597477803 ”400: Bad Request“一般是参数错误，可打印一下返回的错误信息，有详细的提示。

**Comment by 597477803** [comment]
> @597477803 ”400: Bad Request“一般是参数错误，可打印一下返回的错误信息，有详细的提示。

问题是上面报异常就退出了呀，所以没有返回结果

**Comment by javeme** [comment]
@597477803 报异常是否退出是程序控制的，退出之前捕获异常打印一下错误信息就可以，Python具体可参考：https://stackoverflow.com/a/1664074
