### ISSUE TITLE
hugegraph用cassadra做存储后端，发现删除一个边的label时失败，日志如下，请问是什么情况？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#1244]
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to query edges with label '15' for deleting
    at com.baidu.hugegraph.backend.store.cassandra.CassandraTables$Edge.deleteEdgesByLabel(CassandraTables.java:415) ~[hugegraph-cassandra-0.10.4.jar:?]
    at com.baidu.hugegraph.backend.store.cassandra.CassandraTables$Edge.delete(CassandraTables.java:393) ~[hugegraph-cassandra-0.10.4.jar:?]
    at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.mutate(CassandraStore.java:213) ~[hugegraph-cassandra-0.10.4.jar:?]
    at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.mutate(CassandraStore.java:186) ~[hugegraph-cassandra-0.10.4.jar:?]
    at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:244) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.commitMutation2Backend(CachedGraphTransaction.java:209) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:167) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:369) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    at com.baidu.hugegraph.backend.tx.GraphTransaction.removeEdges(GraphTransaction.java:1481) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    ... 10 more
Caused by: com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded)
    at com.datastax.driver.core.exceptions.ReadTimeoutException.copy(ReadTimeoutException.java:88) ~[cassandra-driver-core-3.2.0.jar:?]
    at com.datastax.driver.core.exceptions.ReadTimeoutException.copy(ReadTimeoutException.java:25) ~[cassandra-driver-core-3.2.0.jar:?]
    at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37) ~[cassandra-driver-core-3.2.0.jar:?]
    at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245) ~[cassandra-driver-core-3.2.0.jar:?]
    at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68) ~[cassandra-driver-core-3.2.0.jar:?]
    at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool$Session.execute(CassandraSessionPool.java:194) ~[hugegraph-cassandra-0.10.4.jar:?]
    at com.baidu.hugegraph.backend.store.cassandra.CassandraTables$Edge.deleteEdgesByLabel(CassandraTables.java:413) ~[hugegraph-cassandra-0.10.4.jar:?]
    at com.baidu.hugegraph.backend.store.cassandra.CassandraTables$Edge.delete(CassandraTables.java:393) ~[hugegraph-cassandra-0.10.4.jar:?]
    at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.mutate(CassandraStore.java:213) ~[hugegraph-cassandra-0.10.4.jar:?]
    at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.mutate(CassandraStore.java:186) ~[hugegraph-cassandra-0.10.4.jar:?]
    at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:244) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.commitMutation2Backend(CachedGraphTransaction.java:209) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:167) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:369) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    at com.baidu.hugegraph.backend.tx.GraphTransaction.removeEdges(GraphTransaction.java:1481) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
    ... 10 more

**Comment by zhoney** [comment]
@597477803 根据异常信息是查询label索引超时了，检查下Cassandra集群的状态，是否有节点故障。

如果没有的话，可以提供下这个edgelabel对应的边的数目规模，我们尝试复现下。
