### ISSUE TITLE
vertex.tx_capacity/edge.tx_capacity这两个参数是啥作用？

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph#1246]
vertex.tx_capacity/edge.tx_capacity这两个参数是啥作用？
为什么这个gremlin语句执行时， limit的时候有这个限制？
g.V().hasLabel('XXX').limit(n).drop()

说明：n > vertex.tx_capacity

**Comment by javeme** [comment]
@tmljob 这个是一次性提交的点边数量，可以每100条commit一次。

**Comment by tmljob** [comment]
这个是不是需要和rest-server.properties中的batch.max_vertices_per_batch配套改？
在导入时把batch.max_edges_per_batch 设置成20000，loader的bactch_size也设置成20000，但会hugegraph-server报这个错。

```
 2020-11-18 11:13:21 [batch-worker-18] [WARN ] c.b.h.l.t.TaskManager [] - Batch insert EDGE error, try single insert
12605 java.util.concurrent.CompletionException: class com.baidu.hugegraph.exception.LimitExceedException: Edges size has reached tx capacity 10000
12606         at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_181]
12607         at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_181]
12608         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629) [?:1.8.0_181]
12609         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
12610         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
12611         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
12612 Caused by: com.baidu.hugegraph.exception.ServerException: Edges size has reached tx capacity 10000
12613         at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47) ~[hugegraph-client-1.9.0.jar:1.9.0.0]
12614         at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93) ~[hugegraph-client-1.9.0.jar:1.9.0.0]
12615         at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:198) ~[hugegraph-common-1.8.0.jar:1.8.0.0]
12616         at com.baidu.hugegraph.api.graph.EdgeAPI.create(EdgeAPI.java:59) ~[hugegraph-client-1.9.0.jar:1.9.0.0]
12617         at com.baidu.hugegraph.driver.GraphManager.addEdges(GraphManager.java:260) ~[hugegraph-client-1.9.0.jar:1.9.0.0]
12618         at com.baidu.hugegraph.loader.task.InsertTask.insertBatch(InsertTask.java:104) ~[hugegraph-loader-0.11.0.jar:?]
12619         at com.baidu.hugegraph.loader.task.BatchInsertTask.run(BatchInsertTask.java:54) ~[hugegraph-loader-0.11.0.jar:?]
12620         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_181]
12621         ... 3 more
```

**Comment by javeme** [comment]
@tmljob 不建议把bactch_size设置得过大，一般来说保持1000以内性能较好。

**Comment by tmljob** [comment]
我们把这个batch_size设大是为了提升导入的速度，除了通过设置这个参数调整，还有什么其他参数设置可以提升导入的速度的？

1、把导入的批量大小以及后端批量大小设置为10000，通过impala的parquet文件导入，1亿条边数据(不check顶点)，要耗时3个多小时，平均先来九千多条/秒。

2、后来我们想把这个批量大写调整为20000，会出现如上错误，又把edge.tx_capacity也设置为20000了，但是导入一会出现“failed to do request,read timed out”，响应超时了。

按照批量大小设置为10000 ，导入是比较稳定的，就是想看下还有么有通过调整参数进一步提升导入速度的空间。
