### ISSUE TITLE
按照官方文档配置后，不能启动gremlin-console，提示空指针

### ISSUE THREAD

**Issue by lixuanhng** [hugegraph/hugegraph#1268]
### Expected behavior 期望表现
按照官方文档给出的demo截图，在mac终端输入gremlin-console.sh可以直接使用

### Actual behavior 实际表现
gremlin-console不能启动，报错内容为
Exception in thread "main" java.lang.NullPointerException: Cannot invoke method activate() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.invokeGroovyObjectInvoker(IndyGuardsFiltersAndSignatures.java:163)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
	at org.apache.tinkerpop.gremlin.console.Console$_closure18.doCall(Console.groovy:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356)
	at org.codehaus.groovy.runtime.dgm$186.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
	at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:145)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
	at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:502)

### Steps to reproduce the problem 复现步骤
首先启动hugegraph-server，正常启动没有问题，下面的配置就不贴hugegraph-server的相关配置了

1. 配置gremlin-server.yaml:
host: 127.0.0.1  // 本机IP
port: 8182  // 设定为gremlin-server的端口号
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer

2. 配置rest-server.properties:
gremlinserver.url=http://127.0.0.1:8182

3. gremlin-driver-settings.yaml等配置文件都是默认设置，因为gremlin-server端口就使用的是默认配置localhost:8182，经检查后发现不需要改动

### Specifications of environment 环境信息
- hugegraph version: {v0.10.4}
- operating system: {MACOS 11.0.1}
- hugegraph backend: {cassandra 3.11.2}

检查了两三遍，感觉配置是就是按照官方文档中gremlin-console下client/server那部分进行配置的，很奇怪为什么会启动不了gremlin-console

新手上路，还请不吝赐教，感谢！！

![gremlin-server](https://user-images.githubusercontent.com/40484583/99477639-e55ae900-298d-11eb-9d80-5171f4bf7d48.png)
![rest-server](https://user-images.githubusercontent.com/40484583/99477649-e9870680-298d-11eb-9872-fa761a16499f.png)
![gremlin-报错](https://user-images.githubusercontent.com/40484583/99477716-07546b80-298e-11eb-83e1-1d63a47342a3.png)

**Comment by javeme** [comment]
@lixuanhng 这个是已知Bug，0.11已修复该问题，0.10可参考链接 https://github.com/hugegraph/hugegraph/pull/1047#issuecomment-646652566 下载补丁包。
