### ISSUE TITLE
0.11.2 start fail The server with name 'server-1' already in cluster

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph#1282]
### Expected behavior 期望表现
start OK

### Actual behavior 实际表现
start fail
```
Exception in thread "main" java.lang.IllegalArgumentException: The server with name 'server-1' already in cluster
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:163)
        at com.baidu.hugegraph.util.E.checkArgument(E.java:56)
        at com.baidu.hugegraph.task.ServerInfoManager.initServerInfo(ServerInfoManager.java:142)
        at com.baidu.hugegraph.StandardHugeGraph.serverStarted(StandardHugeGraph.java:220)
        at com.baidu.hugegraph.core.GraphManager.serverStarted(GraphManager.java:237)
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:78)
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:108)
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74)
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81)
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357)
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:398)
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:293)
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:269)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:64)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:133)
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58)
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:55)
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:100)
2020-11-30 20:31:41 22712 [Thread-1] [INFO ] com.baidu.hugegraph.HugeGraph [] - HugeGraph is shutting down
2020-11-30 20:35:22 1675  [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
```

### Specifications of environment 环境信息
- hugegraph version: 0.11.2
- hugegraph backend: hbase 2.1.3

**Comment by zhoney** [comment]
@chencjiajy 
- 如果目标是单个`HugeGraphServer`后端使用`HBase`，那么请确保没有其他的`HugeGraphServer`已经连接到了同一个`namespace`（排查下系统是否有之前启动失败的残留`HugeGraphServer`）。
- 如果目标是多个`HugeGraphServer`连接同一个`namespace`，请保证每个`HugeGraphServer`的`rest-server.properties`中的server.id不同，且只能有一个`server.role=master`，其他的`server.role=worker`
