### ISSUE TITLE
使用hugegraph-client时search索引查询报错Don't accept query based on properties [名称] that are not indexed in label '设备', may not match secondary condition

### ISSUE THREAD

**Issue by aldelee** [hugegraph/hugegraph#1309]
### Expected behavior 期望表现
{type something here...}

hugegraph-client:1.9.1对search索引的字段，java怎么写呢？

这样调用：
hugeClient.graph().listVertices("设备", mapOf("名称" to Text.contains(vertexName)))

抛异常：
com.baidu.hugegraph.exception.ServerException: Don't accept query based on properties [名称] that are not indexed in label '设备', may not match secondary condition
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
	at com.baidu.hugegraph.rest.AbstractRestClient.get(AbstractRestClient.java:260) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
	at com.baidu.hugegraph.api.graph.VertexAPI.list(VertexAPI.java:118) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
	at com.baidu.hugegraph.driver.GraphManager.listVertices(GraphManager.java:160) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
	at com.baidu.hugegraph.driver.GraphManager.listVertices(GraphManager.java:126) ~[hugegraph-client-1.9.1.jar:1.9.1.0]

**Comment by javeme** [comment]
@aldelee 目前rest api仅支持精确匹配和范围匹配，暂时需要使用Gremlin语法`g.V().has('设备', Text.contains('xx'))`。后续会进行增强。
