### ISSUE TITLE
huge-grpah 本地调试报错

### ISSUE THREAD

**Issue by JackyYangPassion** [hugegraph/hugegraph#1364]
### Expected behavior 期望表现
VertexApiTest 运行单元测试报错

### Actual behavior 实际表现
VertexApiTest 运行单元测试报错 详细日志：

`Connected to the target VM, address: '127.0.0.1:62683', transport: 'socket'

javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at com.baidu.hugegraph.api.BaseApiTest$RestClient.get(BaseApiTest.java:117)
	at com.baidu.hugegraph.api.BaseApiTest.lambda$clearGraph$2(BaseApiTest.java:372)
	at com.baidu.hugegraph.api.BaseApiTest.clearGraph(BaseApiTest.java:386)
	at com.baidu.hugegraph.api.BaseApiTest.clearData(BaseApiTest.java:458)
	at com.baidu.hugegraph.api.BaseApiTest.init(BaseApiTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Test ignored.
Disconnected from the target VM, address: '127.0.0.1:62683', transport: 'socket'`

### Specifications of environment 环境信息
- hugegraph version: 0.11.2
- operating system: mac
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by JackyYangPassion** [comment]
已解决，看了下源码，主要是调试时客户端测试用例中没有启动hugeserver mini cluster  这里需要本地或远程启动hugeserver调试

**Comment by Linary** [comment]
@JackyYangPassion 感谢使用和反馈。
