### ISSUE TITLE
HugeFactory.open('...') reports java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by notsharable** [hugegraph/hugegraph#1369]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
gremlin> graph = HugeFactory.open('conf/hugegraph.properties')
graph = HugeFactory.open('conf/hugegraph.properties')
java.lang.String cannot be cast to java.lang.Boolean
Type ':help' or ':h' for help.
Display stack trace? [yN]y
y
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
        at com.baidu.hugegraph.backend.store.BackendProviderFactory.open(BackendProviderFactory.java:49)
        at com.baidu.hugegraph.StandardHugeGraph.loadStoreProvider(StandardHugeGraph.java:411)
        at com.baidu.hugegraph.StandardHugeGraph.<init>(StandardHugeGraph.java:170)
        at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:72)
        at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:63)
        at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:84)
        at com.baidu.hugegraph.HugeFactory$open.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at groovysh_evaluate.run(groovysh_evaluate:3)
		...
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
        at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:168)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
        at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:502)

### Steps to reproduce the problem 复现步骤
1. :remote connect to Hugegraph gremlin server using gremlin-driver-setting.yaml
2. import com.baidu.hugegraph.HugeFactory
3. graph = HugeFactory.open('conf/hugegraph.properties')

#### Vertex/Edge summary 数据量
N/A

#### Vertex/Edge example 数据示例
N/A

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
N/A

### Specifications of environment 环境信息
- hugegraph version: 0.11.2
- operating system:  Windows 10 pro 
- hugegraph backend:  Postgresql v13

**Comment by notsharable** [comment]
Bellow is what I am getting when retrying to get the graph traversal source
gremlin> graph = HugeFactory.open('conf/hugegraph.properties')
graph = HugeFactory.open('conf/hugegraph.properties')
LockGroup 'hugegraph_il_delete' already exists
Type ':help' or ':h' for help.
Display stack trace? [yN]y
y
java.lang.RuntimeException: LockGroup 'hugegraph_il_delete' already exists
        at com.baidu.hugegraph.concurrent.LockManager.create(LockManager.java:45)
        at com.baidu.hugegraph.util.LockUtil.init(LockUtil.java:69)
        at com.baidu.hugegraph.StandardHugeGraph.<init>(StandardHugeGraph.java:167)
        at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:72)
        at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:63)
        at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:84)
        at com.baidu.hugegraph.HugeFactory$open.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at groovysh_evaluate.run(groovysh_evaluate:3)

**Comment by notsharable** [comment]
As a workaround I made a copy of hugegraph.properties and commented out all boolean properties. I am now getting an instance of StandardHuggeGraph and can proceed further a it can be seen below. So closing the issue.

gremlin> graph = HugeFactory.open('conf/hugegraph-small.properties')
graph = HugeFactory.open('conf/hugegraph-small.properties')
==>standardhugegraph[hugegraph]

gremlin> schema = graph.schema();
schema = graph.schema();
main dict load finished, time elapsed 1748 ms
model load finished, time elapsed 98 ms.
gremlin> graph.name();
graph.getName()               graph.name();
==>hugegraph
