### ISSUE TITLE
在batch插入边的时候CPU负载上不去

### ISSUE THREAD

**Issue by Mimori-su** [hugegraph/hugegraph#1412]
### Expected behavior 期望表现
根据压测数据，边的插入应是点插入的三倍

### Actual behavior 实际表现
目前测得点插入差不多是100*200=20k/s，但是插入边的时候在batch size=200的情况下速率和点数据相差无几。

### Status of loaded data 数据状态
边数据来自于我们的内部数据，这些数据中我们以200作为一个batch进行读入，然后插入。
其中有大量的数据在程序中做了判断，不必插入。因此实际插入batch size比统计的数据要低。

### Analysis of log 日志分析
通过查看jstack，看到rest server起了32个线程，但其中只有一个在运行，其他的都在等待。而且锁只有线程自己持有。运行和等待的日志如下：
`"grizzly-http-server-0" #44 prio=5 os_prio=0 tid=0x00007fbbf5fd3000 nid=0xad runnable [0x00007fbb8aaec000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Class.getEnclosingMethod0(Native Method)
	at java.lang.Class.getEnclosingMethodInfo(Class.java:1072)
	at java.lang.Class.isLocalOrAnonymousClass(Class.java:1462)
	at java.lang.Class.isLocalClass(Class.java:1422)
	at com.google.common.reflect.Types$ClassOwnership$2.getOwnerType(Types.java:118)
	at com.google.common.reflect.Types.newParameterizedType(Types.java:102)
	at com.google.common.reflect.Types.newParameterizedTypeWithOwner(Types.java:91)
	at com.google.common.reflect.TypeResolver.resolveParameterizedType(TypeResolver.java:265)
	at com.google.common.reflect.TypeResolver.resolveType(TypeResolver.java:220)
	at com.google.common.reflect.TypeToken.where(TypeToken.java:231)
	at com.datastax.driver.core.TypeTokens.mapOf(TypeTokens.java:113)
	at com.datastax.driver.core.TypeCodec$AbstractMapCodec.<init>(TypeCodec.java:1939)
	at com.datastax.driver.core.TypeCodec$MapCodec.<init>(TypeCodec.java:2117)
	at com.datastax.driver.core.TypeCodec$MapCodec.<init>(TypeCodec.java:2114)
	at com.datastax.driver.core.TypeCodec.map(TypeCodec.java:360)
	at com.datastax.driver.core.CodecRegistry.maybeCreateCodec(CodecRegistry.java:764)
	at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:648)
	at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:631)
	at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:476)
	at com.datastax.driver.core.querybuilder.Utils.convert(Utils.java:348)
	at com.datastax.driver.core.querybuilder.BuiltStatement.getValues(BuiltStatement.java:268)
	at com.datastax.driver.core.BatchStatement.getIdAndValues(BatchStatement.java:90)
	at com.datastax.driver.core.SessionManager.makeRequestMessage(SessionManager.java:676)
	at com.datastax.driver.core.SessionManager.executeAsync(SessionManager.java:143)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
	at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool$Session.commit(CassandraSessionPool.java:158)
	at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.commitTx(CassandraStore.java:371)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:308)
	at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.commitMutation2Backend(CachedGraphTransaction.java:292)
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:223)
	at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:493)
	at com.baidu.hugegraph.StandardHugeGraph$Txs.commit(StandardHugeGraph.java:1237)
	at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.doCommit(StandardHugeGraph.java:1117)
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104)
	at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.commit(StandardHugeGraph.java:1083)
	at com.baidu.hugegraph.api.API.commit(API.java:97)
	at com.baidu.hugegraph.api.graph.BatchAPI.commit(BatchAPI.java:75)
	at com.baidu.hugegraph.api.graph.EdgeAPI.create(EdgeAPI.java:141)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)`

`"grizzly-http-server-31" #75 prio=5 os_prio=0 tid=0x00007fbbf600a800 nid=0xcc waiting on condition [0x00007fbb88bce000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000003ae0b03f8> (a java.util.concurrent.LinkedTransferQueue)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.LinkedTransferQueue.awaitMatch(LinkedTransferQueue.java:737)
	at java.util.concurrent.LinkedTransferQueue.xfer(LinkedTransferQueue.java:647)
	at java.util.concurrent.LinkedTransferQueue.take(LinkedTransferQueue.java:1269)
	at org.glassfish.grizzly.threadpool.FixedThreadPool$BasicWorker.getTask(FixedThreadPool.java:81)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:561)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)`

#### Vertex/Edge summary 数据量
- loaded vertices amount: 260 million
- loaded edges amount: 670 million

### Specifications of environment 环境信息
- hugegraph version: v0.11.2
- operating system: Ubuntu 20.04.1, 16 CPUs, 128G RAM
- hugegraph backend: scylla

**Comment by javeme** [comment]
@Mimori-su 是指CPU负责低，还是指rest线程没有在处理请求？

从堆栈信息来看，该线程（grizzly-http-server-0）是在执行Cassandra的提交操作。
