### ISSUE TITLE
同时开启了Raft和authentication初始化Backend出现错误

### ISSUE THREAD

**Issue by liweidong1216** [hugegraph/hugegraph#1421]
当前版本使用的是hugegraph-0.11.2-b2
复现步骤：
1、在hugegraph.properties配置文件中，设置raft.mode=true
2、在rest-server.properties 配置文件中,设置
# authentication
auth.authenticator=com.baidu.hugegraph.auth.ConfigAuthenticator
#auth.admin_token=162f7848-0b6d-4faf-b557-3a0797869c55
auth.user_tokens=[admin:9fd95c9c-711b-415b-b85f-d4df46ba5c31]
在执行init-store.sh的时候出现空指针异常错误，并一直停住，按Ctrl+C跳出，正常启动服务
这个时候，可以使用用户名：admin，密码：9fd95c9c-711b-415b-b85f-d4df46ba5c31连接服务器，并正常的使用
错误信息如下
[root@hadoop02 hugegraph-0.11.2]# bin/init-store.sh 
Initializing HugeGraph Store...
2021-04-16 23:52:25 565   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2021-04-16 23:52:25 634   [db-open-1] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: /opt/hugegraph/hugegraph-0.11.2/data/m
2021-04-16 23:52:25 743   [db-open-1] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Failed to open RocksDB '/opt/hugegraph/hugegraph-0.11.2/data/m' with database 'hugegraph', try to init CF later
2021-04-16 23:52:25 772   [db-open-1] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: /opt/hugegraph/hugegraph-0.11.2/data/s
main dict load finished, time elapsed 561 ms
model load finished, time elapsed 89 ms.
2021-04-16 23:52:26 1475  [db-open-1] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: /opt/hugegraph/hugegraph-0.11.2/data/g
2021-04-16 23:52:27 1943  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Graph 'hugegraph' has been initialized
2021-04-16 23:52:27 1944  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Close graph standardhugegraph[hugegraph]
2021-04-16 23:52:27 1961  [main] [INFO ] com.baidu.hugegraph.backend.store.BackendProviderFactory [] - Opening backend store 'rocksdb' in raft mode for graph 'hugegraph'
2021-04-16 23:52:27 2001  [main] [INFO ] com.alipay.sofa.jraft.util.JRaftServiceLoader [] - SPI service [com.alipay.sofa.jraft.rpc.RaftRpcFactory - com.alipay.sofa.jraft.rpc.impl.BoltRaftRpcFactory] loading.
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Log4j2 ]
2021-04-16 23:52:27 2057  [main] [INFO ] com.alipay.sofa.common.log [] - Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Log4j2 ]
2021-04-16 23:52:27 2226  [main] [INFO ] com.baidu.hugegraph.backend.store.raft.RaftSharedContext [] - RPC server is started successfully
2021-04-16 23:52:27 2229  [main] [INFO ] com.baidu.hugegraph.backend.store.raft.RaftBackendStoreProvider [] - Init raft backend system store
2021-04-16 23:52:27 2232  [main] [INFO ] com.baidu.hugegraph.backend.store.raft.RaftBackendStoreProvider [] - Init raft backend schema store
2021-04-16 23:52:27 2233  [db-open-1] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: /opt/hugegraph/hugegraph-0.11.2/data/m
2021-04-16 23:52:27 2273  [db-open-1] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: /opt/hugegraph/hugegraph-0.11.2/data/s
2021-04-16 23:52:27 2320  [main] [INFO ] com.baidu.hugegraph.backend.store.raft.RaftBackendStoreProvider [] - Init raft backend graph store
2021-04-16 23:52:27 2321  [db-open-1] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: /opt/hugegraph/hugegraph-0.11.2/data/g
Exception in thread "main" java.lang.NullPointerException
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore.queryByRaft(RaftBackendStore.java:200)
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore.query(RaftBackendStore.java:137)
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.query(AbstractTransaction.java:157)
        at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.queryByName(SchemaIndexTransaction.java:99)
        at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.query(SchemaIndexTransaction.java:77)
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.getSchema(SchemaTransaction.java:322)
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getSchema(CachedSchemaTransaction.java:240)
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.getVertexLabel(SchemaTransaction.java:178)
        at com.baidu.hugegraph.StandardHugeGraph.vertexLabel(StandardHugeGraph.java:688)
        at com.baidu.hugegraph.auth.EntityManager.queryEntity(EntityManager.java:156)
        at com.baidu.hugegraph.auth.EntityManager.query(EntityManager.java:137)
        at com.baidu.hugegraph.auth.StandardUserManager.findUser(StandardUserManager.java:151)
        at com.baidu.hugegraph.auth.StandardAuthenticator.initAdminUser(StandardAuthenticator.java:50)
        at com.baidu.hugegraph.auth.StandardAuthenticator.initAdminUser(StandardAuthenticator.java:124)
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:102)

### Specifications of environment 环境信息
- hugegraph version: v0.11.2-b2
- operating system: centos 7.4, 32 CPUs, 64G RAM
- hugegraph backend: rocksdb

**Comment by lxb1111** [comment]
@liweidong1216 master的代码已经修复该问题，可以拉取编译进行使用。

**Comment by liweidong1216** [comment]
> @liweidong1216 master的代码已经修复该问题，可以拉取编译进行使用。

好的，感谢
