### ISSUE TITLE
批量添加顶点, 这种该如何解决嘞，麻烦了

### ISSUE THREAD

**Issue by MySabers** [hugegraph/hugegraph#1426]
```java
Exception in thread "main" class com.baidu.hugegraph.backend.BackendException: Failed to commit 202 statements: 'INSERT INTO g_v (LABEL,PROPERTIES,ID) VALUES (11,{52:0x0d31302e3235352e31332e313335,53:0x09e5b180e59f9fe7bd91,54:0x00,55:0x00,56:0x00,57:0x00,58:0x0c386365633462613061633031,59:0x023a3a,60:0x838047},0x8f31313a31302e3235352e31332e313335);'...
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93)
	at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:198)
	at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:178)
	at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:56)
	at com.baidu.hugegraph.driver.GraphManager.addVertices(GraphManager.java:95)
	at output.HugeGraphOutput.executeBatch(HugeGraphOutput.java:122)
	at output.HugeGraphOutput.insert(HugeGraphOutput.java:194)
	at output.HugeGraphOutput.main(HugeGraphOutput.java:162)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Batch too large
```

**Comment by imbajin** [comment]
简单看提示了 `InvalidQueryException: Batch too large` , 你可以把异常栈贴详细一些

然后看看是不是 batch 过大? 

先试试单条插入成功 --> 小批量插入成功 --> 控制条数大批量看看呗.  (一般 batch 控制在500条左右/次)

**Comment by MySabers** [comment]
事情的原因是这样的，单条和小批量都可以插入成功，然后我们修改了服务端的`rest-server.properties`，增加了两个配置项`batch.max_edges_per_batch=10000` 和 `batch.max_vertices_per_batch=5000` ，尝试使用更大的批量，却出现了如上异常，有什么办法可以绕过这个异常吗。感谢回复

**Comment by imbajin** [comment]
唔... 建议一般 batch 数其实不需要单独调整呢, 默认500条/次, 一般1000就挺大了, 调整的原因是啥呢?

如果是为了**更快的**导入性能, 不妨说一下现在的总导入速度, 后端之类的, 从我之前测试来看 `batchSize` 并不是关键影响导入的瓶颈, 你可以尝试一下调整发送的方式(并发), 参考 loader 单台机器写都有几十万/s, 无需调整批量数的

至于那个异常看起来是 Cassandra 那边抛出的, 说明方式已经不对了, 绕过可能隐患更多

**Comment by MySabers** [comment]
> 唔... 建议一般 batch 数其实不需要单独调整呢, 默认500条/次, 一般1000就挺大了, 调整的原因是啥呢?
> 
> 如果是为了**更快的**导入性能, 不妨说一下现在的总导入速度, 后端之类的, 从我之前测试来看 `batchSize` 并不是关键影响导入的瓶颈, 你可以尝试一下调整发送的方式(并发), 参考 loader 单台机器写都有几十万/s, 无需调整批量数的
> 
> 至于那个异常看起来是 Cassandra 那边抛出的, 说明方式已经不对了, 绕过可能隐患更多

OK，我们也确实发现了异常的原因跟 `Cassandra` 的配置有关，真的非常感谢！
