### ISSUE TITLE
backend使用mysql，持续使用一段时间后，插入数据报错。

### ISSUE THREAD

**Issue by hjrowen** [hugegraph/hugegraph#1441]
持续使用一段时间后，插入数据会报错。
想通过jdbc.url配置带入一些参数，但发现会启动失败。

报错信息如下。
```
2021-05-06 17:39:19 668070101 [grizzly-http-server-3] [ERROR] com.baidu.hugegraph.server.RestServer [] - Failed to rollback
com.baidu.hugegraph.backend.BackendException: Failed to rollback
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.rollback(MysqlSessions.java:426) ~[hugegraph-mysql-0.11.2.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlStore.rollbackTx(MysqlStore.java:311) ~[hugegraph-mysql-0.11.2.jar:?]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.rollback(AbstractTransaction.java:244) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.rollback(IndexableTransaction.java:72) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.rollback(GraphTransaction.java:506) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
        at com.baidu.hugegraph.StandardHugeGraph$Txs.rollback(StandardHugeGraph.java:1241) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
        at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.doRollback(StandardHugeGraph.java:1123) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
        at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.rollback(AbstractTransaction.java:114) ~[gremlin-core-3.4.3.jar:3.4.3]
        at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.rollback(StandardHugeGraph.java:1092) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
        at com.baidu.hugegraph.api.API.lambda$commit$0(API.java:89) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
        at com.baidu.hugegraph.api.API.commit(API.java:107) [hugegraph-api-0.11.2.jar:0.58.0.0]
        at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:94) [hugegraph-api-0.11.2.jar:0.58.0.0]
        at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.1.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [grizzly-http-server-2.4.4.jar:2.4.4]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [grizzly-framework-2.4.4.jar:2.4.4]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [grizzly-framework-2.4.4.jar:2.4.4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_275]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_275]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_275]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_275]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4576) ~[mysql-connector-java-5.1.45.jar:5.1.45]
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.rollback(MysqlSessions.java:424) ~[hugegraph-mysql-0.11.2.jar:?]
        ... 36 more
```

### Specifications of environment 环境信息
- hugegraph version: 0.11.2
- operating system: Linux version 4.18.0-147.5.1.el8_1.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC)) 
- hugegraph backend: MySQL 8.0.16-X-Cluster-1.0.2

**Comment by imbajin** [comment]
可以提供多一些相关信息么?

比如具体的复现方式, 和相关复现数据, 以及你添加了一些 `jdbc` 参数具体是什么 (加之前是正常? 加之后出现报错之类)

**Comment by hjrowen** [comment]
# 复现
后台程序启动一段时间（2~3天），使用hugeclient插入数据，就会报错（hugeclient 每次使用完都有进行close）。

# 配置 
目前的配置如下，
# mysql backend config
jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://********:3306
jdbc.username=*****
jdbc.password=*****
jdbc.reconnect_max_times=3
jdbc.reconnect_interval=3
jdbc.sslmode=false

我尝试在设置jdbc.url 如下：
jdbc:mysql://********:3306/csg_hugegraph？zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true

但会启动失败，报错如下：

2021-05-08 15:22:59 9682  [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Gremlin Server - shutdown complete
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to query [`Query * from PROPERTY_KEY where [NAME == ~backend_info]`]
        at com.baidu.hugegraph.backend.store.mysql.MysqlTable.query(MysqlTable.java:371)
        at com.baidu.hugegraph.backend.store.mysql.MysqlTable.query(MysqlTable.java:351)
        at com.baidu.hugegraph.backend.store.mysql.MysqlStore.query(MysqlStore.java:273)
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.query(AbstractTransaction.java:166)
        at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.queryByName(SchemaIndexTransaction.java:86)
        at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.query(SchemaIndexTransaction.java:77)
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.getSchema(SchemaTransaction.java:323)
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getSchema(CachedSchemaTransaction.java:234)
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.getPropertyKey(SchemaTransaction.java:128)
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.info(BackendStoreSystemInfo.java:72)
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:92)
        at com.baidu.hugegraph.core.GraphManager.checkBackendVersionOrExit(GraphManager.java:214)
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:77)
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:108)
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74)
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81)
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357)
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:398)
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:293)
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:269)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:64)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:133)
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58)
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:55)
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:100)
Caused by: java.sql.SQLException: No database selected
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.select(MysqlSessions.java:469)
        at com.baidu.hugegraph.backend.store.mysql.MysqlTable.query(MysqlTable.java:367)

**Comment by hjrowen** [comment]
客户端报错如下：
2021-05-08 15:19:20.676| ERROR| business-mgmt|192.168.3.108|-1|b91cf38c96ee4e2195c61a85ae123ca9|e1828cd01779405d8e27931926423ec5|[BusinessScenarioClientHolder-pool-1 thread-7]|c.q.q.c.r.i.BusinessScenarioClientHolder - [buildGraph,327] - Failed to open transaction
com.baidu.hugegraph.exception.ServerException: Failed to open transaction
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93)
	at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:198)
	at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:172)
	at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:49)
	at com.baidu.hugegraph.driver.GraphManager.addVertex(GraphManager.java:58)
	at com.baidu.hugegraph.driver.GraphManager.addVertex(GraphManager.java:73)

**Comment by imbajin** [comment]
似乎是有两个问题么?  是下面的推测么, 不对麻烦说一下:
1. 一个是你没修改 `jdbc_url` 之前, 插入数据就有` Failed to open tx..`的报错
2. 另一个是你修改了 `jdbc_url` 之后, 再启动 `server` 就报错了? 

先说第二个, 从 `Caused by: java.sql.SQLException: No database selected` 来看, 可能是没有正确识别你传入的 DB 参数
问题看起来应该是在后面改的 `jdbc_url` 上面, 可以把程序运行时拼接后的完整 URI 打印一下, 看看是不是拼接的问题. (后续这里补充个日志输出完整 URL, 你可以先自己加一下日志输出)

至于第一个问题, 不修改 jdbc_url 之前, 有具体的复现方式么? 需要2~3天才能么

**Comment by imbajin** [comment]
最新版代码已经默认添加相关日志，暂时关闭 issue, 期待你的新反馈再开启
