### ISSUE TITLE
The name of property key can't be null

### ISSUE THREAD

**Issue by kinda830** [hugegraph/hugegraph#1479]
hugegraph : 0.11.2
java-client: 1.94, 1.9.3, 1.9.1 都试，创建protertykey 时，出现这个问题。代码对比过官方文档，代码如下：
HugeClient hugeClient = HugeClient.builder("http://172.16.29.15:8383", "hugegraph").build();
SchemaManager schema = hugeClient.schema();
schema.propertyKey("name").asText().ifNotExist().create();
schema.propertyKey("sex").asText().ifNotExist().create();
schema.propertyKey("age").asInt().ifNotExist().create();
hugeClient.close();

com.baidu.hugegraph.exception.ServerException: The name of property key can't be null
        at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47) ~[hugegraph-client-1.9.4.jar:1.9.4.0]
        at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93) ~[hugegraph-client-1.9.4.jar:1.9.4.0]
        at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:198) ~[hugegraph-common-1.8.4.jar:1.8.4.0]
        at com.baidu.hugegraph.rest.AbstractRestClient.post(AbstractRestClient.java:172) ~[hugegraph-common-1.8.4.jar:1.8.4.0]
        at com.baidu.hugegraph.api.schema.PropertyKeyAPI.create(PropertyKeyAPI.java:47) ~[hugegraph-client-1.9.4.jar:1.9.4.0]
        at com.baidu.hugegraph.driver.SchemaManager.addPropertyKey(SchemaManager.java:79) ~[hugegraph-client-1.9.4.jar:1.9.4.0]
        at com.baidu.hugegraph.structure.schema.PropertyKey$BuilderImpl.create(PropertyKey.java:158) ~[hugegraph-client-1.9.4.jar:1.9.4.0]
        at com.baidu.hugegraph.structure.schema.PropertyKey$BuilderImpl.create(PropertyKey.java:141) ~[hugegraph-client-1.9.4.jar:1.9.4.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at com.baidu.hugegraph.structure.schema.BuilderProxy.invoke(BuilderProxy.java:56) ~[hugegraph-client-1.9.4.jar:1.9.4.0]
        at com.sun.proxy.$Proxy83.create(Unknown Source) ~[na:na]
        at com.deepexi.kb.dao.testDao.createProperty(testDao.java:46) ~[classes/:na]
        at com.deepexi.kb.service.impl.testServiceImpl.createData(testServiceImpl.java:106)

**Comment by imbajin** [comment]
请使用默认提供的模板 (标题 + 内容)

然后日志信息(写入代码块中), 环境填写到**对应**位置, 这样问题会被更快响应和处理. 谢谢~

**Comment by kinda830** [comment]
> 请使用默认提供的模板 (标题 + 内容)
> 
> 然后日志信息(写入代码块中), 环境填写到**对应**位置, 这样问题会被更快响应和处理. 谢谢~
