### ISSUE TITLE
[Question] Druid + Hugegraph maxActive配置疑问

### ISSUE THREAD

**Issue by xfs1010** [hugegraph/hugegraph#1521]
## Environment ( 环境信息 - 必填 )
- **Server Version**: v0.11.2
- **Backend**: MySQL8 + Druid
- **OS**: 4 CPUs, 8 G RAM, Centos 7

## Your Question ( 问题描述 )
我自定写了个Driver在`connect`中返回Druid的connection，然后在`properties`的配置中jdbc.driver选择我自己写的Driver，serializer和backend选择MySQL，初步测试运行没啥问题。
但是在测试过程中，我发现如果把Druid的maxActive设置的比较小（比如50），调用几次批量添加点的接口后HugeGraph就不能正常返回结果了。
我的问题是：假定我的restserver.max_worker_threads是x，一般我应该把maxActive设置成多少比较合适？看起来hugegraph自己也会保留连接，有什么大概的公示可以估算下吗？顺便问下如果我想了解源码的话对应代码在哪块？

**Comment by imbajin** [comment]
首先, mysql 这里构建 URI 相关的代码可以参考 [MysqlSessions](https://github.com/hugegraph/hugegraph/blob/f22d03fdd608b0aa9384f3c90a3b628d49f1e63e/hugegraph-mysql/src/main/java/com/baidu/hugegraph/backend/store/mysql/MysqlSessions.java#L215) (配置同理)

其次 graph server的 max_threads 一般其实你不用调整, 它是工作线程数, 跟你说的 druid 的 max_active 没看出有什么必然关系, 一个是控制最大的处理并发的, 一个是处理请求最大存活时间的把(虽然我不熟悉 druid)

**Comment by xfs1010** [comment]
非常感谢回答~
我用的Druid是Alibaba的连接池Druid
maxActive大意是连接池的最大连接数，如果HugeGraph所有连接都从Druid获取的话，那么我理解这个值不能低于HugeGraph需要的连接数。
所以我才想问有没有什么办法可以估算下HugeGraph需要连接数的最大值，这个最大值是不是跟`restserver.max_worker_threads`有点关系。

错误信息如下：从日志来看是直接超时了，一共也就一百多个点
```java
2021-06-30 10:54:51.269  WARN 9643 --- [erver-worker-19] o.a.t.g.s.h.HttpGremlinEndpointHandler   : Invalid request - responding with 500 Internal Server Error and Evaluation exceeded the configured 'evaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.V('env_node~environment_dev').out().has('name', 'mysql-8')]

java.util.concurrent.TimeoutException: Evaluation exceeded the configured 'evaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.V('env_node~environment_dev').out().has('name', 'mysql-8')]
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$1(GremlinExecutor.java:321) ~[gremlin-groovy-3.4.11.jar:3.4.11]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-all-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-all-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-all-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-all-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.59.Final.jar:4.1.59.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]

```

**Comment by imbajin** [comment]
可以的, 最简单的办法就是看你正常负载的时候, 是不是所有的 graph-rest workers 都在干活忙着了.

直接 for 循环打印 10秒每秒对应的 `jstack` 信息, 大概看看就行. 更简单图形化的方式就用 arthas 的 `dashboard/thread` 命令就能看出了.

一般来说因为大部分请求都不是计算密集型的, 所以不太容易阻塞在这上面. 如果超时了, 你可以看看当时线程在忙什么

**Comment by cleverpig** [comment]
@xfs1010 “Evaluation exceeded the configured 'evaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request”——半分钟超时、一百多个点，导致查询塞车。
如果连接池正常的话，这个问题和huge主机、数据库服务器性能有关。
