### ISSUE TITLE
graph.iterateEdges(1000) 报错 Not support quering edges based on paging and [vertex, direction, label, properties, offset] together

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#158]
### Expected behavior 期望表现
分页方式遍历边

### Actual behavior 实际表现
        Iterator<Edge> edges = graph.iterateEdges(1000);
        while (edges.hasNext()) {
            // 这一批的1000条迭代完会自动获取下一个1000条
            Edge edge = edges.next();
        }

在while那一行报错:
Exception in thread "main" class java.lang.IllegalArgumentException: Not support quering edges based on paging and [vertex, direction, label, properties, offset] together
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:169)
	at com.baidu.hugegraph.api.graph.EdgeAPI.list(EdgeAPI.java:108)
	at com.baidu.hugegraph.driver.GraphManager.lambda$iterateEdges$1(GraphManager.java:294)
	at com.baidu.hugegraph.structure.graph.GraphIterator.hasNext(GraphIterator.java:53)

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by fisherinbox** [comment]
@Linary 请问这是server的bug还是hugeclient的bug

**Comment by Linary** [comment]
client 的 bug
