### ISSUE TITLE
[Question] HBase 2.1.0-cdh6.3.2 后端初始化数据库报 PleaseHoldException

### ISSUE THREAD

**Issue by chenygie** [hugegraph/hugegraph#1588]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: hbase 
- OS: 16 CPUs, 64 G RAM, Centos 7.x 
- hbase 版本  HBase 2.1.0-cdh6.3.2

### Your Question (问题描述)

以hbase 作为后端，初始化数据库
```java
(base) [root@chencdhmaster bin]# ./init-store.sh 
Initializing HugeGraph Store...
2021-08-26 11:44:03 790   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2021-08-26 11:44:03 1008  [main] [WARN ] org.apache.hadoop.util.NativeCodeLoader [] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-08-26 11:44:04 1173  [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Connect 0x62727399 to 10.10.0.25:2181 with session timeout=90000ms, retries 3, retry interval 1000ms, keepAlive=60000ms
2021-08-26 11:44:04 1413  [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Connect 0x5e81e5ac to 10.10.0.25:2181 with session timeout=90000ms, retries 3, retry interval 1000ms, keepAlive=60000ms
main dict load finished, time elapsed 846 ms
model load finished, time elapsed 37 ms.
2021-08-26 11:44:05 2325  [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Connect 0x26425897 to 10.10.0.25:2181 with session timeout=90000ms, retries 3, retry interval 1000ms, keepAlive=60000ms
2021-08-26 11:44:09 6838  [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=6, retries=16, started=4484 ms ago, cancelled=false, msg=org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
        at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2982)
        at org.apache.hadoop.hbase.master.HMaster.getNamespaces(HMaster.java:3278)
        at org.apache.hadoop.hbase.master.MasterRpcServices.listNamespaceDescriptors(MasterRpcServices.java:1233)
        at org.apache.hadoop.hbase.shaded.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:413)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:130)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:324)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:304)
, details=, see https://s.apache.org/timeout
2021-08-26 11:44:13 10852 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=7, retries=16, started=8498 ms ago, cancelled=false, msg=org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
        at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2982)
        at org.apache.hadoop.hbase.master.HMaster.getNamespaces(HMaster.java:3278)
        at org.apache.hadoop.hbase.master.MasterRpcServices.listNamespaceDescriptors(MasterRpcServices.java:1233)
        at org.apache.hadoop.hbase.shaded.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:413)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:130)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:324)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:304)
, details=, see https://s.apache.org/timeout
````

**Comment by benbenr** [comment]
@chenygie 老哥，你好。 你那有 HBase 2.1.0-cdh6.3.2 的包么，我找了好久没找到。 求一个。 benr0414@126.com 谢谢。 
可能找的姿势不太对。 感谢大佬.

**Comment by chenygie** [comment]
> @chenygie 老哥，你好。 你那有 HBase 2.1.0-cdh6.3.2 的包么，我找了好久没找到。 求一个。 [benr0414@126.com](mailto:benr0414@126.com) 谢谢。 可能找的姿势不太对。 感谢大佬.
兄弟，这个文件有点大
