### ISSUE TITLE
[ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to parse entry: 0x86313a7461736b34:

### ISSUE THREAD

**Issue by ighack** [hugegraph/hugegraph#1590]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: 0.11.2
- Backend: HBase 2.1.1 CDH 6.3.2

我将hbase和hadoop的jar包都换成了对就的cdh版本
配制中除了改地址和端口其他的没改动

### Expected & Actual behavior (期望与实际表现)

```
graph.schema().propertyKey("name").asText().ifNotExist().create()
graph.schema().propertyKey("owner").asText().ifNotExist().create()
graph.schema().propertyKey("datetime").asDate()ifNotExist().create()

task = graph.schema().vertexLabel("task").properties("name", "owner", "datetime").primaryKeys("name").ifNotExist().create()

depend = graph.schema().edgeLabel("depend").sourceLabel("task").targetLabel("task").properties("owner","datetime").ifNotExist().create()

task1 = graph.addVertex(T.label, "task", "name", "task1", "owner", "wk", "datetime", "2021-08-01 10:01:01")
task2 = graph.addVertex(T.label, "task", "name", "task2", "owner", "wk", "datetime", "2021-08-01 10:02:01")
task3 = graph.addVertex(T.label, "task", "name", "task3", "owner", "zs", "datetime", "2021-08-01 11:02:01")
task4 = graph.addVertex(T.label, "task", "name", "task4", "owner", "ls", "datetime", "2021-08-02 10:01:01")

task4.addEdge("depend", task2, "owner", "wk","datetime","2021-08-01 10:01:01")
task3.addEdge("depend", task2, "owner", "wk","datetime","2021-08-01 10:01:01")
task2.addEdge("depend", task1, "owner", "wk","datetime","2021-08-01 10:01:01")
```

g.V()是看不到边的数据。日志中有报错

```
2021-08-27 13:55:57 12088908 [gremlin-server-exec-29] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to parse entry: 0x86313a7461736b34: [�1:task2=wk�����H]
java.lang.IllegalStateException: Invalid entry) with unknown type(134): 0x8208010086313a7461736b32
	at com.google.common.base.Preconditions.checkState(Preconditions.java:531) ~[guava-25.1-jre.jar:?]
	at com.baidu.hugegraph.util.E.checkState(E.java:68) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.parseColumn(BinarySerializer.java:323) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.readVertex(BinarySerializer.java:425) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.parseEntry(GraphTransaction.java:1815) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.lambda$queryEdgesFromBackend$7(GraphTransaction.java:945) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.iterator.FlatMapperIterator.fetch(FlatMapperIterator.java:62) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
	at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:40) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
	at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.queryEdgesFromBackend(CachedGraphTransaction.java:271) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.queryEdges(GraphTransaction.java:903) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.StandardHugeGraph.edges(StandardHugeGraph.java:601) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.traversal.optimize.HugeVertexStep.edges(HugeVertexStep.java:164) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.traversal.optimize.HugeVertexStep.flatMap(HugeVertexStep.java:79) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:49) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.DedupGlobalStep.processNextStart(DedupGlobalStep.java:105) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:197) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:245) ~[gremlin-server-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:272) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_271]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_271]
	at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:1538) [hugegraph-api-0.11.2.jar:0.58.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]

```

![20210827134537790](https://user-images.githubusercontent.com/6670377/131080221-7ccc1093-9faf-4bdf-ab5d-1373796b1e7b.png)

**Comment by imbajin** [comment]
选择 hbase 时, 这下面这两个都写 hbase
backend=hbase
serializer=hbase # 不是写 text

否则序列化方式有误, 是不能正常使用的, [文档配置](https://hugegraph.github.io/hugegraph-doc/config/config-option.html)页有详细说明

mysql 的话同理, 下面两个都写 mysql
backend=mysql
serializer=mysql

**Comment by ighack** [comment]
backend：使用的后端存储，可选值有 memory、cassandra、scylladb 和 rocksdb；
serializer：主要为内部使用，用于将 schema、vertex 和 edge 序列化到后端，对应的可选值为 text、cassandra、scylladb 和 binary；

我看到文档是这样说的。
你给我的文档我看到了

**Comment by imbajin** [comment]
文档之前描述的确不够清晰, 如果方便的话, 你可以改成一个觉得更好理解的方式, 然后在 doc 的仓库提个 PR 帮助改善一下, 蟹蟹
