### ISSUE TITLE
[Question] 使用多个相同的key做 has() 查询失败

### ISSUE THREAD

**Issue by Ckuangf** [hugegraph/hugegraph#1591]
### Problem Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: Cassandra
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

查询的时候出现与预期不符合的结果。
**场景1：**
使用两次has("tag",“x'x”)，查询失败，抛出异常
![image](https://user-images.githubusercontent.com/31173360/131097765-ef12d8ed-7b3b-4af2-8f67-b5be6df5f4b5.png)

异常信息：
2021-08-27 14:29:29 1030156 [gremlin-server-exec-3] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Expect one user-property value of field '6', but got '2'
java.lang.IllegalStateException: Expect one user-property value of field '6', but got '2'
 at com.google.common.base.Preconditions.checkState(Preconditions.java:531) ~[guava-25.1-jre.jar:?]
 at com.baidu.hugegraph.util.E.checkState(E.java:68) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
 at com.baidu.hugegraph.backend.query.ConditionQuery.userpropValue(ConditionQuery.java:344) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.constructSearchQuery(GraphIndexTransaction.java:741) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.doSearchIndex(GraphIndexTransaction.java:463) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.queryByUserprop(GraphIndexTransaction.java:439) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.queryIndex(GraphIndexTransaction.java:364) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.backend.tx.GraphTransaction.indexQuery(GraphTransaction.java:1394) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.backend.tx.GraphTransaction.optimizeQueries(GraphTransaction.java:1295) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.backend.tx.GraphTransaction.query(GraphTransaction.java:519) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.backend.tx.GraphTransaction.queryVerticesFromBackend(GraphTransaction.java:756) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.queryVerticesFromBackend(CachedGraphTransaction.java:186) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.backend.tx.GraphTransaction.queryVertices(GraphTransaction.java:745) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.StandardHugeGraph.vertices(StandardHugeGraph.java:557) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.vertices(HugeGraphStep.java:117) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.lambda$new$0(HugeGraphStep.java:68) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
 at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:155) ~[gremlin-core-3.4.3.jar:3.4.3]
 at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.4.3.jar:3.4.3]
 at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:197) ~[gremlin-core-3.4.3.jar:3.4.3]
 at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62) ~[gremlin-core-3.4.3.jar:3.4.3]
 at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85) ~[gremlin-core-3.4.3.jar:3.4.3]
 at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382) ~[gremlin-core-3.4.3.jar:3.4.3]
 at org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:245) ~[gremlin-server-3.4.3.jar:3.4.3]
 at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36) ~[gremlin-core-3.4.3.jar:3.4.3]
 at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:272) ~[gremlin-groovy-3.4.3.jar:3.4.3]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_291]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_291]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_291]
 at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:1537) [hugegraph-api-0.11.2.jar:0.58.0.0]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_291]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_291]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]

**场景2：**
在场景1的基础上使用out()和in()查询之后，可以正常查询。
![image](https://user-images.githubusercontent.com/31173360/131097739-35b0d81f-2938-4218-a836-f1a73252a41f.png)

异常分析：
场景1中的异常会调用以下方法：
![image](https://user-images.githubusercontent.com/31173360/131084236-1d10e123-c5af-485f-acd4-e6f78146ad38.png)
![image](https://user-images.githubusercontent.com/31173360/131084246-655ec023-0a00-4a95-8a8f-df67c67a57ae.png)
这里会把多个相同key的查询条件放在一个set中，导致j检查失败抛出异常。

**问题点：**
1. 场景1中的查询处理方式为啥会做这样的判断，难道在直接进行所有顶点遍历的时候，不能多次使用相同key作过滤么。
2. 如果问题1是hugegraph中是做了这里的限制，那要怎么写这种多个相同key做过滤的查询条件呢。
3. 为什么使用了out() in() 之后可以正常查询了

**Comment by Ckuangf** [comment]
> `g.V().hasLabel().out(a).in(a).has("tag",Text.contains("20")).has("tag",Text.contains("6"))` 这个之所以能查询, 是因为`in(x).has(x,xx).has(x,xx)` 被合并为了一个不走索引的 step (语义变化了一点)
> 
> 在查询语句末尾带上一个 `explain()` 可以看到一个查询的分解和合并优化.
> 
> PS: 另外不是大佬, 是大菜 🧷

啊，hugegraph这边查询的情况也是和titan(比较老的版本) 一样么，只有V()/ E() 后面的条件才走索引，而经过了out()这种的语法之后，就是下一个迭代器中整体遍历了么

那还有这个错误的情况下， 应该是需要修复的bug吧，这里这种查询方式应该是需要被支持的

**Comment by imbajin** [comment]
跟 janus/titan 不是完全一样的, 不少地方是有定制优化的, 详细你可以看看相关 XxStep 的转换的地方. 总体分两大类

另外讨论后, 目前这个视为暂不直接支持, 或的语义可以支持, 与的话用 filter 来实现, 因为本身也没有走两次索引, 目前先用 filter 代替 (后续是否考虑单独支持, 要看安排了)

**Comment by Ckuangf** [comment]
> 跟 janus/titan 不是完全一样的, 不少地方是有定制优化的, 详细你可以看看相关 XxStep 的转换的地方. 总体分两大类
> 
> 另外讨论后, 目前这个视为暂不直接支持, 或的语义可以支持, 与的话用 filter 来实现, 因为本身也没有走两次索引, 目前先用 filter 代替 (后续是否考虑单独支持, 要看安排了)

好的，了解，谢谢大菜
![image](https://user-images.githubusercontent.com/31173360/131302009-cd153de0-968f-49b5-ba1b-a46ad404318a.png)
