### ISSUE TITLE
[Question] HBase 后端，不通过init-store.sh初始化，采用手动创建元数据的方案可行吗？

### ISSUE THREAD

**Issue by daoerz** [hugegraph/hugegraph#1592]
### Problem Type (问题类型)

server status (启动/运行异常)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: HBase
- Centos 7.9

### Your Question (问题描述)

因环境权限要求，不允许程序中的用户创建hbase的namespace，无法执行init-store.sh。
根据另一环境中的元数据，进行了手动创建，但仍会提示没有进行初始化。

问题：这种手动初始化的操作是否可行？若不可行，hugegraph中hbase的用户在哪里配置？

shell 如下：

`
create 'hugegraph:vl', 'f'
create 'hugegraph:s_vi', 'f'
create 'hugegraph:s_v', 'f'
create 'hugegraph:s_ui', 'f'
create 'hugegraph:s_si', 'f'
create 'hugegraph:s_oe', 'f'
create 'hugegraph:s_li', 'f'
create 'hugegraph:s_ii', 'f'
create 'hugegraph:s_ie', 'f'
create 'hugegraph:s_hi', 'f'
create 'hugegraph:s_fi', 'f'
create 'hugegraph:s_ei', 'f'
create 'hugegraph:s_di', 'f'
create 'hugegraph:s_ai', 'f'
create 'hugegraph:pk', 'f'
create 'hugegraph:m_si', 'f'
create 'hugegraph:il', 'f'
create 'hugegraph:g_vi', 'f'
create 'hugegraph:g_v', 'f'
create 'hugegraph:g_ui', 'f'
create 'hugegraph:g_si', 'f'
create 'hugegraph:g_oe', 'f'
create 'hugegraph:g_li', 'f'
create 'hugegraph:g_ii', 'f'
create 'hugegraph:g_ie', 'f'
create 'hugegraph:g_hi', 'f'
create 'hugegraph:g_fi', 'f'
create 'hugegraph:g_ei', 'f'
create 'hugegraph:g_di', 'f'
create 'hugegraph:g_ai', 'f'
create 'hugegraph:el', 'f'
create 'hugegraph:c', 'f'
`

报错：
[ERROR] com.baidu.hugegraph.dist.HugeGraphServer [] - HugeRestServer start error: 
com.baidu.hugegraph.backend.BackendException: The backend store of 'hugegraph' has not been initialized
        at com.baidu.hugegraph.core.GraphManager.checkBackendVersionOrExit(GraphManager.java:217) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:77) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:108) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357) ~[jersey-container-grizzly2-http-2.25.1.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:398) ~[grizzly-http-server-2.4.4.jar:2.4.4]
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:293) ~[grizzly-http-server-2.4.4.jar:2.4.4]
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:269) ~[grizzly-http-server-2.4.4.jar:2.4.4]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:64) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:133) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58) ~[hugegraph-dist-0.11.2.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:55) [hugegraph-dist-0.11.2.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:100) [hugegraph-dist-0.11.2.jar:?]

**Comment by daoerz** [comment]
多谢
@imbajin
