### ISSUE TITLE
HugeKeys.WRITE_TYPE

### ISSUE THREAD

**Issue by simling82** [hugegraph/hugegraph#1601]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

版本：hugegraph-0.11.2

https://github.com/hugegraph/hugegraph/releases/download/v0.11.2/hugegraph-0.11.2.tar.gz

### Expected & Actual behavior (期望与实际表现)

启动失败，日志如下：

2021-09-07 16:33:13 6711  [main] [ERROR] com.baidu.hugegraph.dist.HugeGraphServer [] - HugeRestServer start error:
java.lang.IllegalArgumentException: No enum constant com.baidu.hugegraph.type.define.HugeKeys.WRITE_TYPE
    at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_112]
    at com.baidu.hugegraph.type.define.HugeKeys.valueOf(HugeKeys.java:22) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
    at com.baidu.hugegraph.backend.store.mysql.MysqlTable.parseKey(MysqlTable.java:689) ~[hugegraph-mysql-0.11.2.jar:?]
    at com.baidu.hugegraph.backend.store.mysql.MysqlEntryIterator.row2Entry(MysqlEntryIterator.java:147) ~[hugegraph-mysql-0.11.2.jar:?]
    at com.baidu.hugegraph.backend.store.mysql.MysqlEntryIterator.fetch(MysqlEntryIterator.java:69) ~[hugegraph-mysql-0.11.2.jar:?]
    at com.baidu.hugegraph.backend.store.BackendEntryIterator.hasNext(BackendEntryIterator.java:59) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
    at com.baidu.hugegraph.iterator.ExtendableIterator.fetch(ExtendableIterator.java:86) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
    at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:40) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
    at com.baidu.hugegraph.backend.query.QueryResults.one(QueryResults.java:223) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
    at com.baidu.hugegraph.backend.query.QueryResults.one(QueryResults.java:87) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
    at com.baidu.hugegraph.backend.tx.SchemaTransaction.getSchema(SchemaTransaction.java:328) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
    at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getSchema(CachedSchemaTransaction.java:234) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
    at com.baidu.hugegraph.backend.tx.SchemaTransaction.getPropertyKey(SchemaTransaction.java:128) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
    at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.info(BackendStoreSystemInfo.java:72) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
    at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:92) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
    at com.baidu.hugegraph.core.GraphManager.checkBackendVersionOrExit(GraphManager.java:214) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
    at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:77) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
    at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:108) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
    at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180) ~[jersey-server-2.25.1.jar:?]
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357) ~[jersey-container-grizzly2-http-2.25.1.jar:?]
    at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:398) ~[grizzly-http-server-2.4.4.jar:2.4.4]
    at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:293) ~[grizzly-http-server-2.4.4.jar:2.4.4]
    at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:269) ~[grizzly-http-server-2.4.4.jar:2.4.4]
    at com.baidu.hugegraph.server.RestServer.start(RestServer.java:64) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
    at com.baidu.hugegraph.server.RestServer.start(RestServer.java:133) ~[hugegraph-api-0.11.2.jar:0.58.0.0]
    at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58) ~[hugegraph-dist-0.11.2.jar:?]
    at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:55) [hugegraph-dist-0.11.2.jar:?]
    at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:100) [hugegraph-dist-0.11.2.jar:?]

**Comment by imbajin** [comment]
bug 相关请给一下复现方式和具体的上下文, 例如如何出现, 何时出现, 是否稳定出现, 自己做了哪些尝试等

便于定位和解决, 多谢

**Comment by simling82** [comment]
> bug 相关请给一下复现方式和具体的上下文, 例如如何出现, 何时出现, 是否稳定出现, 自己做了哪些尝试等
> 
> 便于定位和解决, 多谢

我下载了这个版本：https://github.com/hugegraph/hugegraph/releases/download/v0.11.2/hugegraph-0.11.2.tar.gz
按官方步骤配置完启动就出这个错误，看异常是说HugeKeys.WRITE_TYPE枚举不存在：
java.lang.IllegalArgumentException: No enum constant com.baidu.hugegraph.type.define.HugeKeys.WRITE_TYPE

我拿jar包反编译发现HugeKeys.WRITE_TYPE的确不存在的，而最新master代码是有的，请看下图：
![image](https://user-images.githubusercontent.com/26052357/132438067-79b158f8-547a-48c0-aec4-2276953b5b67.png)

**Comment by imbajin** [comment]
多谢附图, 不过你有更简单快速的方式确认, github 快速文件搜索 `HugeKeys` 然后可以选择这个文件对应的不同分支的情况

显然 `0.11.x` 时就是没有 `WRITE_TYPE`的, [参考此](https://github.com/hugegraph/hugegraph/blob/v0.11.2-b3/hugegraph-core/src/main/java/com/baidu/hugegraph/type/define/HugeKeys.java)

你说的 master 有它已经是 `0.12.x` 的版本了, master 代表最新开发分支并不是发布分支, 如果你原本有存储环境是不能直接混用的. 你这应该是混用了0.11和0.12的环境, 分离开理清楚就可以解决了


另外请使用 `0.11.x-b3` 这是最新的发布版.
