### ISSUE TITLE
[Bug] 以mysql作为存储在初始化数据的时候一直提示 MySQL store only supports MysqlBackendEntry

### ISSUE THREAD

**Issue by lixiuying** [hugegraph/hugegraph#1616]
### Problem Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: mysql
- OS: Centos 7.x /mac

### Your Question (问题描述)

以mysql作为存储在初始化数据的时候一直提示以下错误信息：

2021-10-01 13:47:56 2562  [main] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to commit changes:
com.baidu.hugegraph.backend.BackendException: MySQL store only supports MysqlBackendEntry
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.castBackendEntry(MysqlStore.java:367) ~[hugegraph-mysql-0.11.2.jar:?]
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.mutate(MysqlStore.java:246) ~[hugegraph-mysql-0.11.2.jar:?]
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.mutate(MysqlStore.java:241) ~[hugegraph-mysql-0.11.2.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:306) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:223) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:358) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:325) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.addSchema(SchemaTransaction.java:289) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.addSchema(CachedSchemaTransaction.java:179) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.addPropertyKey(SchemaTransaction.java:115) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.init(BackendStoreSystemInfo.java:66) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.initSystemInfo(AbstractBackendStoreProvider.java:147) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.StandardHugeGraph.initBackend(StandardHugeGraph.java:268) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.cmd.InitStore.initBackend(InitStore.java:133) [hugegraph-dist-0.11.2.jar:?]
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:121) [hugegraph-dist-0.11.2.jar:?]
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:99) [hugegraph-dist-0.11.2.jar:?]
2021-10-01 13:47:56 2567  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Close graph standardhugegraph[hugegraph]
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to commit changes: MySQL store only supports MysqlBackendEntry(com.baidu.hugegraph.backend.BackendException: MySQL store only supports MysqlBackendEntry)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:374)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:325)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.addSchema(SchemaTransaction.java:289)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.addSchema(CachedSchemaTransaction.java:179)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.addPropertyKey(SchemaTransaction.java:115)
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.init(BackendStoreSystemInfo.java:66)
	at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.initSystemInfo(AbstractBackendStoreProvider.java:147)
	at com.baidu.hugegraph.StandardHugeGraph.initBackend(StandardHugeGraph.java:268)
	at com.baidu.hugegraph.cmd.InitStore.initBackend(InitStore.java:133)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:121)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:99)

**Comment by lixiuying** [comment]
已解决，需要设置成：
backend=mysql
serializer=mysql
原来serializer是设置为：binary

mysql配置：
# mysql backend config
jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:3306
jdbc.username=smart
jdbc.password=smart
jdbc.reconnect_max_times=3
jdbc.reconnect_interval=3
jdbc.sslmode=false
jdbc.storage_engine=InnoDB
