### ISSUE TITLE
[Bug] gremlin语句执行超时 将导致内存泄漏statement未释放

### ISSUE THREAD

**Issue by z7658329** [hugegraph/hugegraph#1639]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

Server Version: v0.11.x
Backend: mysql nodes, HDD or SSD
OS: 8 CPUs, 32 G RAM, Centos 7.x
Data Size: 50W vertices, 130W edges

### Expected & Actual behavior (期望与实际表现)

1.当一个gremlin语句执行超时后，监控程序记录到该查询并未释放statement
2.gremlin语句为count语句，监控程序记录到该查询并未释放statement
![1636463077(1)](https://user-images.githubusercontent.com/5474723/140929717-99ca99c0-15b2-44fb-99f4-6744ddf4234d.jpg)

监控monitor代码：
![image](https://user-images.githubusercontent.com/5474723/140929975-cfdbc195-c155-40f9-983f-44ce7ea3ad70.png)

![image](https://user-images.githubusercontent.com/5474723/140930112-51cb727e-8cee-4b6d-8ba5-ae779141a197.png)

Expected & Actual behavior (期望与实际表现)

gremlin语法无论执行成功与否都会释放连接

**Comment by z7658329** [comment]
org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.V("liujizheng6")]
java.util.concurrent.TimeoutException: Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.V("liujizheng6")]
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$1(GremlinExecutor.java:315) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-all-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) [netty-all-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-all-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.13.Final.jar:4.1.13.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by javeme** [comment]
@z7658329 Thanks for your analysis, it seems to have addressed the root cause.

ps: we can wrap log with code block (a pair of "```")
```
org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.V("liujizheng6")]
java.util.concurrent.TimeoutException: Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request [g.V("liujizheng6")]
```

**Comment by javeme** [comment]
related issue: #1626
