### ISSUE TITLE
[Question] docker虚拟机中huge使用hbase，init-store.sh连接zk卡死

### ISSUE THREAD

**Issue by jiaenqiu** [hugegraph/hugegraph#1679]
### Problem Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.2
- Backend: HBase 3 nodes, SSD 
- OS: 16 CPUs, 64 G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### 执行init-store.sh的日志信息
```java
Initializing HugeGraph Store...
+ /home/work/software/java/bin/java -cp /data02/home/hbase/hugegraph/hugegraph-0.11.2/lib/hugegraph-dist-0.11.2.jar -Djava.ext.dirs=/data02/home/hbase/hugegraph/hugegraph-0.11.2/lib:/data02/home/hbase/hugegraph/hugegraph-0.11.2/plugins com.baidu.hugegraph.cmd.InitStore /data02/home/hbase/hugegraph/hugegraph-0.11.2/conf/gremlin-server.yaml /data02/home/hbase/hugegraph/hugegraph-0.11.2/conf/rest-server.properties
2021-12-03 16:20:57 947   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2021-12-03 16:20:57 1202  [main] [WARN ] org.apache.hadoop.util.NativeCodeLoader [] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-12-03 16:20:57 1377  [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Connect 0x5adb0db3 to 【主机名】:2181 with session timeout=90000ms, retries 3, retry interval 1000ms, keepAlive=60000ms
2021-12-03 16:20:58 1782  [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Connect 0x4351c8c3 to 【主机名】:2181 with session timeout=90000ms, retries 3, retry interval 1000ms, keepAlive=60000ms
main dict load finished, time elapsed 801 ms
model load finished, time elapsed 59 ms.
2021-12-03 16:20:59 2684  [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Connect 0x7516e4e5 to 【主机名】:2181 with session timeout=90000ms, retries 3, retry interval 1000ms, keepAlive=60000ms
2021-12-03 16:28:03 427522 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=6, retries=16, started=424204 ms ago, cancelled=false, msg=Call to 【主机名】/0.0.0.0:60000 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call id=13, waitTime=60006, rpcTimeout=60000, details=, see https://s.apache.org/timeout
2021-12-03 16:29:07 491542 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=7, retries=16, started=488224 ms ago, cancelled=false, msg=Call to 【主机名】/0.0.0.0:60000 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call id=15, waitTime=60008, rpcTimeout=60000, details=, see https://s.apache.org/timeout
2021-12-03 16:30:17 561582 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=8, retries=16, started=558264 ms ago, cancelled=false, msg=Call to 【主机名】/0.0.0.0:60000 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call id=17, waitTime=60003, rpcTimeout=60000, details=, see https://s.apache.org/timeout
```
### ctrl+c后的日志信息
```java
^C^C^2021-12-03 16:31:48 652379 [Thread-1] [INFO ] com.baidu.hugegraph.HugeGraph [] - HugeGraph is shutting down
2021-12-03 16:32:18 682381 [Thread-1] [ERROR] com.baidu.hugegraph.HugeGraph [] - Error while shutdown
com.baidu.hugegraph.HugeException: Failed to wait for TaskScheduler
        at com.baidu.hugegraph.task.TaskManager.shutdown(TaskManager.java:220) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
        at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:130) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
        at com.baidu.hugegraph.HugeFactory.lambda$static$0(HugeFactory.java:52) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.util.concurrent.TimeoutException: 30s
        at com.baidu.hugegraph.task.TaskManager.shutdown(TaskManager.java:217) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
        ... 3 more
Exception in thread "Thread-1" com.baidu.hugegraph.HugeException: Failed to shutdown
        at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:134)
        at com.baidu.hugegraph.HugeFactory.lambda$static$0(HugeFactory.java:52)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.baidu.hugegraph.HugeException: Failed to wait for TaskScheduler
        at com.baidu.hugegraph.task.TaskManager.shutdown(TaskManager.java:220)
        at com.baidu.hugegraph.HugeFactory.shutdown(HugeFactory.java:130)
        ... 2 more
Caused by: java.util.concurrent.TimeoutException: 30s
        at com.baidu.hugegraph.task.TaskManager.shutdown(TaskManager.java:217)
        ... 3 more
+ echo 'Initialization finished.'
Initialization finished.
```

### 我的配置 
```
hbase.hosts=【zk master的hostname/ip/0.0.0.0/一个ip/多个ip等都尝试了】
hbase.port=2181
hbase.znode_parent=/hbase
hbase.threads_max=64
```

**Comment by imbajin** [comment]
可以先确认一下网络是否连通, docker 可以正常访问到对应的端口么?

或者排除法, 先在你 docker 对应的物理机上使用 huge, 看看链接是否成功, 先确认物理机正常, 再缩小到容器和它的配置

**Comment by jiaenqiu** [comment]
![image](https://user-images.githubusercontent.com/26378685/144574496-6045bd65-ae22-4df5-8112-d1f411c0c062.png)

**Comment by jiaenqiu** [comment]
> 可以先确认一下网络是否连通, docker 可以正常访问到对应的端口么?
> 
> 或者排除法, 先在你 docker 对应的物理机上使用 huge, 看看链接是否成功, 先确认物理机正常, 再缩小到容器和它的配置
> 
> PS: 另外报错日志可以用代码块框起来, 方便查看不少

![image](https://user-images.githubusercontent.com/26378685/144574563-846a946a-e177-4c7e-a165-9856570642cf.png)

**Comment by imbajin** [comment]
帮你脱敏更新了下, 我的意思是, 你可以先直接在物理机上起一个 huge server, 看看它能不能初始化 (连接你的 ZK)

确认这个之后, 再看看容器内的问题. 先不在容器内测试. (另外你用的容器是自己构建的镜像么?)

**Comment by jiaenqiu** [comment]
> 帮你脱敏更新了下, 我的意思是, 你可以先直接在物理机上起一个 huge server, 看看它能不能初始化 (连接你的 ZK)
> 
> 确认这个之后, 再看看容器内的问题. 先不在容器内测试. (另外你用的容器是自己构建的镜像么?)

我本地测试zk可以正常连接，且可操作，说明zk服务OK；huge在虚拟机部署后，还是连不上zk

**Comment by imbajin** [comment]
如果本地/宿主机(物理机)通过 huge server 连接 zk 出成功, 说明 hugeserver 和 zk 都是基本正常的

那不管是虚拟机还是容器, 因为**网络**和一些其他资源的隔离限制, 大概率问题是出在这里, 你可以在这样排除

在虚拟机或容器内, 起一个 zkClient, 然后用它去连接你外面的 zk, 如果它也不能连上, 那就说明和图是没有关系的, 就需要自己排查一下相关网络问题了

**Comment by jiaenqiu** [comment]
> 如果本地/宿主机(物理机)通过 huge server 连接 zk 出成功, 说明 hugeserver 和 zk 都是基本正常的
> 
> 那不管是虚拟机还是容器, 因为**网络**和一些其他资源的隔离限制, 大概率问题是出在这里, 你可以在这样排除
> 
> 在虚拟机或容器内, 起一个 zkClient, 然后用它去连接你外面的 zk, 如果它也不能连上, 那就说明和图是没有关系的, 就需要自己排查一下相关网络问题了
