### ISSUE TITLE
[Question] How to config multiple graphs correctly (server-1 already in cluster)

### ISSUE THREAD

**Issue by KirubakaranSP** [hugegraph/hugegraph#1707]
### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

Is there any way to create multiple graphs with same backend database?I've tried creating 5 graphs with rockdb as backend database but it results in following error.
Error : 

java.lang.IllegalArgumentException: The server with name 'server-1' already in cluster
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:163) ~[guava-25.1-jre.jar:?]
        at com.baidu.hugegraph.util.E.checkArgument(E.java:56) ~[hugegraph-common-1.8.8.jar:1.8.8.0]
        at com.baidu.hugegraph.task.ServerInfoManager.initServerInfo(ServerInfoManager.java:142) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.StandardHugeGraph.serverStarted(StandardHugeGraph.java:259) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.core.GraphManager.serverStarted(GraphManager.java:300) ~[hugegraph-api-0.12.0.jar:0.66.0.0]
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:87) ~[hugegraph-api-0.12.0.jar:0.66.0.0]
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:110) ~[hugegraph-api-0.12.0.jar:0.66.0.0]
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357) ~[jersey-container-grizzly2-http-2.25.1.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:398) ~[grizzly-http-server-2.4.4.jar:2.4.4]
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:293) ~[grizzly-http-server-2.4.4.jar:2.4.4]
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:269) ~[grizzly-http-server-2.4.4.jar:2.4.4]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:67) ~[hugegraph-api-0.12.0.jar:0.66.0.0]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:173) ~[hugegraph-api-0.12.0.jar:0.66.0.0]
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58) ~[hugegraph-dist-0.12.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.<init>(HugeGraphServer.java:55) ~[hugegraph-dist-0.12.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:100) ~[hugegraph-dist-0.12.0.jar:?]
2021-12-23 15:13:23 [gremlin-server-stop] [INFO] c.b.h.HugeGraph - Close graph standardhugegraph[hugegraph]
2021-12-23 15:13:23 [gremlin-server-stop] [INFO] c.b.h.t.ServerInfoManager - Remove server info: server-1
2021-12-23 15:13:23 [gremlin-server-stop] [WARN] o.a.t.g.s.GremlinServer - Exception while closing Graph instance [hugegraph]
java.lang.IllegalStateException: Ensure tx closed in all threads when closing graph 'hugegraph'
        at com.google.common.base.Preconditions.checkState(Preconditions.java:531) ~[guava-25.1-jre.jar:?]
        at com.baidu.hugegraph.util.E.checkState(E.java:68) ~[hugegraph-common-1.8.8.jar:1.8.8.0]
        at com.baidu.hugegraph.StandardHugeGraph.close(StandardHugeGraph.java:902) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$null$7(GremlinServer.java:298) ~[gremlin-server-3.4.3.jar:3.4.3]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_152]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$stop$8(GremlinServer.java:295) ~[gremlin-server-3.4.3.jar:3.4.3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

**Comment by imbajin** [comment]
maybe refer the current issues first (like #1462 )
![image](https://user-images.githubusercontent.com/17706099/147223422-423d5b39-4015-4763-83dd-f123fbc7488a.png)

first, make sure your multi graph configs is right, u need to change 3 files (at least): 
- gremlin-server.yaml
- hugegraph1-x.properties (modify graph name to keep them not same)
- rest-server.properties

try modify the value in `rest-server.properties`  => `server.id=server-1`  ==> `server.id=serverXX` and see what happens

Then please paste your  `hugegraphX.properties` and `rest-server.properties` and `graphs` in gremlin-server.yaml  like #1462 to help us find the problem quickly.

BTW, due to the lack of English documents, I don't know if there is a big barrier for EN users using HugeGraph? Hopefully get some feedback about it, including improvements and priorities

**Comment by KirubakaranSP** [comment]
**gremlin-server.yaml**
```
graphs: {
  hugegraph: conf/hugegraph.properties,
  hugegraph1: conf/hugegraph1.properties,
  hugegraph2: conf/hugegraph2.properties,
  hugegraph3: conf/hugegraph3.properties,
  hugegraph4: conf/hugegraph4.properties
}
```

**rest-server.properties** : 

`# bind url
restserver.url=http://127.0.0.1:8080
# gremlin server url, need to be consistent with host and port in gremlin-server.yaml
#gremlinserver.url=http://127.0.0.1:8182

# graphs list with pair NAME:CONF_PATH
graphs=[hugegraph:conf/hugegraph.properties,hugegraph1:conf/hugegraph1.properties,hugegraph2:conf/hugegraph2.properties,hugegraph3:conf/hugegraph3.properties,hugegraph4:conf/hugegraph4.properties]

# The maximum thread ratio for batch writing, only take effect if the batch.max_write_threads is 0
batch.max_write_ratio=90
batch.max_write_threads=100
batch.max_vertices_per_batch=20000
batch.max_edges_per_batch=20000

oltp.concurrent_threads=20
oltp.concurrent_depth=20

exception.allow_trace=true

restserver.request_timeout=-1
restserver.connection_idle_timeout=-1

gremlinserver.timeout=1000000

#vertex.tx_capacity=100000000
#edge.tx_capacity=100000000
schema.cache_capacity=1000000

# authentication configs
# choose 'com.baidu.hugegraph.auth.StandardAuthenticator' or 'com.baidu.hugegraph.auth.ConfigAuthenticator'
#auth.authenticator=

# for StandardAuthenticator mode
#auth.graph_store=hugegraph
# auth client config
#auth.remote_url=127.0.0.1:8899,127.0.0.1:8898,127.0.0.1:8897

# for ConfigAuthenticator mode
#auth.admin_token=
#auth.user_tokens=[]

# rpc group configs of multi graph servers
# rpc server configs
rpc.server_host=127.0.0.1
rpc.server_port=8090
#rpc.server_timeout=30

# rpc client configs (like enable to keep cache consistency)
rpc.remote_url=127.0.0.1:8090
#rpc.client_connect_timeout=20
#rpc.client_reconnect_period=10
#rpc.client_read_timeout=40
#rpc.client_retries=3
#rpc.client_load_balancer=consistentHash

# lightweight load balancing (beta)
server.id=server-1
server.role=master
`

hugegraph.properties
`# gremlin entrance to create graph
# auth config: com.baidu.hugegraph.auth.HugeFactoryAuthProxy
gremlin.graph=com.baidu.hugegraph.HugeFactory

# cache config
#schema.cache_capacity=100000
# vertex-cache default is 1000w, 10min expired
vertex.cache_type=l2
vertex.cache_capacity=1
#vertex.cache_expire=600
# edge-cache default is 100w, 10min expired
edge.cache_type=l2
edge.cache_capacity=1
#edge.cache_expire=600


# schema illegal name template
#schema.illegal_name_regex=\s+|~.*

#vertex.default_label=vertex
vertex.check_customized_id_exist=true
task.wait_timeout=600000

backend=rocksdb
serializer=binary

store=hugegraph

raft.mode=false
raft.safe_read=false
raft.use_snapshot=false
raft.endpoint=127.0.0.1:8281
raft.group_peers=127.0.0.1:8281,127.0.0.1:8282,127.0.0.1:8283
raft.path=./raft-log
raft.use_replicator_pipeline=true
raft.election_timeout=10000
raft.snapshot_interval=3600
raft.backend_threads=48
raft.read_index_threads=8
raft.read_strategy=ReadOnlyLeaseBased
raft.queue_size=16384
raft.queue_publish_timeout=60
raft.apply_batch=1
raft.rpc_threads=80
raft.rpc_connect_timeout=500000
raft.rpc_timeout=60000

search.text_analyzer=jieba
search.text_analyzer_mode=SEARCH

# rocksdb backend config
#rocksdb.data_path=/path/to/disk
#rocksdb.wal_path=/path/to/disk


# cassandra backend config
cassandra.host=localhost
cassandra.port=9042
cassandra.username=
cassandra.password=
#cassandra.connect_timeout=5
#cassandra.read_timeout=20
#cassandra.keyspace.strategy=SimpleStrategy
#cassandra.keyspace.replication=3

# hbase backend config
#hbase.hosts=localhost
#hbase.port=2181
#hbase.znode_parent=/hbase
#hbase.threads_max=64

# mysql backend config
#jdbc.driver=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://127.0.0.1:3306
#jdbc.username=root
#jdbc.password=
#jdbc.reconnect_max_times=3
#jdbc.reconnect_interval=3
#jdbc.sslmode=false

# postgresql & cockroachdb backend config
#jdbc.driver=org.postgresql.Driver
#jdbc.url=jdbc:postgresql://localhost:5432/
#jdbc.username=postgres
#jdbc.password=
#jdbc.postgresql.connect_database=template1

# palo backend config
#palo.host=127.0.0.1
#palo.poll_interval=10
#palo.temp_dir=./palo-data
#palo.file_limit_size=32
`
I have other hugegraph properties with file name hugegraph1.properties,hugegraph2.properties,hugegraph3.properties,hugegraph4.properties with the same configurations except the value for **store** 

I followed the steps menntioned in this document.Now am getting new error
`2021-12-23 18:19:38 [db-open-1] [ERROR] c.b.h.b.s.r.RocksDBStore - Failed to open RocksDB with default CF, is there data for other programs: rocksdb-data/m
Exception in thread "main" com.baidu.hugegraph.HugeException: Failed to open schema transaction
	at com.baidu.hugegraph.StandardHugeGraph.openSchemaTransaction(StandardHugeGraph.java:415)
	at com.baidu.hugegraph.StandardHugeGraph.access$19(StandardHugeGraph.java:408)
	at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.getOrNewTransaction(StandardHugeGraph.java:1346)
	at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.schemaTransaction(StandardHugeGraph.java:1322)
	at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.access$0(StandardHugeGraph.java:1321)
	at com.baidu.hugegraph.StandardHugeGraph.schemaTransaction(StandardHugeGraph.java:468)
	at com.baidu.hugegraph.StandardHugeGraph.backendStoreSystemInfo(StandardHugeGraph.java:247)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:114)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:99)
2021-12-23 18:19:38 [db-open-1] [ERROR] c.b.h.b.s.r.RocksDBStore - Failed to open RocksDB 'rocksdb-data/m'
org.rocksdb.RocksDBException: You have to open all column families. Column families not opened: hugegraph+c, hugegraph+si, hugegraph+pk, hugegraph+vl, hugegraph+il, hugegraph+el
	at org.rocksdb.RocksDB.open(Native Method) ~[rocksdbjni-6.10.2.jar:?]
	at org.rocksdb.RocksDB.open(RocksDB.java:239) ~[rocksdbjni-6.10.2.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.openRocksDB(RocksDBStdSessions.java:398) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:95) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:375) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:341) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:298) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.lambda$5(RocksDBStore.java:229) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
2021-12-23 18:19:38 [main] [ERROR] c.b.h.HugeGraph - Failed to open schema transaction
com.baidu.hugegraph.backend.BackendException: Failed to open RocksDB store
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.waitOpenFinish(RocksDBStore.java:258) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:249) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:82) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:75) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:54) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph.openSchemaTransaction(StandardHugeGraph.java:411) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph.access$19(StandardHugeGraph.java:408) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.getOrNewTransaction(StandardHugeGraph.java:1346) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.schemaTransaction(StandardHugeGraph.java:1322) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph$TinkerPopTransaction.access$0(StandardHugeGraph.java:1321) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph.schemaTransaction(StandardHugeGraph.java:468) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.StandardHugeGraph.backendStoreSystemInfo(StandardHugeGraph.java:247) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:114) ~[hugegraph-dist-0.12.0.jar:?]
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:99) ~[hugegraph-dist-0.12.0.jar:?]
Caused by: java.util.concurrent.ExecutionException: com.baidu.hugegraph.exception.ConnectionException: Failed to open RocksDB 'rocksdb-data/m'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.waitOpenFinish(RocksDBStore.java:256) ~[hugegraph-rocksdb-0.12.0.jar:?]
	... 14 more
Caused by: com.baidu.hugegraph.exception.ConnectionException: Failed to open RocksDB 'rocksdb-data/m'
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:355) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:298) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.lambda$5(RocksDBStore.java:229) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: org.rocksdb.RocksDBException: You have to open all column families. Column families not opened: hugegraph+c, hugegraph+si, hugegraph+pk, hugegraph+vl, hugegraph+il, hugegraph+el
	at org.rocksdb.RocksDB.open(Native Method) ~[rocksdbjni-6.10.2.jar:?]
	at org.rocksdb.RocksDB.open(RocksDB.java:239) ~[rocksdbjni-6.10.2.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.openRocksDB(RocksDBStdSessions.java:398) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:95) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:375) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:341) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:298) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.lambda$5(RocksDBStore.java:229) ~[hugegraph-rocksdb-0.12.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_152]`


And regd the language barrier.Luckily google transaction helps to translate the document ,but not for images mentioned inn the document.

**Comment by imbajin** [comment]
seems configuration are right, could u try to delete the `rocksdb-data` directory, and re-init all graph again? 


And we will push HugeGraph to Apache Foundation soon, expect more users to migrate from **JanusGraph** ,  we will use english for images in future to avoid language problem

**Comment by KirubakaranSP** [comment]
yes already tried deleting rocksdb and re-init the graph.
`Caused by: org.rocksdb.RocksDBException: You have to open all column families. Column families not opened: hugegraph+c, hugegraph+si, hugegraph+pk, hugegraph+vl, hugegraph+il, hugegraph+el
`
Why the above exception occurs?

**Comment by KirubakaranSP** [comment]
Any update on this?

**Comment by imbajin** [comment]
> yes already tried deleting rocksdb and re-init the graph. `Caused by: org.rocksdb.RocksDBException: You have to open all column families. Column families not opened: hugegraph+c, hugegraph+si, hugegraph+pk, hugegraph+vl, hugegraph+il, hugegraph+el ` Why the above exception occurs?

try 2 ways:
1. delete `rocksdb-data`, then init all graph **together** (don't init new graph after some graph has been inited)
2. if 1 failed, try to modify the rocksdb-data path to make them different
   ```properties
  # rocksdb backend config
  rocksdb.data_path=/path/to/disk1-5
  rocksdb.wal_path=/path/to/disk1-5
   ```

**Comment by KirubakaranSP** [comment]
Is there any way to know which graph is running when multiple graphs are configured ?

**Comment by imbajin** [comment]
> Is there any way to know which graph is running when multiple graphs are configured ?

you can refer `ip:8080/graphs` api (refer doc) to know them, include backend & config info

**Comment by hdong888** [comment]
The issue still exists, both in 0.11.2 and 0.12.0. I need two graph instances with rocksdb as backend. Init-store is fine if the two graphs use one rocksdb store OR same store name but two different rocksdb paths. But start-hugegraph fails with:
java.lang.IllegalArgumentException: The server with name 'server-1' already in cluster

The problem is gone if the two graphs use different backends, for example, one with rocksdb, one with memory.

BTW, I want to use one hugegraph server (no load balance ) with two graph instances, both with rocksdb backend.

Would this be fixed soon?
