### ISSUE TITLE
[Bug] reft协议部署下，配置的边类型无法删除

### ISSUE THREAD

**Issue by fcser** [hugegraph/hugegraph#1739]
### Bug Type (问题类型)

gremlin (结果不合预期)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: RocksDB 
- OS: 8 CPUs, 30 G RAM, Centos 7.x 
- Data Size:   100w vertices,  500w edges 

3个节点，配置了raft协议
raft.mode=true
raft.safe_read=true
raft.use_snapshot=true
raft.endpoint=10.*.*.27:8281
raft.group_peers=10.*.*.27:8281,10.*.*.235:8281,10.*.*.40:8281

### Expected & Actual behavior (期望与实际表现)

![image](https://user-images.githubusercontent.com/33123034/150756478-5a036637-e70b-45d6-bc52-eae03cc2aaa3.png)
com.baidu.hugegraph.HugeException: Failed to remove edges

**Comment by imbajin** [comment]
删除 500w 条边是么? 你可以看看后端 server 的日志里有什么相关信息么

**Comment by javeme** [comment]
@fcser 感谢反馈，可以提供一下复现流程吗？

**Comment by fcser** [comment]
> 删除 500w 条边是么? 你可以看看后端 server 的日志里有什么相关信息么

2022-01-26 16:12:44 [task-worker-2] [WARN] c.b.h.b.s.r.RaftBackendStore - Failed to execute query '`Query * from EDGE page 'HosxOjBEWW9zb0JTZ3CCCAEAizE6QXc2eW5COHQzQwAAAAAAAAH0', limit 500`': Status[ETIMEDOUT<1010>: read-index request timeout]
com.baidu.hugegraph.backend.BackendException: Failed to do raft read-index: Status[ETIMEDOUT<1010>: read-index request timeout]
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore$1.run(RaftBackendStore.java:225) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.alipay.sofa.jraft.closure.ReadIndexClosure$TimeoutTask.run(ReadIndexClosure.java:153) ~[jraft-core-1.3.9.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:609) ~[jraft-core-1.3.9.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:677) ~[jraft-core-1.3.9.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:395) ~[jraft-core-1.3.9.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
2022-01-26 16:12:44 [task-worker-2] [ERROR] c.b.h.b.Transaction - Failed to remove edges
com.baidu.hugegraph.backend.BackendException: Failed to execute query: `Query * from EDGE page 'HosxOjBEWW9zb0JTZ3CCCAEAizE6QXc2eW5COHQzQwAAAAAAAAH0', limit 500`
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore.queryByRaft(RaftBackendStore.java:237) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore.queryByRaft(RaftBackendStore.java:209) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore.query(RaftBackendStore.java:143) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.query(AbstractTransaction.java:163) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.query(GraphTransaction.java:533) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.queryEdgesFromBackend(GraphTransaction.java:981) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.queryEdgesFromBackend(CachedGraphTransaction.java:279) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.queryEdges(GraphTransaction.java:944) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.traverseByLabel(GraphTransaction.java:2037) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.traverseEdgesByLabel(GraphTransaction.java:1990) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.removeEdges(GraphTransaction.java:1968) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.job.schema.EdgeLabelRemoveJob.removeEdgeLabel(EdgeLabelRemoveJob.java:71) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.job.schema.EdgeLabelRemoveJob.execute(EdgeLabelRemoveJob.java:42) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.job.SysJob.call(SysJob.java:29) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
        at com.baidu.hugegraph.task.HugeTask.run(HugeTask.java:287) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to do raft read-index: Status[ETIMEDOUT<1010>: read-index request timeout]
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore$1.run(RaftBackendStore.java:225) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.alipay.sofa.jraft.closure.ReadIndexClosure$TimeoutTask.run(ReadIndexClosure.java:153) ~[jraft-core-1.3.9.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:609) ~[jraft-core-1.3.9.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:677) ~[jraft-core-1.3.9.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:395) ~[jraft-core-1.3.9.jar:?]
        ... 1 more
2022-01-26 16:12:44 [task-worker-2] [WARN] c.b.h.t.HugeTask - An exception occurred when running task: 2
com.baidu.hugegraph.HugeException: Failed to remove edges
        at com.baidu.hugegraph.backend.tx.GraphTransaction.removeEdges(GraphTransaction.java:1976) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.job.schema.EdgeLabelRemoveJob.removeEdgeLabel(EdgeLabelRemoveJob.java:71) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.job.schema.EdgeLabelRemoveJob.execute(EdgeLabelRemoveJob.java:42) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.job.SysJob.call(SysJob.java:29) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
        at com.baidu.hugegraph.task.HugeTask.run(HugeTask.java:287) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to execute query: `Query * from EDGE page 'HosxOjBEWW9zb0JTZ3CCCAEAizE6QXc2eW5COHQzQwAAAAAAAAH0', limit 500`
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore.queryByRaft(RaftBackendStore.java:237) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore.queryByRaft(RaftBackendStore.java:209) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore.query(RaftBackendStore.java:143) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.query(AbstractTransaction.java:163) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.query(GraphTransaction.java:533) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.queryEdgesFromBackend(GraphTransaction.java:981) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.queryEdgesFromBackend(CachedGraphTransaction.java:279) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.queryEdges(GraphTransaction.java:944) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.traverseByLabel(GraphTransaction.java:2037) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.traverseEdgesByLabel(GraphTransaction.java:1990) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.removeEdges(GraphTransaction.java:1968) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        ... 10 more
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to do raft read-index: Status[ETIMEDOUT<1010>: read-index request timeout]
        at com.baidu.hugegraph.backend.store.raft.RaftBackendStore$1.run(RaftBackendStore.java:225) ~[hugegraph-core-0.12.0.jar:0.12.0.0]
        at com.alipay.sofa.jraft.closure.ReadIndexClosure$TimeoutTask.run(ReadIndexClosure.java:153) ~[jraft-core-1.3.9.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:609) ~[jraft-core-1.3.9.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:677) ~[jraft-core-1.3.9.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:395) ~[jraft-core-1.3.9.jar:?]
        ... 1 more
2022-01-26 16:12:44 [JRaft-FSMCaller-Disruptor-0] [WARN] c.a.s.j.c.ReadIndexClosure - A timeout read-index response finally returned: Status[OK].
2022-01-26 16:21:52 [task-

**Comment by javeme** [comment]
@fcser 贡献反馈，其它raft节点的日志是否也可以提供一下？

**Comment by isliudong** [comment]
同款异常，但是我是停止后无法启动
