### ISSUE TITLE
[Bug] RESTEASY003145: Unable to find a MessageBodyReader - Client无法初始化

### ISSUE THREAD

**Issue by BestBurning** [hugegraph/hugegraph#1764]
### Bug Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.x
- Backend: MySQL 1 nodes, HDD 

- Client Version：2.0.1

### 期望

Client正常初始化，并可以进行调用

### 实际

Client初始化异常

- 初始化代码

```java
    @Bean
    public HugeClient hugeClient(){
        HugeClient hugeClient = HugeClient.builder(url, graph)
            .build();
        return hugeClient;
    }
```

- 报错

```java
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.baidu.hugegraph.driver.HugeClient]: Factory method 'hugeClient' threw exception; nested exception is javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type application/json;charset=UTF-8 and type class java.lang.String
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:652) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	... 33 common frames omitted
Caused by: javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type application/json;charset=UTF-8 and type class java.lang.String
	at org.jboss.resteasy.core.interception.ClientReaderInterceptorContext.throwReaderNotFound(ClientReaderInterceptorContext.java:42) ~[resteasy-jaxrs-3.0.19.Final.jar:3.0.19.Final]
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.getReader(AbstractReaderInterceptorContext.java:75) ~[resteasy-jaxrs-3.0.19.Final.jar:3.0.19.Final]
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:52) ~[resteasy-jaxrs-3.0.19.Final.jar:3.0.19.Final]
	at org.glassfish.jersey.spi.ContentEncoder.aroundReadFrom(ContentEncoder.java:127) ~[jersey-common-2.22.jar:na]
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:55) ~[resteasy-jaxrs-3.0.19.Final.jar:3.0.19.Final]
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:251) ~[resteasy-client-3.0.19.Final.jar:3.0.19.Final]
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:181) ~[resteasy-client-3.0.19.Final.jar:3.0.19.Final]
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:219) ~[resteasy-jaxrs-3.0.19.Final.jar:3.0.19.Final]
	at com.baidu.hugegraph.rest.RestResult.<init>(RestResult.java:45) ~[hugegraph-common-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.rest.AbstractRestClient.get(AbstractRestClient.java:305) ~[hugegraph-common-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.rest.AbstractRestClient.get(AbstractRestClient.java:270) ~[hugegraph-common-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:111) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:95) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:67) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
	at com.baidu.hugegraph.driver.HugeClientBuilder.build(HugeClientBuilder.java:67) ~[hugegraph-client-2.0.1.jar:2.0.1.0]
```

###  部分发现

程序中存在`resteasy-client`包时可复现此问题
```xml
<dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <version>3.0.19.Final</version>
        </dependency>
```

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
不涉及
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
不涉及
```

**Comment by imbajin** [comment]
多谢反馈, 看起来像是包冲突导致的, 如果是单独(bare)的项目使用应该没有这个问题吧?

如果必须引入 jboss 的包, 尝试排除一下引起报错的相关部分看看? (或者用一个 mvn 插件分析一下 client 和 jboss 中相同的包依赖, 排除另一个)

**Comment by BestBurning** [comment]
单独项目没有此问题，排除后可正常初始化
