### ISSUE TITLE
[Question]  Shortest Path API(查两点间最短路径)可否添加filter过滤某些点的最短路径

### ISSUE THREAD

**Issue by OrchidByLiu** [hugegraph/hugegraph#1769]
### Problem Type (问题类型)

performence (性能优化)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

traverser API中Shortest Path API(查找两个顶点之间的最短路径)可否添加filter过滤某些点的最短路径

**Comment by imbajin** [comment]
可以,  而且例如 kout/kneighbor API 已经有支持 filter 边属性了(点是一样的).  (详见 [TraverserUtil](https://github.com/hugegraph/hugegraph/blob/master/hugegraph-core/src/main/java/com/baidu/hugegraph/traversal/optimize/TraversalUtil.java) 类)

目前可以支持以下: (应该能满足常见需要)
1.  `P.eq()` 代表过滤出数值相等的元素
2.  `P.neq()` 代表过滤出数值不相等的元素
3.  `P.lt()` 代表过滤出数值小于 (<) 某数的元素
4.  `P.lte()` 代表过滤出数值小于相等 (≤) 某数的元素
5.  `P.gt()` 代表过滤出数值大于 (>) 某数的元素
6.  `P.gte()` 代表过滤出数值大于相等 (≥) 的元素
7.  `P.between(a, b)` 代表过滤出数值在 `(a, b)` 范围内的元素
8.  `P.inside(a, b)` 代表过滤出数值在 `> a` 且 `< b` 范围内的元素
9.  `P.outside(a, b)` 代表过滤出数值在 `< a` 且 `> b` 范围内的元素
10.  `P.textcontains(str)` 代表过滤出包含 str **子串**的元素
11.  `P.contains(str)` 代表从集合中过滤出包含 str 字符串的元素
12.  `P.within(a, b, c)` 代表过滤出包含**给定集合**中任一子元素的元素


你可以参考相关代码给最短路径也**加一个参数**, 比如新增一个 `List<XxFilter> filters`,  欢迎提交相关 PR~

**Comment by OrchidByLiu** [comment]
customizedKneighbor
通过KneighborRecords records = new KneighborRecords(concurrent,source, true);这个方法找到了所有记录
这个方法在做过滤
 Iterator<Edge> edges = edgesOfVertex(v, step);

这个方法fillConditionQuery(ConditionQuery query, Map<Id, Object> properties,HugeGraph graph)
把properties的值传给ConditionQuery添加了查询条件，查询符合过滤条件的边

最后在返回结果
以上我理解的是否正确！

**Comment by OrchidByLiu** [comment]
在ShortestPathTraverser中shortestPath->method是查询后，返回了第一条
我在返回前做一层过滤List<XxFilter> filters
在返回

**Comment by OrchidByLiu** [comment]
我现在用的版本是0.11.2，我在github下载了11.2-b4的代码，修改API后
2022-03-03 16:33:54 58488 [grizzly-http-server-3] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to parse entry: 0x82415033: [�AP3��AP7=j
2021-11-10, �AP3��LM149=�
2021-11-10]
java.lang.IllegalArgumentException: Undefined property key with id: '106'
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:163) ~[guava-25.1-jre.jar:?]
	at com.baidu.hugegraph.util.E.checkArgument(E.java:56) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
	at com.baidu.hugegraph.StandardHugeGraph.propertyKey(StandardHugeGraph.java:638) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.parseProperty(BinarySerializer.java:179) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.parseProperties(BinarySerializer.java:214) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.parseEdge(BinarySerializer.java:277) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.parseColumn(BinarySerializer.java:315) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.readVertex(BinarySerializer.java:425) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.parseEntry(GraphTransaction.java:1815) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.lambda$queryEdgesFromBackend$7(GraphTransaction.java:945) ~[hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.iterator.FlatMapperIterator.fetch(FlatMapperIterator.java:62) [hugegraph-common-1.8.1.jar:1.8.1.0]
	at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:40) [hugegraph-common-1.8.1.jar:1.8.1.0]
	at com.baidu.hugegraph.iterator.FilterIterator.fetch(FilterIterator.java:42) [hugegraph-common-1.8.1.jar:1.8.1.0]
	at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:40) [hugegraph-common-1.8.1.jar:1.8.1.0]
	at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.queryEdgesFromBackend(CachedGraphTransaction.java:271) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.queryEdges(GraphTransaction.java:903) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.StandardHugeGraph.edges(StandardHugeGraph.java:601) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.traversal.algorithm.HugeTraverser.edgesOfVertex(HugeTraverser.java:183) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.traversal.algorithm.HugeTraverser.edgesOfVertex(HugeTraverser.java:189) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.traversal.algorithm.ShortestPathTraverser$Traverser.forward(ShortestPathTraverser.java:239) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.traversal.algorithm.ShortestPathTraverser.shortestPath(ShortestPathTraverser.java:124) [hugegraph-core-0.11.2.jar:0.11.2.0]
	at com.baidu.hugegraph.api.traversers.ShortestPathAPI.get(ShortestPathAPI.java:91) [hugegraph-api-0.11.2.jar:0.58.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.1.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [grizzly-http-server-2.4.4.jar:2.4.4]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [grizzly-framework-2.4.4.jar:2.4.4]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [grizzly-framework-2.4.4.jar:2.4.4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]

**Comment by javeme** [comment]
想确认下：

- 使用原有的代码是否正常运行？
- 使用v0.11.2-b4不修改代码能执行吗？
