### ISSUE TITLE
[Question] hugegraph兼容hbase1.4.8版本问题

### ISSUE THREAD

**Issue by wuchaojing** [hugegraph/hugegraph#1771]
### Problem Type (问题类型)

other exception / error (其他异常报错)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Backend: hbase 1.4.8

### Your Question (问题描述)

根据https://github.com/hugegraph/hugegraph/issues/957做如下适配
1. 修改hugegraph-hbase模块的pom文件，增加
`
<dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-shaded-client</artifactId>
            <version>1.4.8</version>
</dependency>
`

2. 修改源代码，适配API，暂时注释无关的不兼容代码

3. 修改hugegraph.properties，使用hbase后端

执行bin/init-store.sh，报错如下：
`
Initializing HugeGraph Store...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/didi/Documents/dev/octo-graph/hugegraph-0.12.0/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/didi/Documents/dev/octo-graph/hugegraph-0.12.0/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (com.baidu.hugegraph.config.OptionSpace).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
main dict load finished, time elapsed 634 ms
model load finished, time elapsed 32 ms.
Exception in thread "main" java.lang.IllegalArgumentException
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getThreadPool(ConnectionManager.java:856)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getBatchPool(ConnectionManager.java:830)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getTable(ConnectionManager.java:760)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getTable(ConnectionManager.java:558)
        at org.apache.hadoop.hbase.MetaTableAccessor.getMetaHTable(MetaTableAccessor.java:198)
        at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:633)
        at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:365)
        at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:417)
        at com.baidu.hugegraph.backend.store.hbase.HbaseSessions.existsTable(HbaseSessions.java:202)
        at com.baidu.hugegraph.backend.store.hbase.HbaseStore.initialized(HbaseStore.java:326)
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.storeInitialized(AbstractTransaction.java:105)
        at com.baidu.hugegraph.StandardHugeGraph$StandardHugeGraphParams.initialized(StandardHugeGraph.java:1158)
        at com.baidu.hugegraph.task.ServerInfoManager.removeSelfServerInfo(ServerInfoManager.java:337)
        at com.baidu.hugegraph.task.ServerInfoManager.close(ServerInfoManager.java:121)
        at com.baidu.hugegraph.task.StandardTaskScheduler.close(StandardTaskScheduler.java:495)
        at com.baidu.hugegraph.task.TaskManager.closeScheduler(TaskManager.java:112)
        at com.baidu.hugegraph.StandardHugeGraph.close(StandardHugeGraph.java:895)
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:104)
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:79)
`

辛苦帮看看是什么原因，或者是否还需要其他适配的地方，感谢回复！

建议复现一下看看~ 急~

**Comment by imbajin** [comment]
首先, 社区版不会再维护这种历史包袱很重的低版本了(以前最低就是2.0开始支持的), 商业版倒是给 hbase1.x 单独做过一个适配, 确认是可以用的, 核心以下:
1. 替换 hbase2.x 相关依赖
2. 如果是更换名字的 api, 替换掉所有报错的代码
3. 如果是2.x 新增, 1.x 没有的, 先尝试注释移除. 
4. 剩下的报错得一个个对着1.x 的源码自己看了

你上面这个报错, 改一下 `hbase-site.xml` 里配置的一个线程池选项让它不要算出负数应该就行了.

**Comment by wuchaojing** [comment]
> 首先, 社区版不会再维护这种历史包袱很重的低版本了(以前最低就是2.0开始支持的), 商业版倒是给 hbase1.x 单独做过一个适配, 确认是可以用的, 核心以下:
> 
> 1. 替换 hbase2.x 相关依赖
> 2. 如果是更换名字的 api, 替换掉所有报错的代码
> 3. 如果是2.x 新增, 1.x 没有的, 先尝试注释移除.
> 4. 剩下的报错得一个个对着1.x 的源码自己看了
> 
> 你上面这个报错, 改一下 `hbase-site.xml` 里配置的一个线程池选项让它不要算出负数应该就行了.

感谢回复~

上面那个报错解决了，追了下代码，原因是1.x版本的hbase-client线程池的core线程数和max线程数默认都是256，但是hugegrap给hbase增加了一个参数`hbase.hconnection.threads.max`，将max线程数默认改成了64，导致core > max，就报了这个错。解决方案就是也增加了一个`hbase.hconnection.threads.core`参数，将core也改成了64。（2.x的hbase-client实现方案不同，没细跟）
![image](https://user-images.githubusercontent.com/37741352/156698227-fb0f6b3e-a5a8-4cec-8d97-acb64c6a1449.png)
