### ISSUE TITLE
hbase配置问题

### ISSUE THREAD

**Issue by lftx1986** [hugegraph/hugegraph#193]
现在想以HBASE为存储端，但是配置时总会出现问题
配置信息如果为：
backend=hbase
serializer=hbase

# hbase backend config
hbase.hosts=localhost
hbase.port=2181

初始化时：
Initing HugeGraph Store...
2018-11-13 16:58:36 740   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2018-11-13 16:58:36 853   [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'hbase' for graph 'hugegraph'
2018-11-13 16:58:38 2537  [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
2018-11-13 16:58:38 2705  [pool-5-thread-1] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
Exception in thread "main" java.nio.BufferUnderflowException
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
	at java.nio.ByteBuffer.get(ByteBuffer.java:715)
	at com.baidu.hugegraph.backend.serializer.BytesBuffer.read(BytesBuffer.java:199)
	at com.baidu.hugegraph.backend.serializer.BytesBuffer.readId(BytesBuffer.java:333)
	at com.baidu.hugegraph.backend.store.hbase.HbaseSerializer.parseIndexName(HbaseSerializer.java:53)
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.readIndex(BinarySerializer.java:445)
	at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.queryByName(SchemaIndexTransaction.java:99)
	at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.query(SchemaIndexTransaction.java:75)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getSchema(SchemaTransaction.java:400)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.lambda$getSchema$3(CachedSchemaTransaction.java:192)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getOrFetch(CachedSchemaTransaction.java:152)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getSchema(CachedSchemaTransaction.java:191)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getPropertyKey(SchemaTransaction.java:114)
	at com.baidu.hugegraph.backend.store.BackendStoreInfo.info(BackendStoreInfo.java:60)
	at com.baidu.hugegraph.backend.store.BackendStoreInfo.exist(BackendStoreInfo.java:68)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:98)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86)

如果修改serializer=binary初始化没问题，但是在数据导入时会出现

[root@bsabj38 hugegraph-loader-0.7.0]# bin/hugegraph-loader -g hugegraph -f example/struct.json -s example/schema.groovy -h 192.168.19.38 -p 28081
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy52.create(Unknown Source)
	at com.baidu.hugegraph.structure.schema.SchemaBuilder$create.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at Script1.run(Script1.groovy:23)
	at com.baidu.hugegraph.loader.executor.GroovyExecutor.execute(GroovyExecutor.java:62)
	at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:161)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:104)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:68)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.baidu.hugegraph.structure.schema.BuilderProxy.invoke(BuilderProxy.java:56)
	... 10 more
Caused by: class java.lang.IllegalArgumentException: Not all index fields '[weight]' are contained in schema properties '[city, date]'
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:119)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:79)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:74)
	at com.baidu.hugegraph.api.schema.IndexLabelAPI.create(IndexLabelAPI.java:43)
	at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:147)
	at com.baidu.hugegraph.structure.schema.IndexLabel$BuilderImpl.create(IndexLabel.java:125)
	at com.baidu.hugegraph.structure.schema.IndexLabel$BuilderImpl.create(IndexLabel.java:108)
	... 14 more

数据导入的例子是loader插件里提供的例子，如果存储端改成memory的话就能成功导入。

如果以hbase为后端的话数据插入出会出现如下问题：
Error!
Invalid entry() with unknown type(0): 0x820102000084333a6c6f70

**Comment by javeme** [comment]
@lftx1986 关于第一个问题，serializer使用hbase或binary任何一个都可以（推荐hbase），但是不能交叉使用，否则请清空hbase的数据之后才能继续修改serializer。
关于第2个问题Not all index fields '[weight]' are contained in schema properties '[city, date]'，请 @Linary 帮忙看下。

**Comment by Nana932** [comment]
请问这个报错怎么解决呢？
2023-04-18 08:31:07 164516 [main] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to commit changes:
com.baidu.hugegraph.backend.BackendException: Exception in backend
	at com.baidu.hugegraph.backend.store.hbase.HbaseSessions$Session.commit(HbaseSessions.java:288) ~[hugegraph-hbase-0.8.0.jar:?]
	at com.baidu.hugegraph.backend.store.hbase.HbaseStore.commitTx(HbaseStore.java:304) ~[hugegraph-hbase-0.8.0.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:245) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:166) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:289) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:262) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.addSchema(SchemaTransaction.java:272) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.addSchema(CachedSchemaTransaction.java:196) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.addPropertyKey(SchemaTransaction.java:112) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.init(BackendStoreSystemInfo.java:56) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.HugeGraph.initBackendStoreSystemInfo(HugeGraph.java:241) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.HugeGraph.initBackend(HugeGraph.java:199) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.cmd.InitStore.initBackend(InitStore.java:115) [hugegraph-dist-0.8.0.jar:?]
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:103) [hugegraph-dist-0.8.0.jar:?]
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86) [hugegraph-dist-0.8.0.jar:?]
	at com.baidu.hugegraph.backend.store.hbase.HbaseSessions$Session.commit(HbaseSessions.java:282) ~[hugegraph-hbase-0.8.0.jar:?]
2023-04-18 08:31:07 164530 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
2023-04-18 08:31:07 164537 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
2023-04-18 08:31:07 164552 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Exception in backend
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:300)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:262)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.addSchema(SchemaTransaction.java:272)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.addSchema(CachedSchemaTransaction.java:196)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.addPropertyKey(SchemaTransaction.java:112)
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.init(BackendStoreSystemInfo.java:56)
	at com.baidu.hugegraph.HugeGraph.initBackendStoreSystemInfo(HugeGraph.java:241)
	at com.baidu.hugegraph.HugeGraph.initBackend(HugeGraph.java:199)
	at com.baidu.hugegraph.cmd.InitStore.initBackend(InitStore.java:115)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:103)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86)
-------------------------------------------------------------------------------------------------------------------------------------
2023-04-18 08:31:07 164530 [hconnection-0x60957c0f-shared-pool3-t3] [WARN ] org.apache.hadoop.hbase.client.AsyncRequestFutureImpl [] - id=1, table=hugegraph:pk, attempt=17/16, failed=1ops, last exception=org.apache.hadoop.hbase.exceptions.RegionOpeningException: org.apache.hadoop.hbase.exceptions.RegionOpeningException: Region hugegraph:pk,,1681394734603.56266d707c829c425fba0c89cfa41250. is opening on master,16020,1681777669268
	at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegionByEncodedName(HRegionServer.java:3069)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.getRegion(RSRpcServices.java:1271)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.multi(RSRpcServices.java:2372)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:36812)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2399)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:124)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:311)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:291)
 on master,16020,1681382489629, tracking started Tue Apr 18 08:28:38 CST 2023; not retrying 1 - final failure
2023-04-18 08:31:07 164530 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
2023-04-18 08:31:07 164536 [main] [INFO ] org.apache.hadoop.hbase.client.ConnectionImplementation [] - Closing master protocol: MasterService
2023-04-18 08:31:07 164537 [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Close zookeeper connection 0x62ea3440 to master:2181
2023-04-18 08:31:07 164537 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
2023-04-18 08:31:07 164538 [task-db-worker-1] [INFO ] org.apache.hadoop.hbase.client.ConnectionImplementation [] - Closing master protocol: MasterService
2023-04-18 08:31:07 164539 [task-db-worker-1] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Close zookeeper connection 0x435871cb to master:2181
2023-04-18 08:31:07 164549 [main] [INFO ] org.apache.hadoop.hbase.client.ConnectionImplementation [] - Closing master protocol: MasterService
2023-04-18 08:31:07 164551 [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Close zookeeper connection 0x014fc1f0 to master:2181
2023-04-18 08:31:07 164552 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
---------------------------------------------------------------------------------------------------------------------------------------

**Comment by JackyYangPassion** [comment]
Please submit a new issue @Nana932

**Comment by JackyYangPassion** [comment]
> ## 请问这个报错怎么解决呢？
> 2023-04-18 08:31:07 164516 [main] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to commit changes:
> com.baidu.hugegraph.backend.BackendException: Exception in backend
> at com.baidu.hugegraph.backend.store.hbase.HbaseSessions$Session.commit(HbaseSessions.java:288) ~[hugegraph-hbase-0.8.0.jar:?]
> at com.baidu.hugegraph.backend.store.hbase.HbaseStore.commitTx(HbaseStore.java:304) ~[hugegraph-hbase-0.8.0.jar:?]
> at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:245) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:166) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:289) [hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:262) [hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.backend.tx.SchemaTransaction.addSchema(SchemaTransaction.java:272) [hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.addSchema(CachedSchemaTransaction.java:196) [hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.backend.tx.SchemaTransaction.addPropertyKey(SchemaTransaction.java:112) [hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.init(BackendStoreSystemInfo.java:56) [hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.HugeGraph.initBackendStoreSystemInfo(HugeGraph.java:241) [hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.HugeGraph.initBackend(HugeGraph.java:199) [hugegraph-core-0.8.0.jar:0.8.0.0]
> at com.baidu.hugegraph.cmd.InitStore.initBackend(InitStore.java:115) [hugegraph-dist-0.8.0.jar:?]
> at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:103) [hugegraph-dist-0.8.0.jar:?]
> at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86) [hugegraph-dist-0.8.0.jar:?]
> at com.baidu.hugegraph.backend.store.hbase.HbaseSessions$Session.commit(HbaseSessions.java:282) ~[hugegraph-hbase-0.8.0.jar:?]
> 2023-04-18 08:31:07 164530 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
> 2023-04-18 08:31:07 164537 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
> 2023-04-18 08:31:07 164552 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
> Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Exception in backend
> at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:300)
> at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:262)
> at com.baidu.hugegraph.backend.tx.SchemaTransaction.addSchema(SchemaTransaction.java:272)
> at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.addSchema(CachedSchemaTransaction.java:196)
> at com.baidu.hugegraph.backend.tx.SchemaTransaction.addPropertyKey(SchemaTransaction.java:112)
> at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.init(BackendStoreSystemInfo.java:56)
> at com.baidu.hugegraph.HugeGraph.initBackendStoreSystemInfo(HugeGraph.java:241)
> at com.baidu.hugegraph.HugeGraph.initBackend(HugeGraph.java:199)
> at com.baidu.hugegraph.cmd.InitStore.initBackend(InitStore.java:115)
> at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:103)
> at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86)
> ## 2023-04-18 08:31:07 164530 [hconnection-0x60957c0f-shared-pool3-t3] [WARN ] org.apache.hadoop.hbase.client.AsyncRequestFutureImpl [] - id=1, table=hugegraph:pk, attempt=17/16, failed=1ops, last exception=org.apache.hadoop.hbase.exceptions.RegionOpeningException: org.apache.hadoop.hbase.exceptions.RegionOpeningException: Region hugegraph:pk,,1681394734603.56266d707c829c425fba0c89cfa41250. is opening on master,16020,1681777669268
> at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegionByEncodedName(HRegionServer.java:3069)
> at org.apache.hadoop.hbase.regionserver.RSRpcServices.getRegion(RSRpcServices.java:1271)
> at org.apache.hadoop.hbase.regionserver.RSRpcServices.multi(RSRpcServices.java:2372)
> at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:36812)
> at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2399)
> at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:124)
> at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:311)
> at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:291)
> on master,16020,1681382489629, tracking started Tue Apr 18 08:28:38 CST 2023; not retrying 1 - final failure
> 2023-04-18 08:31:07 164530 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
> 2023-04-18 08:31:07 164536 [main] [INFO ] org.apache.hadoop.hbase.client.ConnectionImplementation [] - Closing master protocol: MasterService
> 2023-04-18 08:31:07 164537 [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Close zookeeper connection 0x62ea3440 to master:2181
> 2023-04-18 08:31:07 164537 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed
> 2023-04-18 08:31:07 164538 [task-db-worker-1] [INFO ] org.apache.hadoop.hbase.client.ConnectionImplementation [] - Closing master protocol: MasterService
> 2023-04-18 08:31:07 164539 [task-db-worker-1] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Close zookeeper connection 0x435871cb to master:2181
> 2023-04-18 08:31:07 164549 [main] [INFO ] org.apache.hadoop.hbase.client.ConnectionImplementation [] - Closing master protocol: MasterService
> 2023-04-18 08:31:07 164551 [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Close zookeeper connection 0x014fc1f0 to master:2181
> 2023-04-18 08:31:07 164552 [main] [WARN ] com.baidu.hugegraph.backend.store.BackendSessionPool [] - Current session has ever been closed

You should check whether the HBase cluster reads and writes normally
