### ISSUE TITLE
huge-server启动失败

### ISSUE THREAD

**Issue by tl890216** [hugegraph/hugegraph#2]
用一键部署方案，启动报错。Failed to start HugeGraphServer, requires at least 512m free memory
已在多台机器上测试，机器剩余内存分别为180G，50G，4G。系统环境为Centos6.7。

**Comment by double-headed-eagle** [comment]
在bin/util.sh中存在free_memory函数,
if [ "$distributor" == "CentOS" ]; then
            #free=`free -m | grep '\-\/\+' | awk '{print $4}'`
改为
            free=`free -m | grep '^Mem' | awk '{print $4}'

**Comment by tl890216** [comment]
@double-headed-eagle 谢谢，看了代码后发现是lsb_release没有安装。不过又出现新的问题了：
Exception in thread "main" java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map;
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:331)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:311)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:337)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:119)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:59)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:76)
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:54)
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:51)

**Comment by Linary** [comment]
@tl890216 感谢你的反馈，这个确实是一个BUG，我们已经修复。[见提交](https://github.com/hugegraph/hugegraph/commit/d93bd1ba3b3be4b969cc5e2726d275310ef6c16a)
