### ISSUE TITLE
hugegraph-client配置连接问题

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#200]
报错 com.baidu.hugegraph.rest.ClientException: Failed to do request
已经重新创建一个干净的项目 还是报这个错误 
具体连接code :HugeClient hugeClient = new HugeClient("http://192.168.3.31:8080", "hugegraph");
配置文件  hugegraph.properties
```
gremlin.graph=com.baidu.hugegraph.HugeFactory
# cache config
#schema.cache_capacity=1048576
#graph.cache_capacity=10485760
#graph.cache_expire=600
# schema illegal name template
#schema.illegal_name_regex=\s+|~.*
#vertex.default_label=vertex
backend=scylladb
serializer=scylladb
store=hugegraph
# rocksdb backend config
#rocksdb.data_path=/path/to/disk
#rocksdb.wal_path=/path/to/disk
```

请问为什么会出现这种情况

**Comment by Linary** [comment]
你用浏览器或 curl 访问 "http://192.168.3.31:8080/graphs" 可以吗？

**Comment by Linary** [comment]
还有你是想用 rocksdb 还是 scylladb 后端?

**Comment by eternalxj** [comment]
用的是scylladb 后端

**Comment by eternalxj** [comment]
浏览去"http://192.168.3.31:8080/graphs"  有相应 返回 {"graphs":["hugegraph"]}

**Comment by Linary** [comment]
com.baidu.hugegraph.rest.ClientException: Failed to do request 后面还有别的信息吗？

**Comment by Linary** [comment]
还有可以看到服务端的日志吗？

**Comment by eternalxj** [comment]
Exception in thread "main" com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:69)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:115)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:79)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:74)
	at com.baidu.hugegraph.api.gremlin.GremlinAPI.post(GremlinAPI.java:41)
	at com.baidu.hugegraph.driver.GremlinManager.execute(GremlinManager.java:47)
	at com.baidu.hugegraph.api.gremlin.GremlinRequest$Builder.execute(GremlinRequest.java:55)
	at Test_Hugegraph.main(Test_Hugegraph.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
	at com.baidu.hugegraph.rest.RestClient.lambda$post$0(RestClient.java:116)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:67)
	... 12 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:399)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
	... 24 more

**Comment by Linary** [comment]
似乎是`g.V().outE().path()`超时了，你的图的规模多大，有多少点，多少边。如果规模较大的话，最好`g.V('id').outE().path()`选一个特定的顶点去查询。
