### ISSUE TITLE
生产系统server初始化报错

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#226]
请问生产系统初始化报一下错误，要怎么解决
```
Initing HugeGraph Store...
2018-11-26 14:25:36 634   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2018-11-26 14:25:36 739   [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'scylladb' for graph 'hugegraph'
Exception in thread "main" com.datastax.driver.core.exceptions.InvalidQueryException: Counter support is not enabled
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool$Session.execute(CassandraSessionPool.java:202)
	at com.baidu.hugegraph.backend.store.cassandra.CassandraTable.createTable(CassandraTable.java:550)
	at com.baidu.hugegraph.backend.store.cassandra.CassandraTables$Counters.init(CassandraTables.java:84)
	at com.baidu.hugegraph.backend.store.cassandra.CassandraStore$CassandraSchemaStore.initTables(CassandraStore.java:471)
	at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.init(CassandraStore.java:248)
	at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.init(AbstractBackendStoreProvider.java:86)
	at com.baidu.hugegraph.HugeGraph.initBackend(HugeGraph.java:189)
	at com.baidu.hugegraph.cmd.InitStore.initBackend(InitStore.java:115)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:103)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Counter support is not enabled
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:148)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:179)
	at com.datastax.driver.core.RequestHandler.access$2400(RequestHandler.java:49)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:799)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:633)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1075)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:998)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:934)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:397)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Linary** [comment]
你的 scylladb 是什么版本的？

**Comment by eternalxj** [comment]
@Linary 1.7.4

**Comment by eternalxj** [comment]
哪位同学知道这种情况怎么解决？

**Comment by Linary** [comment]
似乎scylladb 1.7默认是禁用counter类型的列的，你可以在配置文件`scylla.yaml`中添加`experimental: true` 试试，参考：
https://stackoverflow.com/questions/44307264/how-to-enable-counter-columns-in-scylla-1-7

**Comment by eternalxj** [comment]
@Linary OK的可以解决，感谢、赞
