### ISSUE TITLE
生产环境hugegraph-loader跑example报错

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#233]
请问 服务都已经起来了 
```
root@/cy/server$ jps
11040 Jps
2740 HugeGraphServer
940 Application
10477 HugeGraphStudio
```
hugegraph-loader跑example报错  错误如下  
```
bin/hugegraph-loader -g hugegraph -f example/struct.json -s example/schema.groovy
Exception in thread "main" com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:69)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:147)
	at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41)
	at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45)
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:101)
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:84)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:59)
	at com.baidu.hugegraph.loader.util.HugeClientWrapper.newHugeClient(HugeClientWrapper.java:44)
	at com.baidu.hugegraph.loader.util.HugeClientWrapper.get(HugeClientWrapper.java:33)
	at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:143)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:109)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:69)
Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at com.baidu.hugegraph.rest.RestClient.lambda$get$2(RestClient.java:148)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:67)
	... 11 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:399)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
	... 23 more
```

**Comment by Linary** [comment]
这个问题是由于版本不匹配导致的，你访问一下 `http://localhost:8080/versions` 看看服务端 API 的版本，然后再在 IDE 里面打开你的 loader，搜索 HugeClient 类，查看方法`checkServerApiVersion`里面的版本区间。

如果不想这么麻烦，建议直接使用GitHub上最新的。

**Comment by eternalxj** [comment]
@Linary 我之前使用的loader是0.7.0  现在下载了0.8.0还是报以下错误
bin/hugegraph-loader -g hugegraph -f example/struct.json -s example/schema.groovy
Exception in thread "main" com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:69)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:147)
	at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41)
	at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45)
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:98)
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:84)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:59)
	at com.baidu.hugegraph.loader.util.HugeClientWrapper.newHugeClient(HugeClientWrapper.java:44)
	at com.baidu.hugegraph.loader.util.HugeClientWrapper.get(HugeClientWrapper.java:33)
	at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:143)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:109)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:69)
Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at com.baidu.hugegraph.rest.RestClient.lambda$get$2(RestClient.java:148)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:67)
	... 11 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:399)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
	... 23 more

**Comment by Linary** [comment]
loader 也需要用新的。

**Comment by eternalxj** [comment]
@Linary 现在loader是0.8.0    hugegraph是0.7.4 hugegraph-studio是0.7.0

**Comment by eternalxj** [comment]
之前loader0.7.0 hugegraph是0.7.4 hugegraph-studio是0.7.0 报错

**Comment by eternalxj** [comment]
现在loader是0.8.0 hugegraph是0.7.4 hugegraph-studio是0.7.0 也还是报错

**Comment by eternalxj** [comment]
对应的hugegraph也要升级到最新吗

**Comment by eternalxj** [comment]
我下个hugegraph080的试试哈

**Comment by eternalxj** [comment]
用hugegraph080还需要初始化后端吗

**Comment by Linary** [comment]
应该都使用0.8.0的，loader和studio可以直接下载压缩包，hugegraph 的需要自己拉源码编译。我们明天应该会把压缩包更新上去

**Comment by eternalxj** [comment]
@Linary  目前hugegraph-0.8.0 hugegraph-loader-0.8. loadexample数据还是报之前的错误

**Comment by eternalxj** [comment]
最新的包建议在https://hugegraph.github.io/hugegraph-doc/download.html 网站上做下更新

**Comment by eternalxj** [comment]
目前下载最新的server和loader server可以正常启动 loader还是Failed to do request

**Comment by eternalxj** [comment]
最新的hugegraph-studio-0.8.0我这编译完源码貌似不可用 启动找不到/cy/server/hugegraph-studio-0.8.0/ui doesn't exist的文件了

**Comment by Linary** [comment]
> 目前下载最新的server和loader server可以正常启动 loader还是Failed to do request

你的server的ip改了吗，如果改了，用loader导入的时候，需要加 -h xxx

**Comment by eternalxj** [comment]
restserver.url=http://127.0.0.1:8080 这个改过 我试试

**Comment by eternalxj** [comment]
还真是这个问题  无语了 多谢

**Comment by Linary** [comment]
😅我也想了好久才想起来。

**Comment by eternalxj** [comment]
之前一直想loader到底怎么跟server联系起来的，一直没想明白，现在才明白是这个-h联系起来的
