### ISSUE TITLE
0.8.0版本启动报错 Failed to update/query TaskStore

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#249]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
2018-11-30 11:29:19 4402  [main] [ERROR] com.baidu.hugegraph.dist.HugeGraphServer [] - HugeRestServer start error:
com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:391) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.queryTask(TaskScheduler.java:365) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.queryTask(TaskScheduler.java:360) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.findTask(TaskScheduler.java:278) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.restoreTasks(TaskScheduler.java:152) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.core.GraphManager.restoreUncompletedTasks(GraphManager.java:213) ~[hugegraph-api-0.8.0.jar:0.31.0.0]
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:77) ~[hugegraph-api-0.8.0.jar:0.31.0.0]
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:102) ~[hugegraph-api-0.8.0.jar:0.31.0.0]
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357) ~[jersey-container-grizzly2-http-2.25.1.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:422) ~[grizzly-http-server-2.3.28.jar:2.3.28]
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:314) ~[grizzly-http-server-2.3.28.jar:2.3.28]
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:290) ~[grizzly-http-server-2.3.28.jar:2.3.28]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:296) ~[jersey-container-grizzly2-http-2.25.1.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:119) ~[jersey-container-grizzly2-http-2.25.1.jar:?]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:59) ~[hugegraph-api-0.8.0.jar:0.31.0.0]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:76) ~[hugegraph-api-0.8.0.jar:0.31.0.0]
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58) ~[hugegraph-dist-0.8.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:60) [hugegraph-dist-0.8.0.jar:?]
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: No primitive index label for '-14'
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_172]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_172]
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:389) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        ... 20 more
Caused by: java.lang.AssertionError: No primitive index label for '-14'
        at com.baidu.hugegraph.schema.IndexLabel.label(IndexLabel.java:178) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.structure.HugeIndex.parseIndexId(HugeIndex.java:169) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.serializer.BinarySerializer.readIndex(BinarySerializer.java:434) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.doIndexQuery(GraphIndexTransaction.java:513) ~[hugegraph-core-0.8.0.jar:0.8.0.0]

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@fisherinbox 这个问题已解决 #239 ，请重新下载tar包更新下再试试。

**Comment by Rainshyabc** [comment]
请问楼主解决了吗，I have the same issue

**Comment by fisherinbox** [comment]
@Rainshyabc 重新下载了tar包,现在没问题了

**Comment by ChenBinaBGitHub** [comment]
本地测试，使用内存作为后端存储，也是报这个错误，也是使用0.8版本
