### ISSUE TITLE
求教：使用cassandra后端，初始化报错

### ISSUE THREAD

**Issue by baibingzhi** [hugegraph/hugegraph#255]
使用cassandra后端，初始化报错，麻烦帮忙看下原因，谢谢

后端配置如下(其他配置都采用默认配置)：
gremlin.graph=com.baidu.hugegraph.HugeFactory
vertex.tx_capacity=1
backend=cassandra
serializer=text
store=myStore
cassandra.host=...
cassandra.port=...
cassandra.username=...
cassandra.password=...

具体报错信息如下
2018-12-04 17:04:14 916   [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'cassandra' for graph 'myStore'
2018-12-04 17:04:16 2794  [main] [WARN ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Session has ever been opened(exist keyspace 'myStore' before)
2018-12-04 17:04:16 2825  [main] [WARN ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Session has ever been opened(exist keyspace 'myStore' before)
2018-12-04 17:04:16 2842  [main] [WARN ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Session has ever been opened(exist keyspace 'myStore' before)
2018-12-04 17:04:16 3123  [task-db-worker-1] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to commit changes:
com.baidu.hugegraph.backend.BackendException: Cassandra store only supports CassandraBackendEntry
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.castBackendEntry(CassandraStore.java:482) ~[hugegraph-cassandra-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.mutate(CassandraStore.java:180) ~[hugegraph-cassandra-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.mutate(CassandraStore.java:174) ~[hugegraph-cassandra-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:243) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:166) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:289) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:262) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.addSchema(SchemaTransaction.java:272) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.addSchema(CachedSchemaTransaction.java:196) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.addPropertyKey(SchemaTransaction.java:112) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.createPropertyKey(TaskScheduler.java:503) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.createPropertyKey(TaskScheduler.java:492) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.createPropertyKey(TaskScheduler.java:488) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.initProperties(TaskScheduler.java:470) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.initSchema(TaskScheduler.java:451) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.lambda$null$0(TaskScheduler.java:130) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
2018-12-04 17:04:16 3128  [task-db-worker-1] [WARN ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Store schema expect state COMMITT_FAIL/COMMITTING/CLEAN than BEGIN when rollback()
2018-12-04 17:04:16 3128  [event-worker-1] [WARN ] com.baidu.hugegraph.event.EventHub [] - Failed to handle event: Event{name='store.init', args=[com.baidu.hugegraph.backend.store.cassandra.CassandraStoreProvider@346f1ce8]}
com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:402) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:394) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.lambda$listenChanges$1(TaskScheduler.java:130) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.event.EventHub.lambda$notify$0(EventHub.java:159) ~[hugegraph-common-1.5.3.jar:1.5.3.0]
Caused by: java.util.concurrent.ExecutionException: com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Cassandra store only supports CassandraBackendEntry
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:400) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Cassandra store only supports CassandraBackendEntry
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:300) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:262) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.addSchema(SchemaTransaction.java:272) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.addSchema(CachedSchemaTransaction.java:196) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.addPropertyKey(SchemaTransaction.java:112) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.createPropertyKey(TaskScheduler.java:503) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.createPropertyKey(TaskScheduler.java:492) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.createPropertyKey(TaskScheduler.java:488) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.initProperties(TaskScheduler.java:470) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.initSchema(TaskScheduler.java:451) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.lambda$null$0(TaskScheduler.java:130) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
2018-12-04 17:04:16 3130  [main] [INFO ] com.baidu.hugegraph.backend.store.BackendStoreProvider [] - Graph 'myStore' has been initialized
2018-12-04 17:04:16 3147  [main] [ERROR] com.baidu.hugegraph.backend.Transaction [] - Failed to commit changes:
com.baidu.hugegraph.backend.BackendException: Cassandra store only supports CassandraBackendEntry
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.castBackendEntry(CassandraStore.java:482) ~[hugegraph-cassandra-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.mutate(CassandraStore.java:180) ~[hugegraph-cassandra-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.mutate(CassandraStore.java:174) ~[hugegraph-cassandra-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:243) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:166) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:289) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:262) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.addSchema(SchemaTransaction.java:272) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.addSchema(CachedSchemaTransaction.java:196) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.addPropertyKey(SchemaTransaction.java:112) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.init(BackendStoreSystemInfo.java:56) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.initBackendStoreSystemInfo(HugeGraph.java:241) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.initBackend(HugeGraph.java:199) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.cmd.InitStore.initBackend(InitStore.java:115) [hugegraph-dist-0.8.0.jar:?]
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:103) [hugegraph-dist-0.8.0.jar:?]
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86) [hugegraph-dist-0.8.0.jar:?]
2018-12-04 17:04:16 3148  [main] [WARN ] com.baidu.hugegraph.backend.store.cassandra.CassandraStore [] - Store schema expect state COMMITT_FAIL/COMMITTING/CLEAN than BEGIN when rollback()
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to commit changes: Cassandra store only supports CassandraBackendEntry
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitOrRollback(AbstractTransaction.java:300)
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.afterWrite(AbstractTransaction.java:262)
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.addSchema(SchemaTransaction.java:272)
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.addSchema(CachedSchemaTransaction.java:196)
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.addPropertyKey(SchemaTransaction.java:112)
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.init(BackendStoreSystemInfo.java:56)
        at com.baidu.hugegraph.HugeGraph.initBackendStoreSystemInfo(HugeGraph.java:241)
        at com.baidu.hugegraph.HugeGraph.initBackend(HugeGraph.java:199)
        at com.baidu.hugegraph.cmd.InitStore.initBackend(InitStore.java:115)
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:103)
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86)

**Comment by javeme** [comment]
@baibingzhi 配置文件中`serializer`不能是`text`，请改为：`serializer=cassandra`

**Comment by baibingzhi** [comment]
谢谢！
