### ISSUE TITLE
hbase作为后端的初始化问题

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#266]
@Linary @javeme 
一共6台机器
机器1作为hugeserver、studio、loader的机器
机器master、slave1、slave2、slave3、slave4作为hbase后端存储
hbase配置文件hbase-env.sh  
export JAVA_HOME=/usr/local/jdk1.8
export  HBASE_MANAGES_ZK=false  
hbase-site.xml
<property> 
　　　　<name>hbase.rootdir</name> 
　　　　<value>hdfs://master:8020/hbase</value> 
　　</property> 
　　<property> 
　　　　<name>hbase.cluster.distributed</name> 
　　　　<value>true</value> 
　　</property> 
　　<property> 
　　　　<name>hbase.zookeeper.quorum</name> 
　　　　<value>slave2,slave3,slave4</value> 
　　</property> 
　　<property> 
　　　　<name>hbase.zookeeper.property.dataDir</name> 
　　　　<value>/mnt/data_1/hbase/data</value> 
　　</property>
regionservers 文件
slave1
slave2
slave3
slave4

hugeserver hugegraph.properties文件
backend=hbase
serializer=hbase
store=hugegraph
hbase.hosts=10.50.1.195,10.50.1.196,10.50.1.197,10.50.1.198,10.50.1.199
hbase.port=2181
其中10.50.1.195,10.50.1.196,10.50.1.197,10.50.1.198,10.50.1.199 代表master、slave1、2、3、4机器
现在初始化 bin/init-store.sh 一直停留到以下log不动
Initing HugeGraph Store...
2018-12-10 10:59:56 635   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2018-12-10 10:59:57 740   [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'hbase' for graph 'hugegraph'
请问是什么原因 需要如何解决？

**Comment by eternalxj** [comment]
还是需要手动在hbase建表？
hbase版本 hbase-1.3.1

**Comment by eternalxj** [comment]
hugegraph-server.log 报错

2018-12-10 11:29:10 485019 [ReadOnlyZKClient-master:2181,slave1:2181,slave2:2181,slave3:2181,slave4:2181@0x291a7e3c] [WARN ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - 0x291a7e3c to master:2181,slave1:2181,slave2:2181,slave3:2181,slave4:2181 failed to connect to zk fo get of /hbase/meta-region-server, retries = 16
java.net.UnknownHostException: master
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_121]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_121]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_121]
	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient.getZk(ReadOnlyZKClient.java:298) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient.run(ReadOnlyZKClient.java:327) ~[hbase-client-2.0.0.jar:2.0.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2018-12-10 11:29:11 486019 [ReadOnlyZKClient-master:2181,slave1:2181,slave2:2181,slave3:2181,slave4:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Initiating client connection, connectString=master:2181,slave1:2181,slave2:2181,slave3:2181,slave4:2181 sessionTimeout=90000 watcher=org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient$$Lambda$26/297286492@2cfaa33e
2018-12-10 11:29:11 486019 [ReadOnlyZKClient-master:2181,slave1:2181,slave2:2181,slave3:2181,slave4:2181@0x291a7e3c] [WARN ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - 0x291a7e3c to master:2181,slave1:2181,slave2:2181,slave3:2181,slave4:2181 failed to connect to zk fo get of /hbase/meta-region-server, retries = 17
java.net.UnknownHostException: master
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_121]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_121]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_121]
	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient.getZk(ReadOnlyZKClient.java:298) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient.run(ReadOnlyZKClient.java:327) ~[hbase-client-2.0.0.jar:2.0.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by eternalxj** [comment]
hugegraph-server.log 日志如下
2018-12-10 11:33:08 5561  [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=6, retries=6, started=4123 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:33:12 9600  [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=7, retries=7, started=8162 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:33:22 19666 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=8, retries=8, started=18228 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:33:32 29718 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=9, retries=9, started=28280 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null

**Comment by eternalxj** [comment]
完整日志 
2018-12-10 11:33:03 643   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2018-12-10 11:33:03 749   [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'hbase' for graph 'hugegraph'
2018-12-10 11:33:03 910   [main] [WARN ] org.apache.hadoop.util.NativeCodeLoader [] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2018-12-10 11:33:04 1057  [main] [INFO ] org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient [] - Connect 0x291a7e3c to 10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181 with session timeout=90000ms, retries 30, retry interval 1000ms, keepAlive=60000ms
2018-12-10 11:33:04 1064  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:zookeeper.version=3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f, built on 03/23/2017 10:13 GMT
2018-12-10 11:33:04 1065  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:host.name=iZbp147of4lcxk7jpomnjcZ
2018-12-10 11:33:04 1065  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:java.version=1.8.0_121
2018-12-10 11:33:04 1065  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:java.vendor=Oracle Corporation
2018-12-10 11:33:04 1065  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:java.home=/usr/local/jdk1.8/jre
2018-12-10 11:33:04 1065  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:java.class.path=/cy/server/test/hugegraph-0.8.0/lib/hugegraph-dist-0.8.0.jar
2018-12-10 11:33:04 1065  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2018-12-10 11:33:04 1066  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:java.io.tmpdir=/tmp
2018-12-10 11:33:04 1066  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:java.compiler=<NA>
2018-12-10 11:33:04 1066  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:os.name=Linux
2018-12-10 11:33:04 1066  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:os.arch=amd64
2018-12-10 11:33:04 1066  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:os.version=3.19.8-100.fc20.x86_64
2018-12-10 11:33:04 1066  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:user.name=root
2018-12-10 11:33:04 1066  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:user.home=/root
2018-12-10 11:33:04 1066  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Client environment:user.dir=/cy/server/test/hugegraph-0.8.0
2018-12-10 11:33:04 1068  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c] [INFO ] org.apache.zookeeper.ZooKeeper [] - Initiating client connection, connectString=10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181 sessionTimeout=90000 watcher=org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient$$Lambda$26/1868996807@6a072fe7
2018-12-10 11:33:04 1082  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c-SendThread(10.50.1.197:2181)] [INFO ] org.apache.zookeeper.ClientCnxn [] - Opening socket connection to server 10.50.1.197/10.50.1.197:2181. Will not attempt to authenticate using SASL (unknown error)
2018-12-10 11:33:04 1086  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c-SendThread(10.50.1.197:2181)] [INFO ] org.apache.zookeeper.ClientCnxn [] - Socket connection established to 10.50.1.197/10.50.1.197:2181, initiating session
2018-12-10 11:33:04 1092  [ReadOnlyZKClient-10.50.1.195:2181,10.50.1.196:2181,10.50.1.197:2181,10.50.1.198:2181,10.50.1.199:2181@0x291a7e3c-SendThread(10.50.1.197:2181)] [INFO ] org.apache.zookeeper.ClientCnxn [] - Session establishment complete on server 10.50.1.197/10.50.1.197:2181, sessionid = 0x16792428c940008, negotiated timeout = 40000
2018-12-10 11:33:04 1097  [main] [WARN ] org.apache.hadoop.hbase.client.ConnectionImplementation [] - Retrieve cluster id failed
java.util.concurrent.ExecutionException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/hbaseid
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_121]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_121]
	at org.apache.hadoop.hbase.client.ConnectionImplementation.retrieveClusterId(ConnectionImplementation.java:527) [hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.ConnectionImplementation.<init>(ConnectionImplementation.java:287) [hbase-client-2.0.0.jar:2.0.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_121]
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:219) [hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:114) [hbase-client-2.0.0.jar:2.0.0]
	at com.baidu.hugegraph.backend.store.hbase.HbaseSessions.open(HbaseSessions.java:93) [hugegraph-hbase-0.8.0.jar:?]
	at com.baidu.hugegraph.backend.store.hbase.HbaseStore.open(HbaseStore.java:133) [hugegraph-hbase-0.8.0.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:68) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:54) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.HugeGraph.openSchemaTransaction(HugeGraph.java:247) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.HugeGraph.access$300(HugeGraph.java:81) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.schemaTransaction(HugeGraph.java:721) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.access$000(HugeGraph.java:574) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.HugeGraph.schemaTransaction(HugeGraph.java:298) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.store.BackendStoreInfo.info(BackendStoreInfo.java:57) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.backend.store.BackendStoreInfo.exist(BackendStoreInfo.java:68) [hugegraph-core-0.8.0.jar:0.8.0.0]
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:98) [hugegraph-dist-0.8.0.jar:?]
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86) [hugegraph-dist-0.8.0.jar:?]
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/hbaseid
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient$ZKTask$1.exec(ReadOnlyZKClient.java:168) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient.run(ReadOnlyZKClient.java:323) ~[hbase-client-2.0.0.jar:2.0.0]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
2018-12-10 11:33:08 5561  [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=6, retries=6, started=4123 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:33:12 9600  [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=7, retries=7, started=8162 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:33:22 19666 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=8, retries=8, started=18228 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:33:32 29718 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=9, retries=9, started=28280 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:33:42 39789 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=10, retries=10, started=38351 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:33:52 49796 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=11, retries=11, started=48358 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:34:12 69888 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=12, retries=12, started=68450 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:34:32 89898 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=13, retries=13, started=88460 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 11:34:53 110071 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=14, retries=14, started=108632 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null

**Comment by eternalxj** [comment]
防火墙都是关的 ping可以ping通 端口则拒绝

**Comment by javeme** [comment]
@eternalxj 看起来可能是hbase版本较低导致的，建议更新 hbase 1.3.1 为 2.0 以上试试。

**Comment by eternalxj** [comment]
@javeme  重新安装了hbase 初始化报其他错误了 但是zookeeper的根目录有hbase 这个文件夹
2018-12-10 17:35:08 1774  [main] [WARN ] org.apache.hadoop.hbase.client.ConnectionImplementation [] - Retrieve cluster id failed
java.util.concurrent.ExecutionException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/hbaseid
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_121]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_121]
	at  .................
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/hbaseid
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.10.jar:3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f]
	at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient$ZKTask$1.exec(ReadOnlyZKClient.java:168) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.zookeeper.ReadOnlyZKClient.run(ReadOnlyZKClient.java:323) ~[hbase-client-2.0.0.jar:2.0.0]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
2018-12-10 17:35:13 6248  [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=6, retries=6, started=4125 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
2018-12-10 17:35:17 10257 [main] [INFO ] org.apache.hadoop.hbase.client.RpcRetryingCallerImpl [] - Call exception, tries=7, retries=7, started=8134 ms ago, cancelled=false, msg=org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null

**Comment by javeme** [comment]
@eternalxj 请参考一下这些链接：
- https://community.hortonworks.com/questions/212329/hdp30-timeline-service-v2-reader-cannot-create-zoo.html
- https://github.com/naver/pinpoint/issues/363
- https://blog.csdn.net/agony_sun/article/details/77480109

**Comment by eternalxj** [comment]
@javeme 请问5台机器 master、slave1、slave2、slave3、slave4作为hbase后端存储  slave2、slave3、slave4 是zookeeper 
在 hugeserver hugegraph.properties文件

hbase.hosts=10.50.1.195,10.50.1.196,10.50.1.197,10.50.1.198,10.50.1.199 这个写的是zookeeper的ip还是所有hbase的ip？

**Comment by eternalxj** [comment]
改了下配置文件把
<property>
        <name>zookeeper.znode.parent</name>
        
        <value>/mnt/data_1/hbase/zk</value>
    </property>
改成
<property>
        <name>zookeeper.znode.parent</name>
        
        <value>/hbase/hbaseid</value>
    </property>
之前报的 KeeperErrorCode = NoNode for /hbase/hbaseid 没了
变成$NoNodeException: KeeperErrorCode = NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
。。。。有点晕了

**Comment by eternalxj** [comment]
本身hbase服务、建表插入数据没问题

**Comment by eternalxj** [comment]
@javeme @Linary  就是hugeserver初始化的时候会出现问题
是不是需要预先在hbase里面建表啥的？

**Comment by eternalxj** [comment]
看样子hugegraph的log主要有三个问题  找不到zookeeper中/hbase 下面的master节点、meta-region-server节点 貌似还是hbase版本的问题 想确定一下hugegraph 后端的hbase必须是那个版本以上的？
Will not attempt to authenticate using SASL (unknown error)
NoNode for /hbase/meta-region-server, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null
NoNode for /hbase/master, details=row 'hugegraph:schema_si' on table 'hbase:meta' at null

**Comment by javeme** [comment]
> @javeme 请问5台机器 master、slave1、slave2、slave3、slave4作为hbase后端存储 slave2、slave3、slave4 是zookeeper
> 在 hugeserver hugegraph.properties文件
> 
> hbase.hosts=10.50.1.195,10.50.1.196,10.50.1.197,10.50.1.198,10.50.1.199 这个写的是zookeeper的ip还是所有hbase的ip？

@eternalxj hbase.hosts 填写任意一个zookeeper的IP即可。

**Comment by lishuai588** [comment]
我用Phoenix连接hbase的时候也遇到了同样的问题，尝试了很多方法都没有效果，最后将hbase-site.xml文件复制到了项目的resource目录下，改问题解决了

**Comment by zdy963** [comment]
用HBase2.2的时候也遇到了这个问题。把`.properties`文件中的`hbase.znode_parent=/hbsae`删掉，就可以正常初始化了。
有人用JanusGraph+HBase也有遇到过相似的[问题](https://juejin.im/post/5da956bb518825558b46814b)。文中提到可能是JanusGraph指向的znode和hbase指向的存在差异。一个解法是修改JanusGraph的配置，另一个是配置`hbase-site.xml`中`zookeeper.znode.parent=/hbase`。但第二种办法在我这边并没有效果。

**Comment by chenygie** [comment]
# 显示hugegraph 读取hbase 表信息失败
PS： hugegraph 网上资料好少，社区都不知在哪。。。。

sudo bash hugegraph-0.10.4_hbase/bin/init-store.sh 
Initing HugeGraph Store...
2021-08-24 18:48:52 954   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2021-08-24 18:48:52 1028  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'hbase' for graph 'hugegraph'
2021-08-24 18:51:03 132076 [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Close graph hugegraph[hugegraph]
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to obtain table info
        at com.baidu.hugegraph.backend.store.hbase.HbaseStore.initialized(HbaseStore.java:312)
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:88)
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:99)
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87)
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=16, exceptions:

**Comment by imbajin** [comment]
@chenygie 社区就在这里呢, 以 github 为主, 交流群也有, 不过建议具体问题还是这里提

你可以按 issue 模板提一个单独的问题, 如果不同于现在的.  (注意更新一下上下文, 具体一点的 server 信息, hbase 版本等)
