### ISSUE TITLE
Table 'hugegraph+si' is not opened

### ISSUE THREAD

**Issue by bigdata-eqxiu** [hugegraph/hugegraph#28]
Caused by: com.baidu.hugegraph.backend.BackendException: Table 'hugegraph+si' is not opened
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.cf(RocksDBStdSessions.java:186)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.access$000(RocksDBStdSessions.java:58)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.scan(RocksDBStdSessions.java:514)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBTable.queryById(RocksDBTable.java:147)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBTables$SecondaryIndex.queryByCond(RocksDBTables.java:179)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBTable.query(RocksDBTable.java:133)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.query(RocksDBStore.java:266)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.query(AbstractTransaction.java:104)
	at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.queryByName(SchemaIndexTransaction.java:96)
	at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.query(SchemaIndexTransaction.java:75)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getSchema(SchemaTransaction.java:315)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.lambda$getSchema$3(CachedSchemaTransaction.java:192)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getOrFetch(CachedSchemaTransaction.java:152)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getSchema(CachedSchemaTransaction.java:191)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getPropertyKey(SchemaTransaction.java:105)
	at com.baidu.hugegraph.HugeGraph.propertyKey(HugeGraph.java:312)
	at com.baidu.hugegraph.traversal.optimize.TraversalUtil.convCompare2UserpropRelation(TraversalUtil.java:322)
	at com.baidu.hugegraph.traversal.optimize.TraversalUtil.convCompare2Relation(TraversalUtil.java:274)
	at com.baidu.hugegraph.traversal.optimize.TraversalUtil.convHas2Condition(TraversalUtil.java:192)
	at com.baidu.hugegraph.traversal.optimize.TraversalUtil.fillConditionQuery(TraversalUtil.java:178)
	at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.vertices(HugeGraphStep.java:87)
	at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.lambda$new$0(HugeGraphStep.java:66)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:139)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50)
	at org.apache.tinkerpop.gremlin.process.traversal.step.branch.RepeatStep.standardAlgorithm(RepeatStep.java:188)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ComputerAwareStep.processNextStart(ComputerAwareStep.java:46)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:36)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.PathStep.processNextStart(PathStep.java:117)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62)
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85)
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382)
	at org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:239)
	at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:320)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:278)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by javeme** [comment]
Could you describe the steps to reproduce? Thank you.

**Comment by javeme** [comment]
may be same as #122
