### ISSUE TITLE
Lock error thrown when modifying schema and data dynamically

### ISSUE THREAD

**Issue by xuekang99** [hugegraph/hugegraph#32]
The schema created at the beginning can't satisfy our requirement, so we have to modify the schema to load data into the database. When we modify the schema and invoke setProperty method, the following exception thrown:
```
com.baidu.hugegraph.exception.ServerException: Lock [il_delete:35] is locked by other operation
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.rest.RestClient.put(RestClient.java:142) ~[hugegraph-common-1.4.9.jar:1.4.9.0]
	at com.baidu.hugegraph.api.graph.VertexAPI.append(VertexAPI.java:70) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.driver.GraphManager.appendVertexProperty(GraphManager.java:143) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.structure.graph.Vertex.setProperty(Vertex.java:73) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.structure.graph.Vertex.property(Vertex.java:63) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugegraph.structure.graph.Vertex.property(Vertex.java:30) ~[hugegraph-client-1.5.8.jar:1.5.8.0]
	at com.baidu.hugedragon.repository.graphdb.hugegraph.HugeGraphElement.setProperty(HugeGraphElement.java:118) ~[classes/:?]
	... 19 more
```
### Steps to reproduce

- Create a vertex label
- Add a property key 
- Add a property with property key created in last step in the vertex label
- Set value for the new created property

### Environments
- hugegraph-client 1.5.8
- hugegraph-core 0.7.4

**Comment by Linary** [comment]
这的确是一个BUG，原因是服务端的IndexLabel在create时可能在内部生成异步任务，但是没有对外返回taskId，导致这个接口表现得是一个同步操作，但实际上是一个异步操作。我们正着手修复。
