### ISSUE TITLE
Could not initialize class org.rocksdb.Options

### ISSUE THREAD

**Issue by javeme** [hugegraph/hugegraph#335]
Reference link: https://github.com/confluentinc/ksql/issues/1332
> If the user runs into this, the best solution is to set java.io.tmpdir to a directory which is writable by all users.

**Comment by javeme** [comment]
this error also occurred on macOS 10.11.6:
```
# bin/init-store.sh 
Initing HugeGraph Store...
2019-04-20 11:59:24 808   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2019-04-20 11:59:24 939   [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'rocksdb' for graph 'hugegraph'
2019-04-20 11:59:24 1006  [main] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: rocksdb-data/schema
2019-04-20 11:59:25 1142  [task-db-worker-1] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: rocksdb-data/system
Exception in thread "main" com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
	at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:397)
	at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:389)
	at com.baidu.hugegraph.task.TaskScheduler.close(TaskScheduler.java:205)
	at com.baidu.hugegraph.task.TaskManager.closeScheduler(TaskManager.java:73)
	at com.baidu.hugegraph.HugeGraph.close(HugeGraph.java:460)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:107)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.Options
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:395)
	... 6 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.Options
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.listCFs(RocksDBStdSessions.java:255)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.mergeOldCFs(RocksDBStdSessions.java:232)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:100)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:241)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:181)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:172)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:155)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72)
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30)
	at com.baidu.hugegraph.backend.tx.GraphTransaction.<init>(GraphTransaction.java:119)
	at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.<init>(TaskScheduler.java:406)
	at com.baidu.hugegraph.task.TaskScheduler.tx(TaskScheduler.java:111)
	at com.baidu.hugegraph.task.TaskScheduler.lambda$close$3(TaskScheduler.java:206)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

hugegraph v0.9.2, may be similar to #371
