### ISSUE TITLE
hugegraph-tool 备份请教

### ISSUE THREAD

**Issue by alegjk** [hugegraph/hugegraph#342]
![image](https://user-images.githubusercontent.com/40269185/51659755-87098d00-1fe6-11e9-8dac-2a43a66364b5.png)

hugegraph-tools执行备份操作的时候， 异常， 提示顶点/边的数目过大

`Caused by: com.baidu.hugegraph.rest.ClientException: Exception occurred while backing up edges
        at com.baidu.hugegraph.base.RetryManager.retry(RetryManager.java:76)
        at com.baidu.hugegraph.manager.BackupManager.lambda$backupEdges$3(BackupManager.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: class com.baidu.hugegraph.exception.LimitExceedException: Too many records(must <=800000) for the query: Query for EDGE_OUT offset=0, limit=9223372036854775807, order by {} where id in [] and [ID scan Shard{start=2317021520, end=2322672792, length=0}]
        at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
        at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63)
        at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:169)
        at com.baidu.hugegraph.api.traverser.EdgesAPI.scan(EdgesAPI.java:66)
        at com.baidu.hugegraph.driver.TraverserManager.edges(TraverserManager.java:189)
        at com.baidu.hugegraph.manager.BackupManager.lambda$null$2(BackupManager.java:118)
        at com.baidu.hugegraph.base.RetryManager.retry(RetryManager.java:73)
        ... 6 more`
https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-tools.html
上以及命令行上的操作提示都并未提及这一限制， 请问如果想要做全量数据备份， 应该如何处理？
我的操作命令如下：
bin/hugegraph backup -t all -d /data/hugegraph_backup
顶点在400W， 边在2000万左右

**Comment by zhoney** [comment]
导致原因是一个shard中的数据量大于80w导致的。

hugegraph-0.9版本中shard的scan API将支持paging #360 ，对应的client和tools中都进行了支持，解决了单个shard数据量大以及超级顶点的backup问题。

> scan with paging的代码已提交，还未合入，参见issue #360

**Comment by hklmuaqmn** [comment]
请问HugeGraph 0.9什么时候发布？

**Comment by zhoney** [comment]
@hklmuaqmn 预计3月下旬发布

**Comment by suesunss** [comment]
@zhoney 请问 hugegraph 分布式方案年内有计划吗？
