### ISSUE TITLE
请问使用hugeGraph studio查询图库，总是出现 Faild to do request 是为什么

### ISSUE THREAD

**Issue by xu0612204126** [hugegraph/hugegraph#344]
大约有20万个点，50万的边，在http://192.168.28.128:8088/ 的浏览器界面中输入：
g.E().count()  或者  一个查询，例如： g.V().and(outE('supports')).values('name') 

会提示： 
Error!
Failed to do request

这是为什么？

**Comment by xu0612204126** [comment]
**后台的错误日志：**
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
2019-01-24 17:12:53 28618358 [gremlin-server-exec-2] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Error encountered evaluating script: g.E().hasLabel("eamilEron").count()
java.io.InterruptedIOException: null
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:214) ~[hbase-client-2.0.0.jar:2.0.0]
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:58) ~[hbase-client-2.0.0.jar:2.0.0]
        at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithoutRetries(RpcRetryingCallerImpl.java:192) ~[hbase-client-2.0.0.jar:2.0.0]
        at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:269) ~[hbase-client-2.0.0.jar:2.0.0]
        at org.apache.hadoop.hbase.client.ClientScanner.loadCache(ClientScanner.java:437) ~[hbase-client-2.0.0.jar:2.0.0]
        at org.apache.hadoop.hbase.client.ClientScanner.nextWithSyncCache(ClientScanner.java:312) ~[hbase-client-2.0.0.jar:2.0.0]
        at org.apache.hadoop.hbase.client.ClientScanner.next(ClientScanner.java:597) ~[hbase-client-2.0.0.jar:2.0.0]
        at org.apache.hadoop.hbase.client.ResultScanner$1.hasNext(ResultScanner.java:53) ~[hbase-client-2.0.0.jar:2.0.0]
        at com.baidu.hugegraph.backend.store.hbase.HbaseSessions$RowIterator.hasNext(HbaseSessions.java:491) ~[hugegraph-hbase-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.serializer.BinaryEntryIterator.fetch(BinaryEntryIterator.java:71) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.store.BackendEntryIterator.hasNext(BackendEntryIterator.java:55) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.iterator.ExtendableIterator.fetch(ExtendableIterator.java:95) ~[hugegraph-common-1.5.3.jar:1.5.3.0]
        at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:41) ~[hugegraph-common-1.5.3.jar:1.5.3.0]
        at com.baidu.hugegraph.iterator.ExtendableIterator.fetch(ExtendableIterator.java:89) ~[hugegraph-common-1.5.3.jar:1.5.3.0]
        at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:41) ~[hugegraph-common-1.5.3.jar:1.5.3.0]
        at com.baidu.hugegraph.iterator.FlatMapperIterator.fetch(FlatMapperIterator.java:52) ~[hugegraph-common-1.5.3.jar:1.5.3.0]
        at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:41) ~[hugegraph-common-1.5.3.jar:1.5.3.0]
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409) ~[guava-19.0.jar:?]
        at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:692) ~[guava-19.0.jar:?]
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256) ~[guava-19.0.jar:?]
        at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.queryEdgesFromBackend(CachedGraphTransaction.java:118) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.queryEdges(GraphTransaction.java:599) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.edges(HugeGraph.java:395) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.edges(HugeGraphStep.java:122) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.lambda$new$0(HugeGraphStep.java:66) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:139) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.hasNext(ExpandableStepIterator.java:42) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processAllStarts(ReducingBarrierStep.java:83) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processNextStart(ReducingBarrierStep.java:113) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:239) ~[gremlin-server-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:320) ~[gremlin-groovy-3.2.5.jar:3.2.5]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
        at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.8.0.jar:0.31.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by suesunss** [comment]
参考[这个 issue](https://github.com/hugegraph/hugegraph/issues/102)。

**Comment by javeme** [comment]
@xu0612204126 请试试`g.E().limit(1)`是否可以执行成功，如果这个可以的话那说明`g.E().count()`超时了。理论上50万的边不会超时，可以检查一下hbase连接是否有问题，比如跨外网了或者hbase服务本身有问题。
