### ISSUE TITLE
初始化自定义存储后端失败：Not exists BackendStoreProvider

### ISSUE THREAD

**Issue by hujinbo** [hugegraph/hugegraph#359]
v0.8.0版本使用HugeGraph Plugin机制扩展自定义后端，执行init-store.sh初始化数据库时，会报如下异常：
```
[root@master hugegraph-0.8.0]# bin/init-store.sh 
Initing HugeGraph Store...
2019-02-12 10:51:23 733   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2019-02-12 10:51:23 741   [main] [WARN ] com.baidu.hugegraph.config.HugeConfig [] - The config option 'snappy.driver' is redundant, please ensure it has been registered
2019-02-12 10:51:23 741   [main] [WARN ] com.baidu.hugegraph.config.HugeConfig [] - The config option 'snappy.url' is redundant, please ensure it has been registered
2019-02-12 10:51:23 741   [main] [WARN ] com.baidu.hugegraph.config.HugeConfig [] - The config option 'snappy.username' is redundant, please ensure it has been registered
2019-02-12 10:51:24 835   [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'snappydata' for graph 'bigraph'
2019-02-12 10:51:24 836   [main] [ERROR] com.baidu.hugegraph.HugeGraph [] - Failed to init backend store: Not exists BackendStoreProvider: snappydata
Exception in thread "main" com.baidu.hugegraph.HugeException: Failed to init backend store
	at com.baidu.hugegraph.HugeGraph.<init>(HugeGraph.java:140)
	at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:44)
	at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:56)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:95)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87)
```

查看com.baidu.hugegraph.cmd.InitStore源码，没有发现registerPlugins相关代码；在init-store.sh中没有添加hugegraph-0.8.0/plugins目录下的Jar包到CLASSPATH中
```
    public static void main(String[] args)
                       throws ConfigurationException, InterruptedException {
        E.checkArgument(args.length == 1,
                        "Init store only accept one config file.");
        E.checkArgument(args[0].endsWith(".yaml"),
                        "Init store only accept yaml config file.");

        String confFile = args[0];
        RegisterUtil.registerBackends();//只注册了内置后端

        YamlConfiguration config = new YamlConfiguration();
        config.load(confFile);

        List<ConfigurationNode> nodes = config.getRootNode()
                                              .getChildren(GRAPHS);
        E.checkArgument(nodes.size() == 1,
                        "Must contain one '%s' in config file '%s'",
                        GRAPHS, confFile);

        List<ConfigurationNode> graphNames = nodes.get(0).getChildren();

        E.checkArgument(!graphNames.isEmpty(),
                        "Must contain at least one graph");

        for (ConfigurationNode graphName : graphNames) {
            String configPath = graphName.getValue().toString();
            initGraph(configPath);
        }

        HugeGraph.shutdown(30L);
    }
```

所以目前我的解决方法如下：
1、修改com.baidu.hugegraph.cmd.InitStore源码，在第69行添加RegisterUtil.registerPlugins();
2、将Plugin Jar包放至hugegraph-0.8.0/lib下，使ClassLoader能够加载到Plugin类

请问该问题有无更好的解决方式，或后续版本能否支持初始化自定义存储后端？谢谢！

**Comment by javeme** [comment]
@hujinbo 谢谢反馈，后续会支持初始化自定义存储后端。
@Linary 请增加下初始化的插件机制。
