### ISSUE TITLE
关于边索引的问题

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#362]
经测试，当一个边建立5个索引会保错，4个索引则正常，请问当一个边的索引数大于等于5是会建立失败吗
有什么方法解决这个问题吗

主要为了减少边的数量所以某些边的属性比较多，所以需要索引数比较多

有什么解决方案吗
@Linary @javeme

**Comment by Linary** [comment]
@eternalxj 并没有这个限制，可能是你创建的索引有冗余的，看看你的schema。

**Comment by eternalxj** [comment]
目前的索引详情 前4个都ok 加到transBydcnt 索引的时候就报错了
schema.indexLabel("transByfirst").onE("trans").by("first").secondary().ifNotExist().create();
schema.indexLabel("transBylast").onE("trans").by("last").secondary().ifNotExist().create();
schema.indexLabel("transByfee").onE("trans").by("fee").secondary().ifNotExist().create();
schema.indexLabel("transBycnt").onE("trans").by("cnt").secondary().ifNotExist().create();
schema.indexLabel("transBydcnt").onE("trans").by("dcnt").secondary().ifNotExist().create();
属性如下
schema.propertyKey("first").asText().ifNotExist().create();
schema.propertyKey("last").asText().ifNotExist().create();
schema.propertyKey("fee").asText().ifNotExist().create();
schema.propertyKey("cnt").asText().ifNotExist().create();
schema.propertyKey("dcnt").asText().ifNotExist().create();
schema.propertyKey("un_r").asText().ifNotExist().create();
schema.propertyKey("un_p").asText().ifNotExist().create();
schema.edgeLabel("trans").sourceLabel("rt_person").targetLabel("rt_person").properties("first", "last", "fee", "cnt", "dcnt", "un_r", "un_p").ifNotExist().create();
@Linary

**Comment by Linary** [comment]
@eternalxj 我在本地试过了，没能复现你说的问题。报错的信息是什么样的呢？

**Comment by eternalxj** [comment]
@Linary 报错信息如下
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy52.create(Unknown Source)
        at com.baidu.hugegraph.structure.schema.SchemaBuilder$create.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at Script1.run(Script1.groovy:19)
        at com.baidu.hugegraph.loader.executor.GroovyExecutor.execute(GroovyExecutor.java:62)
        at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:153)
        at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:109)
        at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:69)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.baidu.hugegraph.structure.schema.BuilderProxy.invoke(BuilderProxy.java:56)
        ... 10 more
Caused by: com.baidu.hugegraph.rest.ClientException: Task '13' is 'failed', result is 'null'
        at com.baidu.hugegraph.api.task.TaskAPI.waitUntilTaskSuccess(TaskAPI.java:109)
        at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:177)
        at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:170)
        at com.baidu.hugegraph.structure.schema.IndexLabel$BuilderImpl.create(IndexLabel.java:125)
        at com.baidu.hugegraph.structure.schema.IndexLabel$BuilderImpl.create(IndexLabel.java:108)
        ... 15 more

**Comment by Linary** [comment]
那服务端日志里面有异常信息吗？

**Comment by eternalxj** [comment]
@Linary hugegraph-loader.log 里面到是没有报任何错误 ，之前显示的错误是直接弹出的

**Comment by Linary** [comment]
@eternalxj 看看 hugegraph-server.log 里面有没有什么错误。

**Comment by eternalxj** [comment]
@Linary 奇怪，第一次都会报错 在重新执行load命令就好了
