### ISSUE TITLE
后端存储使用Memory，使用backup/Restore，出现Not support metadata 'splits'

### ISSUE THREAD

**Issue by yandaxin** [hugegraph/hugegraph#370]
您好！
我后端使用的是memory进行存储，想要用tool工具进行备份时出现下面这个异常，请问有办法解决吗？还是说使用内存做后端存储，就是没办法备份呢？
或者hugegraph使用memory做后端，有什么办法在关机之前存储，开机之后恢复？

![wki o f147b _zzy d_n 5](https://user-images.githubusercontent.com/19798112/53314490-8facf600-38f9-11e9-8aaf-944d9888e02a.png)

### Specifications of environment 环境信息
- hugegraph version: {0.8.0}
- operating system: {ubuntu16.04 64}
- hugegraph backend: {memory}

**Comment by javeme** [comment]
@yandaxin memory后端确实没办法备份，建议使用其它可持久化的后端。

**Comment by yandaxin** [comment]
@javeme 多谢盖章！

**Comment by Lucifer-YU** [comment]
我也遇上了同样的问题, 但我用的mysql 的backend，请问有什么建议？
Graph 'hugegraph' start backup!
Exception in thread "main" class com.baidu.hugegraph.exception.NotSupportException: Not support metadata 'splits'
        at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
        at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63)
        at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:169)
        at com.baidu.hugegraph.api.traverser.EdgesAPI.shards(EdgesAPI.java:57)
        at com.baidu.hugegraph.driver.TraverserManager.edgeShards(TraverserManager.java:161)
        at com.baidu.hugegraph.manager.BackupManager.backupEdges(BackupManager.java:112)
        at com.baidu.hugegraph.manager.BackupManager.backup(BackupManager.java:67)
        at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:115)
        at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:280)

**Comment by yandaxin** [comment]
@Lucifer-YU 你好，我这么配置的，没有问题。
![image](https://user-images.githubusercontent.com/19798112/54488442-da100a00-48dc-11e9-92d2-91795ba8c523.png)

**Comment by javeme** [comment]
@yandaxin memory/mysql这两类“非大数据”的后端都没有支持splits接口，目前只能通过vertex-list/edge-list接口把数据拉下出来，然后在使用create接口写回去。
后续我们会考虑到这种场景，支持memory/mysql后端的数据的backup/restore

**Comment by javeme** [comment]
类似的问题：https://github.com/hugegraph/hugegraph/issues/777

**Comment by zhoney** [comment]
#974 中支持了MySQL和memory的shard，并在 [tools pr 56](https://github.com/hugegraph/hugegraph-tools/pull/56)中进行了适配
