### ISSUE TITLE
hugegraph 无法启动

### ISSUE THREAD

**Issue by baibingzhi** [hugegraph/hugegraph#377]
之前正常运行，在一次删除schema的时候报了事务过小的错误，于是修改了 properties配置文件
    vertex.tx_capacity=1 
    改成了 
    vertex.tx_capacity=100
    edge.tx_capacity=100
然后 stop hugegraph-server，再次start失败了。
麻烦看下是什么原因导致的，谢谢！！

版本是0.8.0。
以下是启动日志：

2019-02-28 11:32:09 3965  [main] [INFO ] com.baidu.hugegraph.dist.HugeGremlinServer [] -
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----

2019-02-28 11:32:10 4734  [main] [INFO ] com.baidu.hugegraph.dist.HugeGremlinServer [] - Configuring Gremlin Server from conf/gremlin-server.yaml
2019-02-28 11:32:10 5261  [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'cassandra' for graph 'fanqizha'
2019-02-28 11:32:10 5309  [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Graph [hugegraph] was successfully configured via [conf/hugegraph.properties].
2019-02-28 11:32:10 5309  [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Graph [hugegraph] was successfully configured via [conf/hugegraph.properties].
2019-02-28 11:32:10 5309  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor [] - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
2019-02-28 11:32:10 5309  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor [] - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
2019-02-28 11:32:11 6495  [main] [INFO ] org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines [] - Loaded gremlin-groovy ScriptEngine
2019-02-28 11:32:11 6495  [main] [INFO ] org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines [] - Loaded gremlin-groovy ScriptEngine
2019-02-28 11:32:12 7527  [main] [INFO ] org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor [] - Initialized gremlin-groovy ScriptEngine with scripts/empty-sample.groovy
2019-02-28 11:32:12 7527  [main] [INFO ] org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor [] - Initialized gremlin-groovy ScriptEngine with scripts/empty-sample.groovy
2019-02-28 11:32:12 7528  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor [] - Initialized GremlinExecutor and preparing GremlinScriptEngines instances.
2019-02-28 11:32:12 7528  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor [] - Initialized GremlinExecutor and preparing GremlinScriptEngines instances.
2019-02-28 11:32:12 7585  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor [] - Initialized gremlin-groovy GremlinScriptEngine and registered metrics
2019-02-28 11:32:12 7585  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor [] - Initialized gremlin-groovy GremlinScriptEngine and registered metrics
2019-02-28 11:32:12 7687  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.MetricManager [] - Configured Metrics CsvReporter configured with report interval=180000ms to fileName=/tmp/gremlin-server-metrics.csv
2019-02-28 11:32:12 7687  [main] [INFO ] org.apache.tinkerpop.gremlin.server.util.MetricManager [] - Configured Metrics CsvReporter configured with report interval=180000ms to fileName=/tmp/gremlin-server-metrics.csv
2019-02-28 11:32:13 7728  [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executing start up LifeCycleHook
2019-02-28 11:32:13 7728  [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executing start up LifeCycleHook
2019-02-28 11:32:13 7743  [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executed once at startup of Gremlin Server.
2019-02-28 11:32:13 7743  [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executed once at startup of Gremlin Server.
2019-02-28 11:32:13 7855  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/vnd.gremlin-v1.0+gryo-lite with org.apache.tinkerpop.gremlin.driver.ser.GryoLiteMessageSerializerV1d0
2019-02-28 11:32:13 7855  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/vnd.gremlin-v1.0+gryo-lite with org.apache.tinkerpop.gremlin.driver.ser.GryoLiteMessageSerializerV1d0
2019-02-28 11:32:13 7855  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/vnd.gremlin-v1.0+gryo-stringd with org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0
2019-02-28 11:32:13 7855  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/vnd.gremlin-v1.0+gryo-stringd with org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0
2019-02-28 11:32:13 8223  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/vnd.gremlin-v1.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0
2019-02-28 11:32:13 8223  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/vnd.gremlin-v1.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0
2019-02-28 11:32:13 8272  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/vnd.gremlin-v2.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0
2019-02-28 11:32:13 8272  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/vnd.gremlin-v2.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0
2019-02-28 11:32:13 8274  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0
2019-02-28 11:32:13 8274  [main] [INFO ] org.apache.tinkerpop.gremlin.server.AbstractChannelizer [] - Configured application/json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0
2019-02-28 11:32:13 8467  [gremlin-server-boss-1] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Gremlin Server configured with worker thread pool of 1, gremlin pool of 8 and boss thread pool of 1.
2019-02-28 11:32:13 8467  [gremlin-server-boss-1] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Gremlin Server configured with worker thread pool of 1, gremlin pool of 8 and boss thread pool of 1.
2019-02-28 11:32:13 8467  [gremlin-server-boss-1] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Channel started at port 8182.
2019-02-28 11:32:13 8467  [gremlin-server-boss-1] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Channel started at port 8182.
2019-02-28 11:32:15 9898  [main] [INFO ] com.baidu.hugegraph.server.RestServer [] - RestServer starting...
Feb 28, 2019 11:32:40 AM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [10.9.21.155:8081]
2019-02-28 11:32:40 35274 [main] [INFO ] com.baidu.hugegraph.server.RestServer [] - Graph 'hugegraph' was successfully configured via 'conf/hugegraph.properties'
2019-02-28 11:32:42 37140 [main] [ERROR] com.baidu.hugegraph.dist.HugeGraphServer [] - HugeRestServer start error:
com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:402) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.queryTask(TaskScheduler.java:362) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.queryTask(TaskScheduler.java:357) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.findTask(TaskScheduler.java:275) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.restoreTasks(TaskScheduler.java:153) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.core.GraphManager.restoreUncompletedTasks(GraphManager.java:213) ~[hugegraph-api-0.8.0.jar:0.31.0.0]
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:77) ~[hugegraph-api-0.8.0.jar:0.31.0.0]
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:102) ~[hugegraph-api-0.8.0.jar:0.31.0.0]
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357) ~[jersey-container-grizzly2-http-2.25.1.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:422) ~[grizzly-http-server-2.3.28.jar:2.3.28]
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:314) ~[grizzly-http-server-2.3.28.jar:2.3.28]
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:290) ~[grizzly-http-server-2.3.28.jar:2.3.28]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:296) ~[jersey-container-grizzly2-http-2.25.1.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:119) ~[jersey-container-grizzly2-http-2.25.1.jar:?]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:59) ~[hugegraph-api-0.8.0.jar:0.31.0.0]
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:76) ~[hugegraph-api-0.8.0.jar:0.31.0.0]
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58) ~[hugegraph-dist-0.8.0.jar:?]
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:60) [hugegraph-dist-0.8.0.jar:?]
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Undefined property key: '~task_status'
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_181]
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:400) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        ... 20 more
Caused by: java.lang.IllegalArgumentException: Undefined property key: '~task_status'
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146) ~[guava-19.0.jar:?]
        at com.baidu.hugegraph.util.E.checkArgument(E.java:56) ~[hugegraph-common-1.5.3.jar:1.5.3.0]
        at com.baidu.hugegraph.HugeGraph.propertyKey(HugeGraph.java:406) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.lambda$queryTask$6(TaskScheduler.java:367) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
2019-02-28 11:32:42 37154 [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the standard OpProcessor.
2019-02-28 11:32:42 37154 [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the standard OpProcessor.
2019-02-28 11:32:42 37155 [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the control OpProcessor.
2019-02-28 11:32:42 37155 [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the control OpProcessor.
2019-02-28 11:32:42 37158 [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the session OpProcessor.
2019-02-28 11:32:42 37158 [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the session OpProcessor.
2019-02-28 11:32:42 37163 [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the traversal OpProcessor.
2019-02-28 11:32:42 37163 [main] [INFO ] org.apache.tinkerpop.gremlin.server.op.OpLoader [] - Adding the traversal OpProcessor.
2019-02-28 11:32:42 37164 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[]
2019-02-28 11:32:42 37164 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[]
2019-02-28 11:32:42 37165 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[session]
2019-02-28 11:32:42 37165 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[session]
2019-02-28 11:32:42 37167 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[control]
2019-02-28 11:32:42 37167 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[control]
2019-02-28 11:32:42 37167 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[traversal]
2019-02-28 11:32:42 37167 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down OpProcessor[traversal]
2019-02-28 11:32:42 37169 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down thread pools.
2019-02-28 11:32:42 37169 [main] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Shutting down thread pools.
2019-02-28 11:32:42 37171 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executing shutdown LifeCycleHook
2019-02-28 11:32:42 37171 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executing shutdown LifeCycleHook
Exception in thread "main" 2019-02-28 11:32:42 37171 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executed once at shutdown of Gremlin Server.
com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
2019-02-28 11:32:42 37171 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executed once at shutdown of Gremlin Server.
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:402)
        at com.baidu.hugegraph.task.TaskScheduler.queryTask(TaskScheduler.java:362)
        at com.baidu.hugegraph.task.TaskScheduler.queryTask(TaskScheduler.java:357)
        at com.baidu.hugegraph.task.TaskScheduler.findTask(TaskScheduler.java:275)
        at com.baidu.hugegraph.task.TaskScheduler.restoreTasks(TaskScheduler.java:153)
        at com.baidu.hugegraph.core.GraphManager.restoreUncompletedTasks(GraphManager.java:213)
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:77)
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:102)
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74)
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81)
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357)
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:422)
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:314)
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:290)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:296)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:119)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:59)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:76)
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58)
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:60)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Undefined property key: '~task_status'
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:400)
        ... 20 more
Caused by: java.lang.IllegalArgumentException: Undefined property key: '~task_status'
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
        at com.baidu.hugegraph.util.E.checkArgument(E.java:56)
        at com.baidu.hugegraph.HugeGraph.propertyKey(HugeGraph.java:406)
        at com.baidu.hugegraph.task.TaskScheduler.lambda$queryTask$6(TaskScheduler.java:367)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-02-28 11:32:44 39375 [gremlin-server-stop] [WARN ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Exception while closing Graph instance [hugegraph]
com.baidu.hugegraph.HugeException: Exception when closing task tx
        at com.baidu.hugegraph.task.TaskManager.closeTaskTx(TaskManager.java:110) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskManager.closeScheduler(TaskManager.java:75) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.close(HugeGraph.java:453) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$null$8(GremlinServer.java:307) ~[gremlin-server-3.2.5.jar:3.2.5]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_181]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$stop$9(GremlinServer.java:304) ~[gremlin-server-3.2.5.jar:3.2.5]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@33802670 rejected from java.util.concurrent.ThreadPoolExecutor@5c622b3b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) ~[?:1.8.0_181]
        at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:238) ~[?:1.8.0_181]
        at com.baidu.hugegraph.task.TaskManager.closeTaskTx(TaskManager.java:108) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        ... 6 more
2019-02-28 11:32:44 39375 [gremlin-server-stop] [WARN ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Exception while closing Graph instance [hugegraph]
com.baidu.hugegraph.HugeException: Exception when closing task tx
        at com.baidu.hugegraph.task.TaskManager.closeTaskTx(TaskManager.java:110) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskManager.closeScheduler(TaskManager.java:75) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.close(HugeGraph.java:453) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$null$8(GremlinServer.java:307) ~[gremlin-server-3.2.5.jar:3.2.5]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_181]
        at org.apache.tinkerpop.gremlin.server.GremlinServer.lambda$stop$9(GremlinServer.java:304) ~[gremlin-server-3.2.5.jar:3.2.5]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@33802670 rejected from java.util.concurrent.ThreadPoolExecutor@5c622b3b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) ~[?:1.8.0_181]
        at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:238) ~[?:1.8.0_181]
        at com.baidu.hugegraph.task.TaskManager.closeTaskTx(TaskManager.java:108) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        ... 6 more
2019-02-28 11:32:44 39376 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Closed Graph instance [hugegraph]
2019-02-28 11:32:44 39376 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Closed Graph instance [hugegraph]
2019-02-28 11:32:44 39378 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Gremlin Server - shutdown complete
2019-02-28 11:32:44 39378 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Gremlin Server - shutdown complete

**Comment by zhoney** [comment]
@baibingzhi 感谢反馈！

schema删除会触发内部的异步任务，异步任务负责实际的删除任务（默认500条记录一个batch），当把vertex.tx_capacity和edge.tx_capacity设置为1时，会导致异步任务出错，状态不可知。

vertex.tx_capacity和edge.tx_capacity是设置单个Transaction中的处于未提交状态的顶点和边的数目的，不应该设置太低。上限可以根据程序需要和服务器内存大小进行设置。

我们会在0.9版本限制vertex.tx_capacity和edge.tx_capacity的最小值，避免出现这种错误。
