### ISSUE TITLE
RocksDB 后端初始化失败

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph#383]
### Expected behavior 期望表现

利用 rocksdb 作为存储后端，配置好 properties 文件后执行 init 失败

### Actual behavior 实际表现

![screenshot 2019-03-08 at 10 23 12](https://user-images.githubusercontent.com/22719158/54003289-a91d3000-418c-11e9-9839-039f046db7c4.png)

### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@suesunss 错误日志里面还有更详细的cause信息能否也提供一下？

**Comment by suesunss** [comment]
Hi @javeme  感谢回复，完整的日志：

```java
2019-03-08 09:13:56 1693  [main] [ERROR] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Failed to open RocksDB '/root/suesun/hugegraph_data/data/hugegraph/schema'
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:112) ~[hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:229) ~[hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:169) [hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:149) [hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:68) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:54) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.openSchemaTransaction(HugeGraph.java:247) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.access$300(HugeGraph.java:81) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.schemaTransaction(HugeGraph.java:721) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.access$000(HugeGraph.java:574) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.schemaTransaction(HugeGraph.java:298) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.info(BackendStoreSystemInfo.java:64) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exist(BackendStoreSystemInfo.java:75) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:98) [hugegraph-dist-0.8.0.jar:?]
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86) [hugegraph-dist-0.8.0.jar:?]
2019-03-08 09:13:56 1708  [main] [ERROR] com.baidu.hugegraph.HugeGraph [] - Failed to open schema transaction
com.baidu.hugegraph.backend.BackendException: Failed to open RocksDB '/root/suesun/hugegraph_data/data/hugegraph/schema'
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:207) ~[hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:149) ~[hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:68) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:54) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.openSchemaTransaction(HugeGraph.java:247) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.access$300(HugeGraph.java:81) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.schemaTransaction(HugeGraph.java:721) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.access$000(HugeGraph.java:574) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.HugeGraph.schemaTransaction(HugeGraph.java:298) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.info(BackendStoreSystemInfo.java:64) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exist(BackendStoreSystemInfo.java:75) [hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:98) [hugegraph-dist-0.8.0.jar:?]
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86) [hugegraph-dist-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:112) ~[hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:229) ~[hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:169) ~[hugegraph-rocksdb-0.8.0.jar:?]
2019-03-08 09:13:56 1732  [task-db-worker-1] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: /root/suesun/hugegraph_data/data/hugegraph/system
2019-03-08 09:13:56 1866  [task-db-worker-1] [ERROR] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Failed to open RocksDB '/root/suesun/hugegraph_data/data/hugegraph/system'
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:112) ~[hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:229) ~[hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:169) ~[hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:149) ~[hugegraph-rocksdb-0.8.0.jar:?]
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.backend.tx.GraphTransaction.<init>(GraphTransaction.java:114) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.<init>(TaskScheduler.java:411) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
        at com.baidu.hugegraph.task.TaskScheduler.tx(TaskScheduler.java:110) ~[hugegraph-core-0.8.0.jar:0.8.0.0]
Exception in thread "main" com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:402)
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:394)
        at com.baidu.hugegraph.task.TaskScheduler.close(TaskScheduler.java:210)
        at com.baidu.hugegraph.task.TaskManager.closeScheduler(TaskManager.java:72)
        at com.baidu.hugegraph.HugeGraph.close(HugeGraph.java:453)
        at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:106)
        at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:86)
Caused by: java.util.concurrent.ExecutionException: com.baidu.hugegraph.backend.BackendException: Failed to open RocksDB '/root/suesun/hugegraph_data/data/hugegraph/system'
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:400)
        ... 6 more
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to open RocksDB '/root/suesun/hugegraph_data/data/hugegraph/system'
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:207)
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:149)
        at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72)
        at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30)
        at com.baidu.hugegraph.backend.tx.GraphTransaction.<init>(GraphTransaction.java:114)
        at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.<init>(TaskScheduler.java:411)
        at com.baidu.hugegraph.task.TaskScheduler.tx(TaskScheduler.java:110)
        at com.baidu.hugegraph.task.TaskScheduler.lambda$close$3(TaskScheduler.java:211)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.rocksdb.RocksDBException: While lock file: /root/suesun/hugegraph_data/data/hugegraph/system/LOCK: Resource temporarily unavailable
        at org.rocksdb.RocksDB.open(Native Method)
        at org.rocksdb.RocksDB.open(RocksDB.java:286)
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:112)
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:229)
        at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:169)

```

**Comment by javeme** [comment]
@suesunss 这个错误看起来像还有进程在使用这个数据目录，请确保server停止状态时执行init-store。

**Comment by suesunss** [comment]
@javeme 谢谢回复。确实是这样，我复现了下，是因为上个进程强杀造成了，请问这种情况下有什么手动解决的办法呢？

**Comment by javeme** [comment]
@suesunss 你那边是通过什么命令关闭进程的？理论上`kill -9`应该是一定能能释放进程资源的（包括端口号）。

**Comment by suesunss** [comment]
@javeme 感谢回复。

我们现在尝试的场景是把 server 放到容器中，上面提到的这种情况是 init 过程中容器突然重启了。

**Comment by hustcrab** [comment]
请问这个问题是如何解决的

**Comment by imbajin** [comment]
> 请问这个问题是如何解决的

一般 rocksdb 初始化就失败, 多半是由于其他进程占用 fd 没有释放, 导致同一个配置下重新读写文件产生冲突, 简单的办法两个:
1. `jps` 确认没有其他 server 进程占用
2. lsof | grep rocksdb 查看有没有进程占用 rocksdb 的文件, 有则 kill 再试试

**Comment by hustcrab** [comment]
这个问题我已经解决了。
原因在于我做的是多图的配置，但是没有将每个图的rocksdb的存储路径指定到不同的路径，导致只有第一张图启动成功，其余图抢占不到rocksdb的文件。
