### ISSUE TITLE
hugeclient连接报错 Failed to do request

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph#4]
使用curl命令和hugestudio连接完全没问题,在idea中使用hugeclient示例代码连接直接报错
连接代码:
HugeClient hugeClient = new HugeClient("http://localhost:8080", "hugegraph");
报错信息
Exception in thread "main" com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:69)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:147)
	at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41)
	at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45)
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:101)
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:84)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:59)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:48)
	at hugegraph.SingleExampleJava.main(SingleExampleJava.java:14)
Caused by: javax.ws.rs.ProcessingException: javax.ws.rs.core.Response$Status$Family.familyOf(I)Ljavax/ws/rs/core/Response$Status$Family;
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:264)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at com.baidu.hugegraph.rest.RestClient.lambda$get$2(RestClient.java:148)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:67)
	... 8 more
Caused by: java.lang.NoSuchMethodError: javax.ws.rs.core.Response$Status$Family.familyOf(I)Ljavax/ws/rs/core/Response$Status$Family;
	at org.glassfish.jersey.message.internal.Statuses$StatusImpl.<init>(Statuses.java:63)
	at org.glassfish.jersey.message.internal.Statuses$StatusImpl.<init>(Statuses.java:54)
	at org.glassfish.jersey.message.internal.Statuses.from(Statuses.java:143)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:397)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
	... 19 more

**Comment by Linary** [comment]
@fisherinbox 你是在一个干净的项目中测试的吗？如果不是，可能是因为你项目中其他依赖也引入了其他版本的 jersey，产生依赖冲突。

**Comment by fisherinbox** [comment]
确实是,我新建了一个干净的项目,成功了,感谢

**Comment by mengquanrun** [comment]
您好，我是一名初学者，请问我可以得到您在运行example时的所有代码么，我在添加依赖时遇到了些困难，想观摩下您的代码，感谢

**Comment by waterflowhan** [comment]
hugeclient 不能和hive-jdbc一起使用？请问下解决方案

**Comment by lomodays207** [comment]
> @fisherinbox 你是在一个干净的项目中测试的吗？如果不是，可能是因为你项目中其他依赖也引入了其他版本的 jersey，产生依赖冲突。

jersey 应该是用啥版本的呢？如果是冲突了要指定版本吗
