### ISSUE TITLE
hugegraph-studio 异常请教

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#409]
请教个问题， 我们的图谱里目前有2500W顶点， 5000W+的边， 目前有个场景， 我们统计了仅包含了2个顶点的子图， 然后将这些顶点调用Restful接口进行了删除， 在删除的过程中， 我们使用了HugeStudio查看一些顶点的基本情况，发现hugegStudio直接报错"fail to do the request."， 查看HugeGraph-Server的日志， 发现如下异常：
请教下， 这个异常是怎么触发的呢？ 我们应该在日常的图谱功能开发、运维过程中注意哪些细节， 非常感谢！！！

2019-03-26 18:43:42 99932219 [gremlin-server-exec-11] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Error encountered evaluating script: g.V("XXXXXXXXX").count()
org.apache.tinkerpop.gremlin.process.traversal.util.TraversalInterruptedException: null
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:142) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:239) ~[gremlin-server-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:320) ~[gremlin-groovy-3.2.5.jar:3.2.5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.8.0.jar:0.31.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by javeme** [comment]
@hklmuaqmn 这个错误是因为超时了，一般是删除的数据太多，比如删除的顶点太多，或被删除的顶点拥有很多边。请使用异步任务来执行长时间的操作。
