### ISSUE TITLE
请问，HugeGraph支持 Spark入库吗？ 

### ISSUE THREAD

**Issue by ChenBinaBGitHub** [hugegraph/hugegraph#419]
### Expected behavior 期望表现
{type something here...}
rdd.foreachPartition{
graph= HugeFactory.open(propertyToBaseConf(loadLocalProperty(hugeProperties)))
}
希望可以在每个partition内 打开 graph，进行多线程入库
### Actual behavior 实际表现
{type something here...}
报错如下：
 Lost task 1.0 in stage 0.0 (TID 1, 172.25.21.5, executor 0): com.baidu.hugegraph.HugeException: Failed to init backend store
	at com.baidu.hugegraph.HugeGraph.<init>(HugeGraph.java:140)
	at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:44)
	at com.suntek.ai.graphdb.data.SparkLoadToGraph$$anonfun$main$1.apply(SparkLoadToGraph.scala:36)
	at com.suntek.ai.graphdb.data.SparkLoadToGraph$$anonfun$main$1.apply(SparkLoadToGraph.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2019-03-29 02:10:31 20096[task-result-getter-1] [WARN ] org.apache.spark.scheduler.TaskSetManager  - Lost task 0.0 in stage 0.0 (TID 0, 172.25.21.5, executor 0): java.lang.RuntimeException: LockGroup 'hugegraph_test_il_delete' already exists!
	at com.baidu.hugegraph.concurrent.LockManager.create(LockManager.java:45)
	at com.baidu.hugegraph.util.LockUtil.init(LockUtil.java:60)
	at com.baidu.hugegraph.HugeGraph.<init>(HugeGraph.java:133)
	at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:44)
	at com.suntek.ai.graphdb.data.SparkLoadToGraph$$anonfun$main$1.apply(SparkLoadToGraph.scala:36)
	at com.suntek.ai.graphdb.data.SparkLoadToGraph$$anonfun$main$1.apply(SparkLoadToGraph.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

'hugegraph_test 表示graph的名称
### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by ChenBinaBGitHub** [comment]
程序入库时：在 foreachPartition 内部 无法获取到属性名称 
Not found key 'NAME' from entry 0x0101: [cardinality="SINGLE", data_type="TEXT", name="name", properties=[], status="CREATED", user_data={}]

DAGScheduler: ResultStage 0 (foreachPartition at SparkLoadToGraph.scala:32) failed in 42.621 s due to Job aborted due to stage failure: Task 1 in stage 0.0 failed 4 times, most recent failure: Lost task 1.3 in stage 0.0 (TID 6, 172.25.21.5, executor 0): java.lang.IllegalStateException: Not found key 'NAME' from entry 0x0101: [cardinality="SINGLE", data_type="TEXT", name="name", properties=[], status="CREATED", user_data={}]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at com.baidu.hugegraph.util.E.checkState(E.java:68)
	at com.baidu.hugegraph.backend.serializer.BinarySerializer$SchemaSerializer.column(BinarySerializer.java:1143)
	at com.baidu.hugegraph.backend.serializer.BinarySerializer$SchemaSerializer.readString(BinarySerializer.java:1057)
	at com.baidu.hugegraph.backend.serializer.BinarySerializer$SchemaSerializer.readPropertyKey(BinarySerializer.java:994)
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.readPropertyKey(BinarySerializer.java:882)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.deserialize(SchemaTransaction.java:362)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getAllSchema(SchemaTransaction.java:320)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getAllSchema(CachedSchemaTransaction.java:239)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getPropertyKeys(SchemaTransaction.java:92)
	at com.baidu.hugegraph.schema.SchemaManager.getPropertyKeys(SchemaManager.java:90)
	at com.suntek.ai.graphdb.data.SparkLoadToGraph$$anonfun$main$1.apply(SparkLoadToGraph.scala:40)
	at com.suntek.ai.graphdb.data.SparkLoadToGraph$$anonfun$main$1.apply(SparkLoadToGraph.scala:32)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
19/03/30 03:52:56 INFO DAGScheduler: Job 0 failed: foreachPartition at SparkLoadToGraph.scala:32, took 42.805954 s
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 4 times, most recent failure: Lost task 1.3 in stage 0.0 (TID 6, 172.25.21.5, executor 0): java.lang.IllegalStateException: Not found key 'NAME' from entry 0x0101: [cardinality="SINGLE", data_type="TEXT", name="name", properties=[], status="CREATED", user_data={}]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at com.baidu.hugegraph.util.E.checkState(E.java:68)
	at com.baidu.hugegraph.backend.serializer.BinarySerializer$SchemaSerializer.column(BinarySerializer.java:1143)
	at com.baidu.hugegraph.backend.serializer.BinarySerializer$SchemaSerializer.readString(BinarySerializer.java:1057)
	at com.baidu.hugegraph.backend.serializer.BinarySerializer$SchemaSerializer.readPropertyKey(BinarySerializer.java:994)
	at com.baidu.hugegraph.backend.serializer.BinarySerializer.readPropertyKey(BinarySerializer.java:882)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.deserialize(SchemaTransaction.java:362)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getAllSchema(SchemaTransaction.java:320)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getAllSchema(CachedSchemaTransaction.java:239)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getPropertyKeys(SchemaTransaction.java:92)
	at com.baidu.hugegraph.schema.SchemaManager.getPropertyKeys(SchemaManager.java:90)
	at com.suntek.ai.graphdb.data.SparkLoadToGraph$$anonfun$main$1.apply(SparkLoadToGraph.scala:40)
	at com.suntek.ai.graphdb.data.SparkLoadToGraph$$anonfun$main$1.apply(SparkLoadToGraph.scala:32)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
