### ISSUE TITLE
求教 查询超时

### ISSUE THREAD

**Issue by baibingzhi** [hugegraph/hugegraph#422]
数据结构：
    顶点：  身份证    手机号    设备    IP
    边： 身份证--手机号    身份证--设备    身份证--IP    设备--IP
数据现状：
    顶点边总量 1亿左右
    身份证数量 关联的 手机号数量   1-5 : 1-5 （1:1为主）
    身份证数量 关联的 设备数量   1-5 : 1-5（1:1为主）
    身份证数量 关联的 IP数量   1-3000 : 1-5 (1:1为主，可能有3000个身份证在一个IP上出现)
    设备数量 关联的 IP数量   1-3000 : 1-5 (1:1为主，可能有3000个设备在一个IP上出现)

hugegraph版本： 8.0  （16核16G）
后端： cassandra*3 （16核16G * 3）

需求：给定身份证，查询5度关联之内的所有顶点数量
gremlin: g.V(...).emit().repeat(both().simplePath()).until(__.not(both().simplePath()).or().loops().is(5)).toSet().size()

时不时出现查询超时的情况，具体报错见下面。

求教：
1. 不改变需求可以从哪些方面优化？
2. 需求有什么改进建议？

非常感谢！！

[ERROR]-[http-nio-8766-exec-7]-[com.hcfc.knowledgegraph.common.config.logAspect.HcfcExceptionHandler.baseResponseDtoErrorHandler:32]-Failed to do request
com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:69)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:115)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:79)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:74)
	at com.baidu.hugegraph.api.gremlin.GremlinAPI.post(GremlinAPI.java:41)
	at com.baidu.hugegraph.driver.GremlinManager.execute(GremlinManager.java:50)
	at com.baidu.hugegraph.api.gremlin.GremlinRequest$Builder.execute(GremlinRequest.java:55)
	at com.hcfc.knowledgegraph.common.config.graph.GraphExecuteService.execute(GraphExecuteService.java:25)
	at com.hcfc.knowledgegraph.blackgrid.run.service.GraphEntityQueryService.countRelated(GraphEntityQueryService.java:80)
	at com.hcfc.knowledgegraph.blackgrid.run.service.GraphEntityQueryService.bomCorrelationParam(GraphEntityQueryService.java:334)
	at com.hcfc.knowledgegraph.blackgrid.run.service.GraphEntityQueryService.queryForBom(GraphEntityQueryService.java:214)
	at com.hcfc.knowledgegraph.blackgrid.run.service.GraphEntityQueryService$$FastClassBySpringCGLIB$$3f2f504.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.hcfc.knowledgegraph.blackgrid.run.service.GraphEntityQueryService$$EnhancerBySpringCGLIB$$cbd6d176.queryForBom(<generated>)
	at com.hcfc.knowledgegraph.blackgrid.run.controller.GraphController.queryBom(GraphController.java:49)
	at com.hcfc.knowledgegraph.blackgrid.run.controller.GraphController$$FastClassBySpringCGLIB$$96f15e99.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.hcfc.knowledgegraph.blackgrid.run.controller.GraphController$$EnhancerBySpringCGLIB$$9b63071d.queryBom(<generated>)
	at sun.reflect.GeneratedMethodAccessor483.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
	at com.baidu.hugegraph.rest.RestClient.lambda$post$0(RestClient.java:116)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:67)
	... 93 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:399)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
	... 105 common frames omitted

**Comment by zhoney** [comment]
```
时不时出现超时
```

是说明有的点关联度比较大，会超时，对于关联度一般的就不会超时。

```
1. 不改变需求可以从哪些方面优化
```

查询的数据多，肯定是要花费更多的时间，同时也一定会占用较多内存的。如果不改变方式的情况下，可以增大server的内存和增加client的超时时间。

```
2. 需求有什么改进建议？
```

方案建议：
1. 可以通过限制一下每个点的边的数目限制规模，比如`both().limit(x)`
2. 查询以一个点为中心的周围的全部点，可以使用RESTful API K-neighbor，可以参考：https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html

> 这两种方式都有可能会丢失一部分数据，但可以规避超级点带来的内存耗尽和请求超时问题

**Comment by zhangshenghang** [comment]
> ```
> 时不时出现超时
> ```
> 
> 是说明有的点关联度比较大，会超时，对于关联度一般的就不会超时。
> 
> ```
> 1. 不改变需求可以从哪些方面优化
> ```
> 
> 查询的数据多，肯定是要花费更多的时间，同时也一定会占用较多内存的。如果不改变方式的情况下，可以增大server的内存和增加client的超时时间。
> 
> ```
> 2. 需求有什么改进建议？
> ```
> 
> 方案建议：
> 
> 1. 可以通过限制一下每个点的边的数目限制规模，比如`both().limit(x)`
> 2. 查询以一个点为中心的周围的全部点，可以使用RESTful API K-neighbor，可以参考：https://hugegraph.github.io/hugegraph-doc/clients/restful-api/traverser.html
> 
> > 这两种方式都有可能会丢失一部分数据，但可以规避超级点带来的内存耗尽和请求超时问题

你好，我看K-neighbor可以查询范围内所有相关点，我想把边的信息也获取通过RESTful api可以获取到吗？

**Comment by javeme** [comment]
@baibingzhi 可以参考下 https://github.com/hugegraph/hugegraph/issues/924
