### ISSUE TITLE
hugegraph-tools-1.2.0  restore时，报"Graph 'hugegraph' does not exist"

### ISSUE THREAD

**Issue by zhouyongliang** [hugegraph/hugegraph#423]
我自己创建的store名称是rocksdbgraph2  ，执行backup和dump没有异常，当我restore时发生了错误。
我试过./hugegraph --graph rocksdbgraph2 --url http://55.29.1.1:8080  graph-mode-set --graph-name rocksdbgraph2 -m RESTORING，没有用。

详细的信息：
`./hugegraph --graph rocksdbgraph2  --url http://55.29.1.1:8080  restore -d /home/hugegraph/backup/rocksdbhugegraph/backup -t all`
报错：
Exception in thread "main" class javax.ws.rs.NotFoundException: Graph 'hugegraph' does not exist
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:177)
	at com.baidu.hugegraph.api.graphs.GraphsAPI.mode(GraphsAPI.java:65)
	at com.baidu.hugegraph.driver.GraphsManager.mode(GraphsManager.java:50)
	at com.baidu.hugegraph.manager.GraphsManager.mode(GraphsManager.java:55)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:121)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:280)

**Comment by zhoney** [comment]
@zhouyongliang 感谢反馈！

问题已经解决，请参考: https://github.com/hugegraph/hugegraph-tools/issues/27

后续如果有问题，请在对应的组件创建issue，比如hugegraph-tools的问题在https://github.com/hugegraph/hugegraph-tools/issues 进行提交，谢谢！
