### ISSUE TITLE
only used for secondary index, relation must be EQ, but got 'GT'

### ISSUE THREAD

**Issue by CrazyBeeline** [hugegraph/hugegraph#424]
### Expected behavior 
期望表现支持边的范围搜索

### Actual behavior 实际表现

Caused by: java.lang.IllegalStateException: Method userpropValues(List<String>) only used for secondary index, relation must be EQ, but got 'GT'
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at com.baidu.hugegraph.util.E.checkState(E.java:68)
	at com.baidu.hugegraph.backend.query.ConditionQuery.userpropValues(ConditionQuery.java:290)
	at com.baidu.hugegraph.backend.query.ConditionQuery.userpropValuesString(ConditionQuery.java:309)
	at com.baidu.hugegraph.backend.tx.GraphTransaction.optimizeQuery(GraphTransaction.java:971)
	at com.baidu.hugegraph.backend.tx.GraphTransaction.query(GraphTransaction.java:317)
	at com.baidu.hugegraph.backend.tx.GraphTransaction.queryEdgesFromBackend(GraphTransaction.java:637)
	at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.queryEdgesFromBackend(CachedGraphTransaction.java:118)
	at com.baidu.hugegraph.backend.tx.GraphTransaction.queryEdges(GraphTransaction.java:599)
	at com.baidu.hugegraph.HugeGraph.edges(HugeGraph.java:391)
	at com.baidu.hugegraph.traversal.optimize.HugeVertexStep.edges(HugeVertexStep.java:153)
	at com.baidu.hugegraph.traversal.optimize.HugeVertexStep.flatMap(HugeVertexStep.java:80)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:49)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:48)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62)
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85)
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382)
	at org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:239)
	at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:320)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
 schema.vertexLabel("person").properties("name", "person_id").primaryKeys("person_id").nullableKeys("name").ifNotExist().create();

 schema.vertexLabel("event").properties("event_id").primaryKeys("event_id").ifNotExist().create();

 schema.edgeLabel("person_train_travel").sourceLabel("person").targetLabel("event").properties("detail_time").multiTimes().sortKeys("detail_time").ifNotExist().create();
        schema.edgeLabel("person_air_travel").sourceLabel("person").targetLabel("event").properties("detail_time").multiTimes().sortKeys("detail_time").ifNotExist().create();

 schema.indexLabel("person_train_travel_range_index").onE("person_train_travel").by("detail_time").range().ifNotExist().create();
        schema.indexLabel("person_air_travel_range_index").onE("person_air_travel").by("detail_time").secondary().ifNotExist().create();

插入数据
    Vertex person = graph.addVertex(T.label, "person", "name", "hahah", "person_id", "320281196706308746");
        Vertex event_1 = graph.addVertex(T.label, "event", "event_id", "1F5C3C51CE204B609918BEDACCA86991");
        Vertex event_2 = graph.addVertex(T.label, "event", "event_id", "8428E7BC680B46F3ADE6B8ED31929EB6");

        person.addEdge("person_train_travel", event_1, "detail_time",1471826914 );
        person.addEdge("person_air_travel", event_2, "detail_time",1505925089 )

查询："g.V().hasLabel('person').has('person_id','320281196706308746').outE('person_air_travel').has('detail_time',gt(1505925089)).values('detail_time')"
### Specifications of environment 环境信息
- hugegraph version: {like v0.8.0}
- operating system: {like ubunut 14.04, 80 CPUs, 128G RAM}
- hugegraph backend: {like hbase-cdh 1.2.0, cluster with 1nodes, 1x 4TB SATAdisk each node}

**Comment by javeme** [comment]
@CrazyBeeline 我这边尝试复现但最终没有复现这个问题，请问下你那边使用的版本是多少？需要注意的是这个功能需要0.9版本才支持（0.9目前还未发布，所以需要使用master最新的代码才具备该功能）

另外发现person_air_travel_range_index使用的是secondary索引。

**Comment by CrazyBeeline** [comment]
使用range索引，也会报这个错误
目前看来是版本的问题
我目前使用的是0.8.0版本

**Comment by CrazyBeeline** [comment]
目前的版本我怎么实现person_air_travel 的大于一定时间的记录

**Comment by javeme** [comment]
> 目前的版本我怎么实现person_air_travel 的大于一定时间的记录

@CrazyBeeline 0.8版本可以使用：
`g.E().hasLabel('person_air_travel').has('detail_time',gt(1505925089)).where(outV().hasLabel('person').has('person_id','320281196706308746')).values('detail_time')`
