### ISSUE TITLE
 RocksDB : Table 'hugegraph+si' is not opened

### ISSUE THREAD

**Issue by ChenBinaBGitHub** [hugegraph/hugegraph#483]
hugegraph0.9.2版本：

Opening RocksDB with data path: /home/kngraph/hugegraph/data/hugegraph/graph
2019-04-24 20:12:08 1102  [main] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Failed to open RocksDB '/home/kngraph/hugegraph/data/hugegraph/graph' with database 'hugegraph', try to init CF later
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Table 'hugegraph+si' is not opened
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.cf(RocksDBStdSessions.java:225)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.access$000(RocksDBStdSessions.java:63)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.scan(RocksDBStdSessions.java:586)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBTable.queryByPrefix(RocksDBTable.java:173)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBTable.query(RocksDBTable.java:129)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.query(RocksDBStore.java:318)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.query(AbstractTransaction.java:104)
	at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.queryByName(SchemaIndexTransaction.java:96)
	at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.query(SchemaIndexTransaction.java:75)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getSchema(SchemaTransaction.java:307)
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getSchema(CachedSchemaTransaction.java:195)
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getPropertyKey(SchemaTransaction.java:125)
	at com.baidu.hugegraph.schema.builder.PropertyKeyBuilder.create(PropertyKeyBuilder.java:81)
	at com.baidu.hugegraph.schema.builder.PropertyKeyBuilder.create(PropertyKeyBuilder.java:40)
	at com.suntek.ai.graphdb.data.FactoryLoadToGraphTest$.createSchema(FactoryLoadToGraphTest.scala:52)
	at com.suntek.ai.graphdb.data.FactoryLoadToGraphTest$.main(FactoryLoadToGraphTest.scala:34)
	at com.suntek.ai.graphdb.data.FactoryLoadToGraphTest.main(FactoryLoadToGraphTest.scala)

**Comment by javeme** [comment]
@ChenBinaBGitHub 如果是直接基于hugegraph-server代码进行开发的话，可参考hugegraph-example中的示例流程，这个错误可能是漏掉了一些步骤。

**Comment by ChenBinaBGitHub** [comment]
com.baidu.hugegraph.example.ExampleUtil 类中，方法 public static HugeGraph loadGraph(boolean needClear, boolean needProfile) 
  open hugegraph.     

HugeGraph graph = HugeFactory.open(conf);

        if (needClear) {
            graph.clearBackend();
        }
        graph.initBackend();


自己的代码：

     graph = HugeFactory.open(hugeProperties)
     graph.initBackend()



说明：
1. open 方法与 实例一样
2. 在gremlin中可以打开
3.后端存储为HBase时，可以正常入库
4.引用的jar hugegraph-loader/lib 和 hugegraph/lib

猜测：
  是不是缺少jar 之类的，

**Comment by ChenBinaBGitHub** [comment]
可以帮忙解答这个问题吗？？
