### ISSUE TITLE
服务出现Unknown HK2 failure detected

### ISSUE THREAD

**Issue by aiyongyyy** [hugegraph/hugegraph#490]
使用Cassandra做后端，使用api导入数据后是正常的，查询了一段时间后，出现了Unknown HK2 failure detected这个问题。
详细日志如下：
Apr 29, 2019 2:09:13 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 1
java.lang.IllegalStateException: Please wait for the server to initialize
 at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
 at com.baidu.hugegraph.util.E.checkState(E.java:68)
 at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory.provide(ApplicationConfig.java:120)
 at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory.provide(ApplicationConfig.java:90)
 at org.jvnet.hk2.internal.FactoryCreator.create(FactoryCreator.java:153)
 at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
 at org.glassfish.jersey.process.internal.RequestScope.findOrCreate(RequestScope.java:162)
 at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
 at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:774)
 at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:786)
 at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111)
 at com.baidu.hugegraph.api.filter.AuthenticationFilter.authenticate(AuthenticationFilter.java:65)
 at com.baidu.hugegraph.api.filter.AuthenticationFilter.filter(AuthenticationFilter.java:59)
 at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
 at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
 at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
 at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318)
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
 at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
 at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
 at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
 at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
 at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
 at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
 at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
 at java.lang.Thread.run(Thread.java:748)

问一下，这个问题好解决吗，谢谢了

**Comment by aiyongyyy** [comment]
后来发现可能是内存太小的缘故，换了大内存机器后，比较稳定了

**Comment by javeme** [comment]
> WARNING: The following warnings have been detected: WARNING: Unknown HK2 failure detected:
> MultiException stack 1 of 1
> java.lang.IllegalStateException: **Please wait for the server to initialize**

@aiyongyyy 这个日志本身是一个警告，如果服务能正常启动则可以忽略。如果服务无法启动或者服务启动慢，可能是恢复未完成任务时卡住了。

**Comment by javeme** [comment]
Similar warning messages: #125 and #421
