### ISSUE TITLE
graphdb-benchmarks测试有大量WARN日志

### ISSUE THREAD

**Issue by wenzhenghu** [hugegraph/hugegraph#547]
### Expected behavior 期望表现
不应有频繁的调用栈日志

### Actual behavior 实际表现
2019-06-03 17:02:14 279704 [metrics-csv-reporter-1-thread-1] [WARN ] com.codahale.metrics.CsvReporter [] - Error writing to hugegraphcore.eu.socialsensor.query.nextEdge
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_211]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_211]
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.CsvReporter.reportTimer(CsvReporter.java:173) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:166) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117) [metrics-core-3.1.0.jar:3.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
2019-06-03 17:02:14 279705 [metrics-csv-reporter-1-thread-1] [WARN ] com.codahale.metrics.CsvReporter [] - Error writing to hugegraphcore.eu.socialsensor.query.nextVertex
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_211]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_211]
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.CsvReporter.reportTimer(CsvReporter.java:173) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:166) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117) [metrics-core-3.1.0.jar:3.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
2019-06-03 17:02:14 279705 [metrics-csv-reporter-1-thread-1] [WARN ] com.codahale.metrics.CsvReporter [] - Error writing to hugegraphcore.eu.socialsensor.query.shortestPath
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_211]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_211]
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.CsvReporter.reportTimer(CsvReporter.java:173) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:166) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162) [metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117) [metrics-core-3.1.0.jar:3.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

想问下，为什么会提示“No such file or directory”，这个错误是什么引起的，如何解决？

### Steps to reproduce the problem 复现步骤
1. https://github.com/hugegraph/graphdb-benchmarks下载源码包，编译通过
2. 配置为core模式
3. 下载https://github.com/hugegraph/hugegraph/issues/64所述数据集，创建data目录并解压数据
4. 使用run.sh跑测试（删掉了cassandra的语句）。

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.9.2}
- operating system: {debian9.7}
- hugegraph backend: {myrocks}

**Comment by zhoney** [comment]
@wenzhenghu 感谢反馈！

大量的warning日志是由于Metrics信息的存储目录`./metrics`不存在导致，已在`run.sh`脚本中增加判断和修复机制[graphdb-benchmark/PR 6](https://github.com/hugegraph/graphdb-benchmarks/pull/6/files)

也可在`graphdb-benchmark`的根目录下手动建立目录`metrics`解决

**Comment by wenzhenghu** [comment]
@zhoney 手动创建metrics，问题解决。3xs
