### ISSUE TITLE
hugegraph运行1天，报错

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#556]
### Expected behavior 期望表现
hugegraph能稳定运行
### Actual behavior 实际表现
在测试环境运行1天，报错
```
org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Broken pipe
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_101]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[?:1.8.0_101]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[?:1.8.0_101]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_101]
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_101]
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3728) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2509) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2438) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.select(MysqlSessions.java:339) ~[hugegraph-mysql-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.store.mysql.MysqlTable.query(MysqlTable.java:270) ~[hugegraph-mysql-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.query(MysqlStore.java:227) ~[hugegraph-mysql-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.query(AbstractTransaction.java:104) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.doIndexQueryOnce(GraphIndexTransaction.java:472) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.doIndexQuery(GraphIndexTransaction.java:454) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.doJointIndex(GraphIndexTransaction.java:381) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.doIndexQueries(GraphIndexTransaction.java:364) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.queryByUserprop(GraphIndexTransaction.java:333) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.queryIndex(GraphIndexTransaction.java:260) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.indexQuery(GraphTransaction.java:1045) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.query(GraphTransaction.java:330) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.queryVerticesFromBackend(GraphTransaction.java:508) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.queryVerticesFromBackend(CachedGraphTransaction.java:76) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.queryVertices(GraphTransaction.java:477) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.HugeGraph.vertices(HugeGraph.java:382) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.vertices(HugeGraphStep.java:94) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.lambda$new$0(HugeGraphStep.java:66) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:139) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:48) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:239) ~[gremlin-server-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:320) ~[gremlin-groovy-3.2.5.jar:3.2.5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.9.2.jar:0.38.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

### Specifications of environment 环境信息
- hugegraph version: v0.9.2
- operating system: CentOS release 6.6 (Final), 16  Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, 32G RAM
- hugegraph backend: mysql 5.7.21

**Comment by javeme** [comment]
@306495389li 这个错误看起来是MySQL连接中断了，请确认MySQL服务本身是否正常？若正常的话重新请求一次是否正常？

**Comment by 306495389li** [comment]
重新请求2到3次就正常的，但是现在有个问题，就是一段时间不请求，再次请求，前1到2次会失败，报这个错，再掉就成功了，这个要怎么解决

**Comment by Linary** [comment]
duplicate #561
