### ISSUE TITLE
导入数据失败

### ISSUE THREAD

**Issue by hklmuaqmn** [hugegraph/hugegraph#58]
### Expected behavior 期望表现
期望hugegraph-loader导入数据正常

### Actual behavior 实际表现
实际导入数据报错

### Steps to reproduce the problem 复现步骤
下载 hugegraph-loader 0.7解压后运行（hugegraph-server运行正常，也实现执行过init-store）按照官方文档
运行的命令：bin/hugegraph-loader -g hugegraph -f example/struct.json -s example/schema.groovy
报错：
Exception in thread "main" null: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> /versions</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.13</h3></body></html>
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:63)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:150)
	at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41)
	at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45)
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:101)
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:84)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:59)
	at com.baidu.hugegraph.loader.executor.HugeClients.newHugeClient(HugeClients.java:43)
	at com.baidu.hugegraph.loader.executor.HugeClients.get(HugeClients.java:33)
	at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:151)
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:104)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:68)
root@personalserver:~/hugegraph-loader-0.7.0#

**Comment by Linary** [comment]
你本地是不是有起别的服务吗？你用浏览器访问`http://127.0.0.1:8080/versions`试试看是什么样的响应。

**Comment by hklmuaqmn** [comment]
非常感谢您的回复， 我搞错了， 改过端口， 没有加-p参数， 现在构造数据正在导入
