### ISSUE TITLE
模糊搜索时报错，求大神指点

### ISSUE THREAD

**Issue by 1315861791** [hugegraph/hugegraph#582]
![image](https://user-images.githubusercontent.com/24642133/59812559-ff2f7100-9340-11e9-97a0-cfad34a35b38.png)

**Comment by javeme** [comment]
@1315861791 建议在每个has后面均加上limit(10)

**Comment by 1315861791** [comment]
谢谢，我试试

**Comment by 1315861791** [comment]
@javeme 再请教个问题：我在统计每一类label的数据量时，当库里数据多了也会报这个错，请问有什么解决办法吗？
g.V().groupCount('a').by(label).cap('a')
g.E().groupCount('a').by(label).cap('a')

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/59841643-56583480-9387-11e9-8ffc-49f519d50a0c.png)
shao少量数据时没毛病，执行速度也很快。但数据量多了就不好使了。

**Comment by 1315861791** [comment]
@javeme 查询数据量的时候报错了。groupBY的时候报同样的错（g.V().label().groupCount()），请问怎么解决啦
![image](https://user-images.githubusercontent.com/24642133/59892083-45043c00-940a-11e9-9fe3-44196d62f370.png)


![image](https://user-images.githubusercontent.com/24642133/59892100-59483900-940a-11e9-9f8d-62d64cc89efb.png)

**Comment by 1315861791** [comment]
@javeme 我需要统计每个label的数据量，刚开始测的时候数据量少，一切正常，当数据量多了以后就这样了。求助！

**Comment by 1315861791** [comment]
请问这个错误是不是跟我后台存储库使用hbase有关？如果限制不让全表扫描的话点和边的数量统计该怎么实现啦？
2019-06-21 09:48:48 58831003 [gremlin-server-exec-2] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Too many records(must <=800000) for the query: Query for VERTEX page=
null, offset=0, limit=9223372036854775807, order by {}
com.baidu.hugegraph.exception.LimitExceedException: Too many records(must <=800000) for the query: Query for VERTEX page=null, offset=0, limit=9223372036854775807, order by {}
        at com.baidu.hugegraph.backend.query.Query.checkCapacity(Query.java:218) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
        at com.baidu.hugegraph.backend.store.BackendEntryIterator.checkCapacity(BackendEntryIterator.java:104) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
        at com.baidu.hugegraph.backend.store.BackendEntryIterator.next(BackendEntryIterator.java:64) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
        at com.baidu.hugegraph.backend.store.BackendEntryIterator.next(BackendEntryIterator.java:32) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
        at com.baidu.hugegraph.iterator.MapperIterator.fetch(MapperIterator.java:43) ~[hugegraph-common-1.6.0.jar:1.6.0.0]
        at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:41) ~[hugegraph-common-1.6.0.jar:1.6.0.0]
        at com.baidu.hugegraph.iterator.FilterIterator.fetch(FilterIterator.java:42) ~[hugegraph-common-1.6.0.jar:1.6.0.0]
        at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:41) ~[hugegraph-common-1.6.0.jar:1.6.0.0]
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:131) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:36) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.hasNext(ExpandableStepIterator.java:42) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processAllStarts(ReducingBarrierStep.java:83) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processNextStart(ReducingBarrierStep.java:113) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:239) ~[gremlin-server-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36) ~[gremlin-core-3.2.5.jar:3.2.5]
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:320) ~[gremlin-groovy-3.2.5.jar:3.2.5]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
        at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.9.2.jar:0.38.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by javeme** [comment]
@1315861791 建议使用[gremlin-schedule](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-tools.html)

**Comment by 1315861791** [comment]
请问可以用java client中的API来解决吗？
