### ISSUE TITLE
用mysql做后端数据库导入信息错误

### ISSUE THREAD

**Issue by jackchen-c** [hugegraph/hugegraph#591]
Exception in thread "main" com.baidu.hugegraph.rest.ClientException: Failed to do request
        at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:92)
        at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:170)
        at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41)
        at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45)
        at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:120)
        at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:106)
        at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:70)
        at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:58)
        at com.baidu.hugegraph.loader.util.HugeClientWrapper.newHugeClient(HugeClientWrapper.java:45)
        at com.baidu.hugegraph.loader.util.HugeClientWrapper.get(HugeClientWrapper.java:33)
        at com.baidu.hugegraph.loader.HugeGraphLoader.createSchema(HugeGraphLoader.java:141)
        at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:107)
        at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:67)
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: 拒绝连接 (Connection refused)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
        at com.baidu.hugegraph.rest.RestClient.lambda$get$2(RestClient.java:171)
        at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:90)
        ... 12 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: 拒绝连接 (Connection refused)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
        ... 24 more
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
        ... 33 more

**Comment by javeme** [comment]
@jackchen-c 请确保服务已正常启动，`Connection refused` 表明可能服务没有成功启动，看看服务日志中是否有错误信息。
