### ISSUE TITLE
当id策略PRIMARY_KEY时，id字段如何设置为空

### ISSUE THREAD

**Issue by Jason-zzzzz** [hugegraph/hugegraph#593]
运行报错：
Vertices has been imported: Exception in thread "main" java.lang.IllegalStateException: The id field must be empty or null when id strategy is PRIMARY_KEY for vertex label 'person'
        at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
        at com.baidu.hugegraph.util.E.checkState(E.java:68)
        at com.baidu.hugegraph.loader.builder.VertexBuilder.checkIdField(VertexBuilder.java:119)
        at com.baidu.hugegraph.loader.builder.VertexBuilder.<init>(VertexBuilder.java:43)
        at com.baidu.hugegraph.loader.HugeGraphLoader.loadVertices(HugeGraphLoader.java:161)
        at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:111)
        at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:67)
 struct.json文件
 "vertices": [
    {
      "label": "person",
      "input": {
        "type": "jdbc",
        "driver": "com.mysql.cj.jdbc.Driver",
        "url": "jdbc:mysql://192.168.131.128:3306",
        "database": "example",
        "table": "person",
        "username": "root",
        "password": "root",
        "batch_size": 500
      },
      "id": "id",
      "null_values": ["NULL"]
    },

**Comment by Linary** [comment]
麻烦按照如下步骤重试一次：
1. 停掉 HugeGraphServer 服务
2. 进入 mysql client，清理数据库，使用 drop database 命令
3. 回到hugegraph目录，执行init-store.sh
4. 启动 HugeGraphServer 服务
5. 修改loader中的schema文件，确保没有vertexlabel中含有id属性
6. 删除struct.json文件中的`"id": "id"`行
7. 执行导入
