### ISSUE TITLE
hugegraph-loader从mysql中导入

### ISSUE THREAD

**Issue by jackchen-c** [hugegraph/hugegraph#621]
Caused by: class com.baidu.hugegraph.backend.BackendException: Failed to query [Query for PROPERTY_KEY page=null, offset=0, limit=9223372036854775807, orde {} where id in [] and [NAME == b_type]]
        at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
        at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:69)
        at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:142)
        at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:102)
        at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:97)
        at com.baidu.hugegraph.api.schema.PropertyKeyAPI.create(PropertyKeyAPI.java:43)
        at com.baidu.hugegraph.driver.SchemaManager.addPropertyKey(SchemaManager.java:79)
        at com.baidu.hugegraph.structure.schema.PropertyKey$BuilderImpl.create(PropertyKey.java:116)
        at com.baidu.hugegraph.structure.schema.PropertyKey$BuilderImpl.create(PropertyKey.java:99)
        ... 15 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 5,453,187 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds a

**Comment by Linary** [comment]
@jackchen-c 这个是mysql连接超时断开了。你的导入任务是卡住了很长时间吗？
