### ISSUE TITLE
hugeGraph-server组件设置用户和密码后，重启图时报错，但实际图已经成功启动的问题

### ISSUE THREAD

**Issue by lixiaobiao** [hugegraph/hugegraph#622]
#### test version: 
hugeGraph-server is 0.9.2

### Expected behavior 期望表现
执行 ./start-hugegraph.sh
Starting HugeGraphServer...
Connecting to HugeGraphServer (http://ip:8086/graphs)......OK

### Actual behavior 实际表现
修改配置增加图密码后
执行./start-hugegraph.sh 
Starting HugeGraphServer...
Connecting to HugeGraphServer (http://ip:8087/graphs)................The operation timed out when attempting to connect to http://ip:8087/graphs
See /home/bd/lixiaobiao/hugegraph-0.9.2/hugegraph-0.9.2-test2/logs/hugegraph-server.log for HugeGraphServer log output.

这种情况下，其实图已经启动了，但是仍有错出现！

查看日志报错：
```
2019-07-25 19:33:12 7716  [main] [INFO ] com.baidu.hugegraph.server.RestServer [] - RestServer started
2019-07-25 19:36:07 182348 [metrics-csv-reporter-thread-1] [WARN ] com.codahale.metrics.CsvReporter [] - Error writing to com.baidu.hugegraph.backend.cache.Cache.edge-hugegraph.capacity
java.io.FileNotFoundException: /tmp/gremlin-server-metrics.csv/com.baidu.hugegraph.backend.cache.Cache.edge-hugegraph.capacity.csv (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_191]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_191]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_191]
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:242) [metrics-core-3.0.2.jar:3.0.2]
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234) [metrics-core-3.0.2.jar:3.0.2]
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150) [metrics-core-3.0.2.jar:3.0.2]
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116) [metrics-core-3.0.2.jar:3.0.2]
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87) [metrics-core-3.0.2.jar:3.0.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]


```

**Comment by javeme** [comment]
@lixiaobiao 可能是启动时间较长导致超时了，能正常访问说明启动成功。
另外，有一个警告，是因为目录没有写权限`/tmp/gremlin-server-metrics.csv/`，可以增加一下启动用户的权限。

**Comment by lixiaobiao** [comment]
👌好的
