### ISSUE TITLE
0.9.2版本启动报错 Failed to update/query TaskStore

### ISSUE THREAD

**Issue by yuzhanggdut** [hugegraph/hugegraph#639]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
```
Exception in thread "main" com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:397)
        at com.baidu.hugegraph.task.TaskScheduler.queryTask(TaskScheduler.java:357)
        at com.baidu.hugegraph.task.TaskScheduler.queryTask(TaskScheduler.java:352)
        at com.baidu.hugegraph.task.TaskScheduler.findTask(TaskScheduler.java:270)
        at com.baidu.hugegraph.task.TaskScheduler.restoreTasks(TaskScheduler.java:143)
        at com.baidu.hugegraph.core.GraphManager.restoreUncompletedTasks(GraphManager.java:210)
        at com.baidu.hugegraph.core.GraphManager.<init>(GraphManager.java:74)
        at com.baidu.hugegraph.server.ApplicationConfig$GraphManagerFactory$1.onEvent(ApplicationConfig.java:106)
        at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74)
        at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onStartup(MonitoringContainerListener.java:81)
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:1180)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:357)
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:422)
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:314)
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:290)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:60)
        at com.baidu.hugegraph.server.RestServer.start(RestServer.java:89)
        at com.baidu.hugegraph.dist.HugeRestServer.start(HugeRestServer.java:58)
        at com.baidu.hugegraph.dist.HugeGraphServer.main(HugeGraphServer.java:60)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Undefined vertex label: '~task'
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:395)2019-08-13 07:58:43 20947 [gremlin-server-stop] [INFO ] org.apache.tinkerpop.gremlin.server.GremlinServer [] - Executing shutdown LifeCycleHook

        ... 18 more
Caused by: java.lang.IllegalArgumentException: Undefined vertex label: '~task'
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
        at com.baidu.hugegraph.util.E.checkArgument(E.java:56)
        at com.baidu.hugegraph.HugeGraph.vertexLabel(HugeGraph.java:425)
        at com.baidu.hugegraph.task.TaskScheduler.lambda$queryTask$6(TaskScheduler.java:359)


```
### Steps to reproduce the problem 复现步骤
1. {step 1}studio查询，cassandra down
2. {step 2}重启cassandra
3. {step 3}重启hugegraph server

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 10 billion}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.9.2}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.2, cluster with 4 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@yuzhanggdut 是在什么情况下发生的呢？请提供一下复现的步骤

**Comment by yuzhanggdut** [comment]
> @yuzhanggdut 是在什么情况下发生的呢？请提供一下复现的步骤

cassandra卡死后，关闭hg server，然后kill cassandra并重启，然后重启hg server出错。

**Comment by yuzhanggdut** [comment]
您好，错误复现步骤如下：

1.studio查询时导致cassandra shut down(机器存储原因导致的)；
2.重启cassandra；
3.重启hugegraph server；


------------------------------------------------------------------
发件人：Jermy Li <notifications@github.com>
发送时间：2019年8月19日(星期一) 17:41
收件人：hugegraph/hugegraph <hugegraph@noreply.github.com>
抄　送：yuzhang <yuzhanggdut@aliyun.com>; Mention <mention@noreply.github.com>
主　题：Re: [hugegraph/hugegraph] 0.9.2版本启动报错 Failed to update/query TaskStore (#639)

@yuzhanggdut 是在什么情况下发生的呢？请提供一下复现的步骤

**Comment by javeme** [comment]
@yuzhanggdut 看起来是Cassandra的缺少了部分数据导致的，请检查一下有没有什么原因导致Cassandra数据丢失的？

**Comment by yuzhanggdut** [comment]
丢失数据应该没有，报错之前只进行了studio的查询操作，看日志报Cassandra timeout read query at consistency Local_ONE (1 responses were required but only 0 replica responded)。
然后关闭server重启就出现了Failed to update/query TaskStore的提示。
------------------------------------------------------------------
发件人：Jermy Li <notifications@github.com>
发送时间：2019年9月2日(星期一) 11:12
收件人：hugegraph/hugegraph <hugegraph@noreply.github.com>
抄　送：yuzhang <yuzhanggdut@aliyun.com>; Mention <mention@noreply.github.com>
主　题：Re: [hugegraph/hugegraph] 0.9.2版本启动报错 Failed to update/query TaskStore (#639)

@yuzhanggdut 看起来是Cassandra的缺少了部分数据导致的，请检查一下有没有什么原因导致Cassandra数据丢失的？
