### ISSUE TITLE
内存做后端的hugegraph导数据到mysql做后端

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph#644]
### Expected behavior 期望表现
运维人员安装错误，使用了内存做了后端，现在要把数据迁到mysql的后端

### Actual behavior 实际表现
bin/hugegraph graph-mode-set -m RESTORING
bin/hugegraph restore -t all -d data
现在使用工具导出数据拿到mysql做后端的导入报错
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Graph 'hugegraph' start restore in mode 'RESTORING'!
Property key restore started
Exception in thread "main" class com.baidu.hugegraph.exception.ExistedException: The PROPERTY_KEY id '1' has existed
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44)
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:69)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:142)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:102)
	at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:97)
	at com.baidu.hugegraph.api.schema.PropertyKeyAPI.create(PropertyKeyAPI.java:43)
	at com.baidu.hugegraph.driver.SchemaManager.addPropertyKey(SchemaManager.java:79)
	at com.baidu.hugegraph.manager.RestoreManager.lambda$restorePropertyKeys$6(RestoreManager.java:178)
	at com.baidu.hugegraph.manager.BackupRestoreBaseManager.read(BackupRestoreBaseManager.java:121)
	at com.baidu.hugegraph.manager.RestoreManager.restore(RestoreManager.java:244)
	at com.baidu.hugegraph.manager.RestoreManager.restorePropertyKeys(RestoreManager.java:183)
	at com.baidu.hugegraph.manager.RestoreManager.restore(RestoreManager.java:72)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.execute(HugeGraphCommand.java:149)
	at com.baidu.hugegraph.cmd.HugeGraphCommand.main(HugeGraphCommand.java:305)

### Specifications of environment 环境信息
- hugegraph version: 0.9.2
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
类似问题：https://github.com/hugegraph/hugegraph/issues/370

**Comment by zhoney** [comment]
@306495389li 根据报错，以MySQL为后端的HugeGraph中已经有id为“1”的PropertyKey了。例如，已经存在PropertyKey name，且id为1，那么在Restoring模式下，就无法再恢复id为1的PropertyKey。如果仍希望恢复，可以使用Merging模式，参见[backup restore](https://hugegraph.github.io/hugegraph-doc/guides/backup-restore.html)
