### ISSUE TITLE
hugegraph loader jdbc方式导入，table表数据为空时，无法导入

### ISSUE THREAD

**Issue by 0xqq** [hugegraph/hugegraph#646]
### Expected behavior 期望表现
{type something here...}

### Actual behavior 实际表现
{type something here...}
 执行 /bdp/hg/hugegraph-loader-0.9.0/bin/hugegraph-loader -g friend -f /bdp/dataset/friend/jdbc-struct.json -s /bdp/dataset/friend/schema.groovy --check-vertex false  --token  xxx时，表空时，发生以下错误
--------------------------------------------
ERROR: Failed to load due to Reached end of table
Exception in thread "main" java.util.NoSuchElementException: Reached end of table
        at com.baidu.hugegraph.loader.reader.jdbc.JDBCReader.next(JDBCReader.java:82)
        at com.baidu.hugegraph.loader.reader.jdbc.JDBCReader.next(JDBCReader.java:33)
        at com.baidu.hugegraph.loader.builder.ElementBuilder.next(ElementBuilder.java:106)
        at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:182)
        at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:150)
        at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:94)
        at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:67)
### Steps to reproduce the problem 复现步骤
1. {step 1}
2. {step 2}
3. {step 3}

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by Linary** [comment]
https://github.com/hugegraph/hugegraph-loader/pull/90 修复此问题
