### ISSUE TITLE
HugeGraph Server 启动异常

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph#657]
### Expected behavior 期望表现
 正常启动一个具有10图的 hugegraph server。

### Actual behavior 实际表现
启动报异常：

```java
2019-08-22 19:53:19 728   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/suesunss_hellograph_g1.properties
2019-08-22 19:53:20 834   [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'rocksdb' for graph 'suesunss_hellograph_g1'
2019-08-22 19:53:20 892   [main] [INFO ] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Opening RocksDB with data path: /data01/graphproject/hugegraph_data/data/suesunss_hellograph_g1/schema
2019-08-22 19:53:20 1113  [main] [ERROR] com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore [] - Failed to open RocksDB '/data01/graphproject/hugegraph_data/data/suesunss_hellograph_g1/schema'
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:122) ~[hugegraph-rocksdb-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:241) ~[hugegraph-rocksdb-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:181) [hugegraph-rocksdb-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:172) [hugegraph-rocksdb-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:155) [hugegraph-rocksdb-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:68) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:53) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.HugeGraph.openSchemaTransaction(HugeGraph.java:250) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.HugeGraph.access$300(HugeGraph.java:80) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.getOrNewTransaction(HugeGraph.java:730) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.schemaTransaction(HugeGraph.java:713) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.access$000(HugeGraph.java:588) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.HugeGraph.schemaTransaction(HugeGraph.java:301) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.info(BackendStoreSystemInfo.java:66) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exist(BackendStoreSystemInfo.java:78) [hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:99) [hugegraph-dist-0.9.2.jar:?]
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87) [hugegraph-dist-0.9.2.jar:?]
2019-08-22 19:53:20 1119  [main] [ERROR] com.baidu.hugegraph.HugeGraph [] - Failed to open schema transaction
com.baidu.hugegraph.backend.BackendException: Failed to open RocksDB '/data01/graphproject/hugegraph_data/data/suesunss_hellograph_g1/schema'
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:219) ~[hugegraph-rocksdb-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:172) ~[hugegraph-rocksdb-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:155) ~[hugegraph-rocksdb-0.9.2.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.<init>(SchemaTransaction.java:68) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.<init>(CachedSchemaTransaction.java:53) ~[hugegraph-core-0.9.2.jar:0.9.2.0]
Exception in thread "main" com.baidu.hugegraph.HugeException: Failed to update/query TaskStore
	at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:397)
	at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:389)
	at com.baidu.hugegraph.task.TaskScheduler.close(TaskScheduler.java:205)
	at com.baidu.hugegraph.task.TaskManager.closeScheduler(TaskManager.java:73)
	at com.baidu.hugegraph.HugeGraph.close(HugeGraph.java:460)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:107)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87)
Caused by: java.util.concurrent.ExecutionException: com.baidu.hugegraph.backend.BackendException: Failed to open RocksDB '/data01/graphproject/hugegraph_data/data/suesunss_hellograph_g1/system'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.baidu.hugegraph.task.TaskScheduler.call(TaskScheduler.java:395)
	... 6 more
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to open RocksDB '/data01/graphproject/hugegraph_data/data/suesunss_hellograph_g1/system'
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:219)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:172)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:155)
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.<init>(AbstractTransaction.java:72)
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.<init>(IndexableTransaction.java:30)
	at com.baidu.hugegraph.backend.tx.GraphTransaction.<init>(GraphTransaction.java:119)
	at com.baidu.hugegraph.task.TaskScheduler$TaskTransaction.<init>(TaskScheduler.java:406)
	at com.baidu.hugegraph.task.TaskScheduler.tx(TaskScheduler.java:111)
	at com.baidu.hugegraph.task.TaskScheduler.lambda$close$3(TaskScheduler.java:206)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.rocksdb.RocksDBException: no meta-nextfile entry in descriptor
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:286)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions.<init>(RocksDBStdSessions.java:122)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.openSessionPool(RocksDBStore.java:241)
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.open(RocksDBStore.java:181)
	... 13 more
```

### Status of loaded data 数据状态
之前已经导入过数据，停止 server 后重新启动

#### Vertex/Edge summary 数据量
- loaded vertices amount: 10 million
- loaded edges amount: 100 million

### Specifications of environment 环境信息
- hugegraph version:  0.9.2
- operating system: 16 Cores CPU, 32G, ubuntu 18.04
- hugegraph backend: RocksDB (compatible with hg 0.9.2)

**Comment by javeme** [comment]
@suesunss 是否是因为使用了共享存储，导致数据混乱了呢？

**Comment by suesunss** [comment]
@javeme 没有使用共享存储，我们有场景把 hg server 放在 docker 里，cpu/memory 没有控制好，造成 query 把容器压爆直接重启了，这种情况 RocksDB 数据脏了。
