### ISSUE TITLE
loader解析json失败

### ISSUE THREAD

**Issue by oushu1liwenhui1** [hugegraph/hugegraph#660]
```
Exception in thread "main" com.baidu.hugegraph.rest.SerializeException: Failed to deserialize json
	at com.baidu.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:59)
	at com.baidu.hugegraph.loader.source.GraphSource.of(GraphSource.java:49)
	at com.baidu.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:74)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "mapping" (class com.baidu.hugegraph.loader.source.VertexSource), not marked as ignorable (8 known properties: "value_mapping", "ignored", "label", "field_mapping", "input", "null_values", "id", "selected"])
 at [Source: {
  "vertices": [
    {
      "label": "人物",
      "input": {
        "type": "file",
        "path": "test/personinfo.csv",
        "format": "CSV",
        "header": ["1", "2", "3", "4", "5", "6", "7"],
        "charset": "UTF-8"
      },
      "mapping": {
        "1": "身份证号",
        "2": "电话号码",
        "3": "姓名",
	"4": "爱好",
        "5": "犯罪类型",
	"6": "犯罪时间",
	"7": "涉毒"
      },
      "null_values": ["NULL", "null", ""]
    }
  ],
  "edges": [
    {
      "label": "致电",
      "source": ["sourceid"],
      "target": ["targetid"],
      "input": {
        "type": "file",
        "path": "test/phoneinfo.json",
        "format": "JSON"
      },
      "mapping": {
        "sourceid": "身份证号",
        "targetid": "身份证号"
      }
    }
  ]
}
; line: 22, column: 6] (through reference chain: com.baidu.hugegraph.loader.source.GraphSource["vertices"]->java.util.ArrayList[0]->com.baidu.hugegraph.loader.source.VertexSource["mapping"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:817)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:958)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1278)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:452)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3564)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2580)
	at com.baidu.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:57)
	... 3 more
```

你好，请问这是什么原因？没改任何代码，就是重编译了一下，就报以上错误。而以前编译好的可以正常运行。检查了jackson的版本是和以前一样的。

**Comment by oushu1liwenhui1** [comment]
解决了，mapping改成field_mapping

**Comment by Linary** [comment]
最新的代码（还没发布版本v0.10）将 `mapping` 改为了 `field_mapping`
