### ISSUE TITLE
运行hugegraph-client中SingleExample报错

### ISSUE THREAD

**Issue by Mr-jackchen** [hugegraph/hugegraph#684]
### Expected behavior 期望表现
运行SingleExample成功

### Actual behavior 实际表现
运行测试用例报错：
```
"C:\Program Files\Java\jdk1.8.0_201\bin\java.exe" "-javaagent:D:\develop\IntelliJ IDEA 2019.1\lib\idea_rt.jar=54808:D:\develop\IntelliJ IDEA 2019.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_201\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_201\jre\lib\rt.jar;D:\git_download\hugegraph-client\target\classes;D:\m2\repo\com\baidu\hugegraph\hugegraph-common\1.6.11\hugegraph-common-1.6.11.jar;D:\m2\repo\junit\junit\4.12\junit-4.12.jar;D:\m2\repo\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;D:\m2\repo\org\apache\logging\log4j\log4j-api\2.8.2\log4j-api-2.8.2.jar;D:\m2\repo\org\apache\logging\log4j\log4j-core\2.8.2\log4j-core-2.8.2.jar;D:\m2\repo\org\apache\logging\log4j\log4j-slf4j-impl\2.8.2\log4j-slf4j-impl-2.8.2.jar;D:\m2\repo\org\slf4j\slf4j-api\1.7.24\slf4j-api-1.7.24.jar;D:\m2\repo\org\glassfish\javax.json\1.0\javax.json-1.0.jar;D:\m2\repo\commons-configuration\commons-configuration\1.10\commons-configuration-1.10.jar;D:\m2\repo\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\m2\repo\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;D:\m2\repo\org\apache\commons\commons-configuration2\2.1.1\commons-configuration2-2.1.1.jar;D:\m2\repo\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;D:\m2\repo\commons-io\commons-io\2.4\commons-io-2.4.jar;D:\m2\repo\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;D:\m2\repo\commons-codec\commons-codec\1.11\commons-codec-1.11.jar;D:\m2\repo\com\google\guava\guava\19.0\guava-19.0.jar;D:\m2\repo\com\google\code\findbugs\jsr305\3.0.1\jsr305-3.0.1.jar;D:\m2\repo\org\javassist\javassist\3.21.0-GA\javassist-3.21.0-GA.jar;D:\m2\repo\org\glassfish\jersey\core\jersey-client\2.22\jersey-client-2.22.jar;D:\m2\repo\org\glassfish\hk2\hk2-api\2.4.0-b31\hk2-api-2.4.0-b31.jar;D:\m2\repo\org\glassfish\hk2\hk2-utils\2.4.0-b31\hk2-utils-2.4.0-b31.jar;D:\m2\repo\org\glassfish\hk2\external\aopalliance-repackaged\2.4.0-b31\aopalliance-repackaged-2.4.0-b31.jar;D:\m2\repo\org\glassfish\hk2\external\javax.inject\2.4.0-b31\javax.inject-2.4.0-b31.jar;D:\m2\repo\org\glassfish\hk2\hk2-locator\2.4.0-b31\hk2-locator-2.4.0-b31.jar;D:\m2\repo\org\glassfish\jersey\media\jersey-media-json-jackson\2.22\jersey-media-json-jackson-2.22.jar;D:\m2\repo\org\glassfish\jersey\ext\jersey-entity-filtering\2.22\jersey-entity-filtering-2.22.jar;D:\m2\repo\com\fasterxml\jackson\jaxrs\jackson-jaxrs-base\2.5.4\jackson-jaxrs-base-2.5.4.jar;D:\m2\repo\com\fasterxml\jackson\core\jackson-core\2.5.4\jackson-core-2.5.4.jar;D:\m2\repo\com\fasterxml\jackson\core\jackson-databind\2.5.4\jackson-databind-2.5.4.jar;D:\m2\repo\com\fasterxml\jackson\jaxrs\jackson-jaxrs-json-provider\2.5.4\jackson-jaxrs-json-provider-2.5.4.jar;D:\m2\repo\com\fasterxml\jackson\module\jackson-module-jaxb-annotations\2.5.4\jackson-module-jaxb-annotations-2.5.4.jar;D:\m2\repo\com\fasterxml\jackson\core\jackson-annotations\2.5.4\jackson-annotations-2.5.4.jar;D:\m2\repo\org\glassfish\jersey\connectors\jersey-apache-connector\2.22\jersey-apache-connector-2.22.jar;D:\m2\repo\org\apache\httpcomponents\httpclient\4.5\httpclient-4.5.jar;D:\m2\repo\org\apache\httpcomponents\httpcore\4.4.1\httpcore-4.4.1.jar;D:\m2\repo\org\glassfish\jersey\inject\jersey-hk2\2.27\jersey-hk2-2.27.jar;D:\m2\repo\org\glassfish\jersey\containers\jersey-container-servlet\2.22\jersey-container-servlet-2.22.jar;D:\m2\repo\org\glassfish\jersey\containers\jersey-container-servlet-core\2.22\jersey-container-servlet-core-2.22.jar;D:\m2\repo\org\glassfish\jersey\core\jersey-common\2.22\jersey-common-2.22.jar;D:\m2\repo\javax\annotation\javax.annotation-api\1.2\javax.annotation-api-1.2.jar;D:\m2\repo\org\glassfish\jersey\bundles\repackaged\jersey-guava\2.22\jersey-guava-2.22.jar;D:\m2\repo\org\glassfish\hk2\osgi-resource-locator\1.0.1\osgi-resource-locator-1.0.1.jar;D:\m2\repo\org\glassfish\jersey\core\jersey-server\2.22\jersey-server-2.22.jar;D:\m2\repo\org\glassfish\jersey\media\jersey-media-jaxb\2.22\jersey-media-jaxb-2.22.jar;D:\m2\repo\javax\validation\validation-api\1.1.0.Final\validation-api-1.1.0.Final.jar;D:\m2\repo\javax\ws\rs\javax.ws.rs-api\2.0.1\javax.ws.rs-api-2.0.1.jar" com.baidu.hugegraph.example.SingleExample
Exception in thread "main" com.baidu.hugegraph.rest.ClientException: Failed to do request
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:128)
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:190)
	at com.baidu.hugegraph.api.version.VersionAPI.get(VersionAPI.java:41)
	at com.baidu.hugegraph.driver.VersionManager.getApiVersion(VersionManager.java:45)
	at com.baidu.hugegraph.driver.HugeClient.checkServerApiVersion(HugeClient.java:122)
	at com.baidu.hugegraph.driver.HugeClient.initManagers(HugeClient.java:108)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:72)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:60)
	at com.baidu.hugegraph.driver.HugeClient.<init>(HugeClient.java:56)
	at com.baidu.hugegraph.example.SingleExample.main(SingleExample.java:41)
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectTimeoutException: Connect to 192.168.0.113:8182 [/192.168.0.113] failed: connect timed out
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at com.baidu.hugegraph.rest.RestClient.lambda$get$3(RestClient.java:191)
	at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:126)
	... 9 more
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to 192.168.0.113:8182 [/192.168.0.113] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:143)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 21 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 30 more
```
应该是外部IP不能访问，尝试过将修改rest-server.properties restserver.url=http://0.0.0.0:8080 ，重启后仍然运行报同样的错，请问下这是什么原因？怎么解决啊？

### Specifications of environment 环境信息
- hugegraph version: {like v0.7.4}
- operating system: {like centos 7.4, 32 CPUs, 64G RAM}
- hugegraph backend: {like cassandra 3.10, cluster with 20 nodes, 3 x 1TB HDD disk each node}

**Comment by javeme** [comment]
@Mr-jackchen 请检查一下Gremlin Server的host、port是否能访问到：
```
host | 127.0.0.1 | The host or ip of Gremlin Server.
port | 8182      | The listening port of Gremlin Server.
```

https://hugegraph.github.io/hugegraph-doc/config/config-option.html

**Comment by Mr-jackchen** [comment]
> @Mr-jackchen 请检查一下Gremlin Server的host、port是否能访问到：
> 
> ```
> host | 127.0.0.1 | The host or ip of Gremlin Server.
> port | 8182      | The listening port of Gremlin Server.
> ```
> 
> https://hugegraph.github.io/hugegraph-doc/config/config-option.html

**Comment by Mr-jackchen** [comment]
@javeme 我是外部ip通过hugegraph-client访问失败的，
我是这么配置的
![image](https://user-images.githubusercontent.com/19922845/64671655-b4cf1380-d49b-11e9-9d4d-87f7397ec3a3.png)
![image](https://user-images.githubusercontent.com/19922845/64671680-c31d2f80-d49b-11e9-94a4-33cb2da18c25.png)

**Comment by Mr-jackchen** [comment]
@javeme ip和port本地是可以通的，但是我的电脑连就通不了。
![image](https://user-images.githubusercontent.com/19922845/64672289-9ec25280-d49d-11e9-9f02-e0df9c7d4650.png)

**Comment by Mr-jackchen** [comment]
@javeme 地址是192.168.0.113，端口是8182

**Comment by javeme** [comment]
@Mr-jackchen 从你的配置来看，应该是连8080端口才对。

**Comment by Mr-jackchen** [comment]
@javeme 8080端口我也试了，连不了
