### ISSUE TITLE
Invalid column family specified in write batch

### ISSUE THREAD

**Issue by javeme** [hugegraph/hugegraph#697]
Accidental error when truncating rocksdb and running api tests at the same time:
```
2019-09-26 14:08:23 608650 [grizzly-http-server-5] [ERROR] com.baidu.hugegraph.server.RestServer [] - Failed to commit
com.baidu.hugegraph.backend.BackendException: Exception in backend
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:513) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:1) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.commitTx(RocksDBStore.java:400) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:247) ~[classes/:?]
	at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.commitMutation2Backend(CachedGraphTransaction.java:209) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:168) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:364) ~[classes/:?]
	at com.baidu.hugegraph.HugeGraph$Txs.commit(HugeGraph.java:805) ~[classes/:?]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.doCommit(HugeGraph.java:692) ~[classes/:?]
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104) ~[gremlin-core-3.4.3.jar:3.4.3]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.commit(HugeGraph.java:658) ~[classes/:?]
	at com.baidu.hugegraph.api.API.commit(API.java:94) [classes/:?]
	at com.baidu.hugegraph.api.graph.BatchAPI.commit(BatchAPI.java:75) [classes/:?]
	at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:112) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.22.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.22.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.22.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.22.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.22.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.22.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.1.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.28.jar:2.3.28]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593) [grizzly-framework-2.3.28.jar:2.3.28]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573) [grizzly-framework-2.3.28.jar:2.3.28]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.rocksdb.RocksDBException: Invalid column family specified in write batch
	at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-5.14.2.jar:?]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[rocksdbjni-5.14.2.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:510) ~[classes/:?]
	... 39 more
```

The second time:
```
2019-09-26 20:29:15 114776 [task-worker-1] [WARN ] com.baidu.hugegraph.task.HugeTask [] - An exception occurred when running task: 7
java.lang.AssertionError: null
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.scan(RocksDBStdSessions.java:651) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBTable.queryByPrefix(RocksDBTable.java:173) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBTable.query(RocksDBTable.java:129) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.query(RocksDBStore.java:320) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.query(AbstractTransaction.java:105) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.doIndexQueryOnce(GraphIndexTransaction.java:513) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphIndexTransaction.lambda$doIndexQuery$0(GraphIndexTransaction.java:499) ~[classes/:?]
	at com.baidu.hugegraph.backend.page.IdHolder.fetchNext(IdHolder.java:98) ~[classes/:?]
	at com.baidu.hugegraph.backend.page.QueryList$IndexQuery.iterator(QueryList.java:250) ~[classes/:?]
	at com.baidu.hugegraph.backend.page.QueryList.fetchNext(QueryList.java:124) ~[classes/:?]
	at com.baidu.hugegraph.backend.page.PageEntryIterator.fetch(PageEntryIterator.java:79) ~[classes/:?]
	at com.baidu.hugegraph.backend.page.PageEntryIterator.hasNext(PageEntryIterator.java:66) ~[classes/:?]
	at com.baidu.hugegraph.iterator.MapperIterator.fetch(MapperIterator.java:42) ~[hugegraph-common-1.6.14.jar:1.6.14.0]
	at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:41) ~[hugegraph-common-1.6.14.jar:1.6.14.0]
	at com.baidu.hugegraph.iterator.FilterIterator.fetch(FilterIterator.java:42) ~[hugegraph-common-1.6.14.jar:1.6.14.0]
	at com.baidu.hugegraph.iterator.WrappedIterator.hasNext(WrappedIterator.java:41) ~[hugegraph-common-1.6.14.jar:1.6.14.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.traverseByLabel(GraphTransaction.java:1504) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.traverseVerticesByLabel(GraphTransaction.java:1474) ~[classes/:?]
	at com.baidu.hugegraph.job.schema.RebuildIndexCallable.rebuildIndex(RebuildIndexCallable.java:126) ~[classes/:?]
	at com.baidu.hugegraph.job.schema.RebuildIndexCallable.rebuildIndex(RebuildIndexCallable.java:68) ~[classes/:?]
	at com.baidu.hugegraph.job.schema.RebuildIndexCallable.execute(RebuildIndexCallable.java:53) ~[classes/:?]
	at com.baidu.hugegraph.job.Job.call(Job.java:40) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at com.baidu.hugegraph.task.HugeTask.run(HugeTask.java:203) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
2019-09-26 20:29:16 116322 [task-worker-3] [WARN ] com.baidu.hugegraph.task.HugeTask [] - An exception occurred when running task: 8
com.baidu.hugegraph.backend.BackendException: Exception in backend
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:513) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:1) ~[classes/:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.commitTx(RocksDBStore.java:400) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:247) ~[classes/:?]
	at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.commitMutation2Backend(CachedGraphTransaction.java:209) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:168) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:364) ~[classes/:?]
	at com.baidu.hugegraph.HugeGraph$Txs.commit(HugeGraph.java:805) ~[classes/:?]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.doCommit(HugeGraph.java:692) ~[classes/:?]
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104) ~[gremlin-core-3.4.3.jar:3.4.3]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.commit(HugeGraph.java:658) ~[classes/:?]
	at com.baidu.hugegraph.job.schema.IndexLabelRemoveCallable.removeIndexLabel(IndexLabelRemoveCallable.java:64) ~[classes/:?]
	at com.baidu.hugegraph.job.schema.IndexLabelRemoveCallable.execute(IndexLabelRemoveCallable.java:39) ~[classes/:?]
	at com.baidu.hugegraph.job.Job.call(Job.java:40) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at com.baidu.hugegraph.task.HugeTask.run(HugeTask.java:203) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.rocksdb.RocksDBException: Invalid column family specified in write batch
	at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-5.14.2.jar:?]
	at org.rocksdb.RocksDB.write(RocksDB.java:602) ~[rocksdbjni-5.14.2.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:510) ~[classes/:?]
	... 21 more
```

**Comment by javeme** [comment]
reference https://github.com/facebook/rocksdb/issues/592

**Comment by javeme** [comment]
TODO Fix:
May avoid race condition by CF synchronize: wait CF finished then drop it, like use ColumnFamilyHandle Wrapper:
```
class CFWrapper implements Closeable {
  ColumnFamilyHandle handle;
  AtomicInteger refs;

  void open() {
    refs.incrementAndGet();
  }

  void close() {
    if (refs.decrementAndGet() == 0) {
      handle.close();
    }
  }
}

CFWrapper cf(String cf) {
  wrapper = this.cfs.get(cf);
  wrapper.open();
  return wrapper;
}

try (CFWrapper cf = cf("xx")) {
}
```
