### ISSUE TITLE
初始化mysql数据库连接失败

### ISSUE THREAD

**Issue by EnzoLiang** [hugegraph/hugegraph#758]
### Expected behavior 期望表现
{希望成功连接数据库}

### Actual behavior 实际表现
{后端存储选择mysql，进行初始化时提示连接数据库失败}

### Steps to reproduce the problem 报错截图

(https://user-images.githubusercontent.com/27463147/69526368-feac9d80-0fa4-11ea-8366-ea3ba34eecb7.jpg)

#### Vertex/Edge summary 数据量
- loaded vertices amount: {like 10 million}
- loaded edges amount: {like 20 million}
- loaded time: {like 200s}

#### Vertex/Edge example 数据示例
{type something here...}

#### Schema(VertexLabel, EdgeLabel, IndexLabel) 元数据结构
{type something here...}

### Specifications of environment 环境信息
- hugegraph version: {v0.10.4}
- operating system: {lUbuntu16.04 }
- hugegraph backend: {like mysql 5.7}

**Comment by zhoney** [comment]
@EnzoLiang 我在本地用MySQL 5.7没有复现问题。你使用的MySQL的版本麻烦提供一下。

**Comment by EnzoLiang** [comment]
@zhoney 我本地用的5.7.18也没问题，但是用服务器的5.7.20就出现我说的问题了，而且即使用本地的mysql初始化成功了，后期用浏览器编写的schema会报错，存不到数据库里

**Comment by zhoney** [comment]
@EnzoLiang 本地的可以尝试下`bin/start-hugegraph.sh -s false`，看能否解决问题。

服务器上的5.7.20，在init-store的时候出错，每次都可以复现吗？麻烦提供一下详细的复现步骤。

**Comment by EnzoLiang** [comment]
@zhoney 
Steps to reproduce the problem 复现步骤
1：部署hugegraph-0.10.4，修改hugegraph.properties配置文件为如下内容：
![image](https://user-images.githubusercontent.com/27463147/69837347-365b6400-1289-11ea-850f-7187498431e9.png)
2. bin/init-store.sh进行初始化，报以下错误：
![image](https://user-images.githubusercontent.com/27463147/69837437-c4cfe580-1289-11ea-9ecf-931805659945.png)

**Comment by zhoney** [comment]
@EnzoLiang 感谢回复！

> 本地的可以尝试下bin/start-hugegraph.sh -s false，看能否解决问题。

一、你本地MySQL关闭gremlin敏感操作检查，是否可以正常工作？


二、关于服务器上的MySQL，我验证了两个版本：

    - 5.7.28
    - 5.6.19

都没能复现你的问题。

三、请按以下步骤排查：
1. 上述错误是否每次都可以复现？
2. 如果每次必现，尝试以下步骤检查：
```
If you get a SQLException: Connection refused or Connection timed out or a MySQL specific CommunicationsException: 
Communications link failure, then it means that the DB isn't reachable at all. This can have one or more of the following causes:

IP address or hostname in JDBC URL is wrong.
Hostname in JDBC URL is not recognized by local DNS server.
Port number is missing or wrong in JDBC URL.
DB server is down.
DB server doesn't accept TCP/IP connections.
DB server has run out of connections.
Something in between Java and DB is blocking connections, e.g. a firewall or proxy.

To solve the one or the other, follow the following advices:

Verify and test them with ping.
Refresh DNS or use IP address in JDBC URL instead.
Verify it based on my.cnf of MySQL DB.
Start the DB.
Verify if mysqld is started without the --skip-networking option.
Restart the DB and fix your code accordingly that it closes connections in finally.
Disable firewall and/or configure firewall/proxy to allow/forward the port.
```
3. 尝试cherry-pick #765 后，打包重试，如果问题仍存在，会打印出更为详细的失败原因，可以贴出来进一步讨论

**Comment by javeme** [comment]
Similar error with gremlin(rocksdb): `graph.addVertex(T.label,'person','name','marko','age',29,'city','Beijing')`
```
2019-12-01 23:09:57 18819 [gremlin-server-exec-2] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and com.baidu.hugegraph.structure.HugeElement$ElementKeys
java.lang.ClassNotFoundException: com.baidu.hugegraph.structure.HugeElement$ElementKeys
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
	at com.baidu.hugegraph.structure.HugeElement.classifyKeys(HugeElement.java:300) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.constructVertex(GraphTransaction.java:448) ~[classes/:?]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.addVertex(GraphTransaction.java:415) ~[classes/:?]
	at com.baidu.hugegraph.HugeGraph.addVertex(HugeGraph.java:380) ~[classes/:?]
```

**Comment by zhoney** [comment]
grenlin执行`hugegraph.clearBackend();hugegraph.initBackend()`

```
2019-12-03 15:41:21 124263 [gremlin-server-exec-2] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Keyspace hugegraph doesn't exist
com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Keyspace hugegraph doesn't exist
        at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:37) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:27) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68) ~[cassandra-driver-core-3.2.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraSessionPool$Session.execute(CassandraSessionPool.java:194) ~[hugegraph-cassandra-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraTable.createTable(CassandraTable.java:546) ~[hugegraph-cassandra-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraTables$Edge.init(CassandraTables.java:322) ~[hugegraph-cassandra-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraTables$Edge.init(CassandraTables.java:282) ~[hugegraph-cassandra-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.initTables(CassandraStore.java:488) ~[hugegraph-cassandra-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.cassandra.CassandraStore.init(CassandraStore.java:277) ~[hugegraph-cassandra-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.init(AbstractBackendStoreProvider.java:104) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
        at com.baidu.hugegraph.HugeGraph.initBackend(HugeGraph.java:207) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
        at com.baidu.hugegraph.GremlinGraph$initBackend$1.call(Unknown Source) ~[?:?]
        at Script6.run(Script6.groovy:1) ~[?:?]
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:674) ~[gremlin-groovy-3.4.3.jar:3.4.3]
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:376) ~[gremlin-groovy-3.4.3.jar:3.4.3]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[?:1.8.0_181]
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266) ~[gremlin-groovy-3.4.3.jar:3.4.3]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.11.0.jar:0.49.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by javeme** [comment]
相关问题（memory backend）：#776

**Comment by zhoney** [comment]
```
2019-12-05 12:01:04 36489 [gremlin-server-exec-2] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /Users/zhangyi51/Desktop/v0.10.4/temp/hugegraph-0.11.0/org/postgresql/translation/messages.properties
2019-12-05 12:01:04 36490 [gremlin-server-exec-2] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /Users/zhangyi51/Desktop/v0.10.4/temp/hugegraph-0.11.0/org/postgresql/translation/messages_zh.properties
2019-12-05 12:01:04 36495 [gremlin-server-exec-2] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /Users/zhangyi51/Desktop/v0.10.4/temp/hugegraph-0.11.0/org/postgresql/translation/messages_zh_Hans.properties
2019-12-05 12:01:04 36502 [gremlin-server-exec-2] [WARN ] com.baidu.hugegraph.security.HugeSecurityManager [] - SecurityException: Not allowed to read file via Gremlin: /Users/zhangyi51/Desktop/v0.10.4/temp/hugegraph-0.11.0/org/postgresql/translation/messages_zh_Hans_CN.properties
2019-12-05 12:01:04 36505 [gremlin-server-exec-2] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and FATAL: terminating connection due to administrator command
org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264) ~[postgresql-42.1.4.jar:42.1.4]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260) ~[postgresql-42.1.4.jar:42.1.4]
        at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.execute(MysqlSessions.java:454) ~[hugegraph-mysql-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlTable.createTable(MysqlTable.java:112) ~[hugegraph-mysql-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlTable.init(MysqlTable.java:72) ~[hugegraph-mysql-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlStore.initTables(MysqlStore.java:290) ~[hugegraph-mysql-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.mysql.MysqlStore.init(MysqlStore.java:165) ~[hugegraph-mysql-0.11.0.jar:?]
        at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.init(AbstractBackendStoreProvider.java:104) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
        at com.baidu.hugegraph.HugeGraph.initBackend(HugeGraph.java:207) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
        at com.baidu.hugegraph.GremlinGraph$initBackend$1.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.7-indy.jar:2.5.7]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.7-indy.jar:2.5.7]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.7-indy.jar:2.5.7]
        at Script7.run(Script7.groovy:1) ~[?:?]
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:674) ~[gremlin-groovy-3.4.3.jar:3.4.3]
        at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:376) ~[gremlin-groovy-3.4.3.jar:3.4.3]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[?:1.8.0_181]
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266) ~[gremlin-groovy-3.4.3.jar:3.4.3]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.11.0.jar:0.49.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by zhoney** [comment]
```
2019-12-05 14:12:55 69862 [gremlin-server-exec-2] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Not allowed to create class loader via Gremlin
java.lang.SecurityException: Not allowed to create class loader via Gremlin
	at com.baidu.hugegraph.security.HugeSecurityManager.newSecurityException(HugeSecurityManager.java:356) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at com.baidu.hugegraph.security.HugeSecurityManager.checkCreateClassLoader(HugeSecurityManager.java:104) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at java.lang.ClassLoader.checkCreateClassLoader(ClassLoader.java:274) ~[?:1.8.0_222]
	at java.lang.ClassLoader.<init>(ClassLoader.java:316) ~[?:1.8.0_222]
	at java.security.SecureClassLoader.<init>(SecureClassLoader.java:76) ~[?:1.8.0_222]
	at java.net.URLClassLoader.<init>(URLClassLoader.java:101) ~[?:1.8.0_222]
	at org.apache.hadoop.hbase.util.ClassLoaderBase.<init>(ClassLoaderBase.java:48) ~[hbase-common-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.util.DynamicClassLoader.<init>(DynamicClassLoader.java:92) ~[hbase-common-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.ipc.RemoteWithExtrasException$ClassLoaderHolder.lambda$static$0(RemoteWithExtrasException.java:56) ~[hbase-client-2.0.0.jar:2.0.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_222]
	at org.apache.hadoop.hbase.ipc.RemoteWithExtrasException$ClassLoaderHolder.<clinit>(RemoteWithExtrasException.java:55) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.ipc.RemoteWithExtrasException.unwrapRemoteException(RemoteWithExtrasException.java:79) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.protobuf.ProtobufUtil.makeIOExceptionOfException(ProtobufUtil.java:279) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.protobuf.ProtobufUtil.handleRemoteException(ProtobufUtil.java:266) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:129) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:386) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:360) ~[hbase-client-2.0.0.jar:2.0.0]
	at com.baidu.hugegraph.backend.store.hbase.HbaseSessions$Session.get(HbaseSessions.java:428) ~[hugegraph-hbase-0.11.0.jar:?]
	at com.baidu.hugegraph.backend.store.hbase.HbaseTables$Counters.getCounter(HbaseTables.java:57) ~[hugegraph-hbase-0.11.0.jar:?]
	at com.baidu.hugegraph.backend.store.hbase.HbaseStore$HbaseSchemaStore.getCounter(HbaseStore.java:410) ~[hugegraph-hbase-0.11.0.jar:?]
	at com.baidu.hugegraph.backend.store.BackendStore.setCounterLowest(BackendStore.java:101) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.setNextIdLowest(SchemaTransaction.java:425) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.init(BackendStoreSystemInfo.java:52) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.initSystemInfo(AbstractBackendStoreProvider.java:142) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at com.baidu.hugegraph.HugeGraph.truncateBackend(HugeGraph.java:241) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at com.baidu.hugegraph.GremlinGraph$truncateBackend.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.7-indy.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.7-indy.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.7-indy.jar:2.5.7]
	at Script3.run(Script3.groovy:1) ~[?:?]
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:674) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:376) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[?:1.8.0_222]
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.11.0.jar:0.49.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by zhoney** [comment]
```
2019-12-06 14:21:04 320890 [gremlin-server-exec-1] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Not allowed to connect socket via Gremlin
java.lang.SecurityException: Not allowed to connect socket via Gremlin
	at com.baidu.hugegraph.security.HugeSecurityManager.newSecurityException(HugeSecurityManager.java:356) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at com.baidu.hugegraph.security.HugeSecurityManager.checkConnect(HugeSecurityManager.java:233) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1269) ~[?:1.8.0_222]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_222]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_222]
	at java.net.InetAddress.getByName(InetAddress.java:1077) ~[?:1.8.0_222]
	at org.apache.hadoop.hbase.client.ConnectionUtils.getStubKey(ConnectionUtils.java:233) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.ConnectionImplementation$MasterServiceStubMaker.makeStubNoRetries(ConnectionImplementation.java:1126) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.ConnectionImplementation$MasterServiceStubMaker.makeStub(ConnectionImplementation.java:1148) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.ConnectionImplementation.getKeepAliveMasterService(ConnectionImplementation.java:1213) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.ConnectionImplementation.getMaster(ConnectionImplementation.java:1202) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.MasterCallable.prepare(MasterCallable.java:57) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:105) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3055) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3047) ~[hbase-client-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hbase.client.HBaseAdmin.listNamespaceDescriptors(HBaseAdmin.java:2235) ~[hbase-client-2.0.0.jar:2.0.0]
	at com.baidu.hugegraph.backend.store.hbase.HbaseSessions.existsNamespace(HbaseSessions.java:146) ~[hugegraph-hbase-0.11.0.jar:?]
	at com.baidu.hugegraph.backend.store.hbase.HbaseStore.clear(HbaseStore.java:255) ~[hugegraph-hbase-0.11.0.jar:?]
	at com.baidu.hugegraph.backend.store.AbstractBackendStoreProvider.clear(AbstractBackendStoreProvider.java:116) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at com.baidu.hugegraph.HugeGraph.clearBackend(HugeGraph.java:226) ~[hugegraph-core-0.11.0.jar:0.11.0.0]
	at com.baidu.hugegraph.GremlinGraph$clearBackend$0.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.7-indy.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.7-indy.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.7-indy.jar:2.5.7]
	at Script6.run(Script6.groovy:1) ~[?:?]
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:674) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:376) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[?:1.8.0_222]
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.11.0.jar:0.49.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
