### ISSUE TITLE
List option must be registered with class ConfigListOption

### ISSUE THREAD

**Issue by javeme** [hugegraph/hugegraph#774]
### Actual behavior 实际表现
Start server with error when config `rocksdb.compression_per_level`:
```
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78) ~[gremlin-core-3.4.3.jar:3.4.3]
	... 16 more
Caused by: java.lang.IllegalStateException: List option must be registered with class ConfigListOption
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199) ~[guava-19.0.jar:?]
	at com.baidu.hugegraph.util.E.checkState(E.java:68) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
	at com.baidu.hugegraph.config.HugeConfig.validateOption(HugeConfig.java:151) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
	at com.baidu.hugegraph.config.HugeConfig.addProperty(HugeConfig.java:138) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
	at com.baidu.hugegraph.config.HugeConfig.<init>(HugeConfig.java:54) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
	at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:42) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78) ~[gremlin-core-3.4.3.jar:3.4.3]
	... 16 more
```

### Specifications of environment 环境信息
- hugegraph version: 0.10
- operating system: mac
- hugegraph backend: rocksdb 6.3.6

**Comment by javeme** [comment]
After fixing ConfigListOption, there is a new error:
```
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78) ~[gremlin-core-3.4.3.jar:3.4.3]
	... 16 more
Caused by: java.lang.IllegalArgumentException: Invalid option value for 'rocksdb.compression_per_level': [NO_COMPRESSION, NO_COMPRESSION, NO_COMPRESSION, NO_COMPRESSION, NO_COMPRESSION, NO_COMPRESSION, NO_COMPRESSION]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146) ~[guava-19.0.jar:?]
	at com.baidu.hugegraph.util.E.checkArgument(E.java:56) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
	at com.baidu.hugegraph.config.TypedOption.check(TypedOption.java:149) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
	at com.baidu.hugegraph.config.HugeConfig.validateOption(HugeConfig.java:150) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
	at com.baidu.hugegraph.config.HugeConfig.addProperty(HugeConfig.java:138) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
	at com.baidu.hugegraph.config.HugeConfig.<init>(HugeConfig.java:54) ~[hugegraph-common-1.6.16.jar:1.6.16.0]
	at com.baidu.hugegraph.HugeFactory.open(HugeFactory.java:42) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78) ~[gremlin-core-3.4.3.jar:3.4.3]
	... 16 more
```
