### ISSUE TITLE
请教：部署hugegraph-studio-0.10.0后，执行graph.schema().propertyKey("name").asText().ifNotExist().create()报错

### ISSUE THREAD

**Issue by OptimusPrimeLee** [hugegraph/hugegraph#778]
Invalid request - responding with 500 Internal Server Error and The 'hugegraph' store of mysql has not been opened
com.baidu.hugegraph.exception.ConnectionException: The 'hugegraph' store of mysql has not been opened
	at com.baidu.hugegraph.backend.store.AbstractBackendStore.checkOpened(AbstractBackendStore.java:60) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.query(MysqlStore.java:246) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.query(AbstractTransaction.java:105) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.queryByName(SchemaIndexTransaction.java:84) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.SchemaIndexTransaction.query(SchemaIndexTransaction.java:75) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getSchema(SchemaTransaction.java:310) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.cache.CachedSchemaTransaction.getSchema(CachedSchemaTransaction.java:200) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.SchemaTransaction.getPropertyKey(SchemaTransaction.java:126) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.schema.builder.PropertyKeyBuilder.create(PropertyKeyBuilder.java:86) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.schema.builder.PropertyKeyBuilder.create(PropertyKeyBuilder.java:41) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.schema.builder.SchemaBuilder$create$0.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.7-indy.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.7-indy.jar:2.5.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119) ~[groovy-2.5.7-indy.jar:2.5.7]
	at Script9.run(Script9.groovy:1) ~[?:?]
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:674) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:376) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[?:1.8.0_152]
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

**Comment by OptimusPrimeLee** [comment]
页面提示：
Error!
java.net.SocketTimeoutException: Read timed out

**Comment by javeme** [comment]
看起来与 #758 是一样的
