### ISSUE TITLE
创建unique schema，本地没问题，但切换到服务器提示要升级版本

### ISSUE THREAD

**Issue by CPJ-data** [hugegraph/hugegraph#839]
报错信息：
Caused by: com.baidu.hugegraph.rest.ClientException: HugeGraphServer API version must be >= 0.44 to support unique index, but current HugeGraphServer API version is: 0.38.0.0
at com.baidu.hugegraph.client.RestClient.checkApiVersion(RestClient.java:80)
	at com.baidu.hugegraph.api.schema.IndexLabelAPI.create(IndexLabelAPI.java:49)
	at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:187)
	at com.baidu.hugegraph.driver.SchemaManager.addIndexLabel(SchemaManager.java:182)
	at com.baidu.hugegraph.structure.schema.IndexLabel$BuilderImpl.create(IndexLabel.java:133)
	at com.baidu.hugegraph.structure.schema.IndexLabel$BuilderImpl.create(IndexLabel.java:116)
 服务器上使用是0.9.2的server，存储后端用了Cassandra
 本地使用0.10.4的server，存储后端memory：创建schema成功
 测试服务器使用是0.9.2的server，存储后端用了Cassandra：创建schema成功
请问大佬这种情况是升级哪个jar包？
client使用是官网的最新版本的jar——>version: '1.8.0'

**Comment by javeme** [comment]
@CPJ-data server需要使用0.10版本，可以使用tools中的migrate命令迁移数据
