### ISSUE TITLE
配置mysql连接，初始化数据库时sslmodel不起作用

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#849]
报错如下：
 Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to obtain database info
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.existsDatabase(MysqlSessions.java:144)
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.initialized(MysqlStore.java:202)
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:88)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:99)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87)
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to access jdbc:mysql://192.168.32.134:3307
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.openWithoutDB(MysqlSessions.java:194)
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.existsDatabase(MysqlSessions.java:135)
	... 4 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

**Comment by javeme** [comment]
类似问题：https://github.com/hugegraph/hugegraph/issues/172

**Comment by I-DO-NOT-KNOW** [comment]
> 类似问题：#172

下载ssl-mode分支的代码，编译后这个问题就解决了。相关问题看这个https://github.com/hugegraph/hugegraph/pull/842

**Comment by I-DO-NOT-KNOW** [comment]
下载ssl-mode分支的代码，编译后这个问题就解决了。相关问题看这个https://github.com/hugegraph/hugegraph/pull/842
