### ISSUE TITLE
关于报错Failed to deserialize json的问题

### ISSUE THREAD

**Issue by eternalxj** [hugegraph/hugegraph#855]
新安装了hugegraph 10的最新版本，在跑例子的时候 出现报错，详细如下，请问要如何处理 @Linary @javeme 
 bin/hugegraph-loader -g hugegraph -f data/example/example.json -s data/example/schema.groovy
Exception in thread "main" com.baidu.hugegraph.rest.SerializeException: Failed to deserialize json
	at com.baidu.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:70)
	at com.baidu.hugegraph.loader.struct.GraphStruct.of(GraphStruct.java:67)
	at com.baidu.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:71)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:65)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "mapping" (class com.baidu.hugegraph.loader.struct.VertexStruct), not marked as ignorable (10 known properties: "value_mapping", "update_strategies", "field_mapping", "input", "ignored", "label", "null_values", "id", "selected", "skip"])
 at [Source: {
  "vertices": [
    {
      "label": "person",
      "input": {
        "type": "file",
        "path": "example/vertex_person.csv",
        "format": "CSV",
        "header": ["name", "age", "city"],
        "charset": "UTF-8"
      },
      "mapping": {
        "name": "name",
        "age": "age",
        "city": "city"
      }
    },
    {
      "label": "software",
      "input": {
        "type": "file",
        "path": "example/vertex_software.text",
        "format": "TEXT",
        "delimiter": "|",
        "charset": "GBK"
      }
    }
  ],
  "edges": [
    {
      "label": "knows",
      "source": ["source_name"],
      "target": ["target_name"],
      "input": {
        "type": "file",
        "path": "example/edge_knows.json",
        "format": "JSON"
      },
      "mapping": {
        "source_name": "name",
        "target_name": "name"
      }
    },
    {
      "label": "created",
      "source": ["aname"],
      "target": ["bname"],
      "input": {
        "type": "file",
        "path": "example/edge_created.json",
        "format": "JSON"
      },
      "mapping": {
        "aname": "name",
        "bname": "name"
      }
    }
  ]
}
; line: 17, column: 6] (through reference chain: com.baidu.hugegraph.loader.struct.GraphStruct["vertices"]->java.util.ArrayList[0]->com.baidu.hugegraph.loader.struct.VertexStruct["mapping"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:817)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:958)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1278)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:452)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3564)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2580)
	at com.baidu.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:68)
	... 3 more

**Comment by Linary** [comment]
@eternalxj `mapping`域需要修改成`field_mapping`
