### ISSUE TITLE
访问server不稳定，有时候会出现error

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#872]
使用studio和client访问图数据库服务器时，有时候正常，有时候会出现400或者500的错误。
比如client访问，调用updateVertices方法，访问的response信息如下
requestUri=http://xxx.xxx.xxx.xxx:8080/graphs/hugegraph/graph/vertices/batch
httpMethod=PUT
返回的status有时候是500有时候是400，偶尔是200，操作成功。
400时报错：
```
com.baidu.hugegraph.backend.BackendException: Failed to rollback
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.rollback(MysqlSessions.java:420) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.rollbackTx(MysqlStore.java:293) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.rollback(AbstractTransaction.java:188) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.rollback(IndexableTransaction.java:72) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.rollback(GraphTransaction.java:382) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph$Txs.rollback(HugeGraph.java:809) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.doRollback(HugeGraph.java:698) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.rollback(AbstractTransaction.java:114) ~[gremlin-core-3.4.3.jar:3.4.3]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.rollback(HugeGraph.java:667) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.api.API.lambda$commit$0(API.java:86) ~[hugegraph-api-0.10.4.jar:0.48.0.0]
	at com.baidu.hugegraph.api.API.commit(API.java:103) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at com.baidu.hugegraph.api.graph.BatchAPI.commit(BatchAPI.java:75) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at com.baidu.hugegraph.api.graph.VertexAPI.update(VertexAPI.java:145) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.1.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.28.jar:2.3.28]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593) [grizzly-framework-2.3.28.jar:2.3.28]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573) [grizzly-framework-2.3.28.jar:2.3.28]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
	at sun.reflect.GeneratedConstructorAccessor72.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_231]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_231]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4576) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.rollback(MysqlSessions.java:418) ~[hugegraph-mysql-0.10.4.jar:?]
	... 37 more
```

500时报错：
```
java.lang.NullPointerException: null
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.execute(MysqlSessions.java:463) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.reconnectIfNeeded(MysqlSessions.java:434) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.BackendSessionPool.detectSession(BackendSessionPool.java:89) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.store.BackendSessionPool.getOrNewSession(BackendSessionPool.java:68) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.session(MysqlSessions.java:94) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.opened(MysqlStore.java:150) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.AbstractBackendStore.checkOpened(AbstractBackendStore.java:57) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.rollbackTx(MysqlStore.java:291) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.rollback(AbstractTransaction.java:188) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.rollback(IndexableTransaction.java:72) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.rollback(GraphTransaction.java:382) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph$Txs.rollback(HugeGraph.java:809) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.doRollback(HugeGraph.java:698) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.rollback(AbstractTransaction.java:114) ~[gremlin-core-3.4.3.jar:3.4.3]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.rollback(HugeGraph.java:667) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.api.API.lambda$commit$0(API.java:86) ~[hugegraph-api-0.10.4.jar:0.48.0.0]
	at com.baidu.hugegraph.api.API.commit(API.java:103) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at com.baidu.hugegraph.api.graph.BatchAPI.commit(BatchAPI.java:75) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at com.baidu.hugegraph.api.graph.VertexAPI.update(VertexAPI.java:145) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.1.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.28.jar:2.3.28]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593) [grizzly-framework-2.3.28.jar:2.3.28]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573) [grizzly-framework-2.3.28.jar:2.3.28]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

```

使用studio执行语句时，大多数是正常的，偶尔也会出现error页面，多执行几次就又正常了。

我用的是mysql 5.7，不知道是不是不太支持mysql

**Comment by javeme** [comment]
@I-DO-NOT-KNOW 看日志里面报错：`“Communications link failure during rollback(). Transaction resolution unknown.”`，是否有大量写入数据的时候触发的？异常频繁程度是？最好能提供一下复现流程。

第2个500异常可能是由于上面那个触发的，是一个Bug，这个稍后会解决。

**Comment by I-DO-NOT-KNOW** [comment]
@javeme 我是先通过graph.getVertex读取一条数据，之后更改数据值之后调用graph.updateVertices方法。一般读取数据没有什么问题，不会报错。但是调用updateVertices这个方法时出错率特别高，一般是500，偶尔出现400，偶尔会200正常。没有大量数据写入，也没有频繁的调用。
代码如下：
HugeClient hugeClient = new HugeClient("http://xxx.xxx.xxx.xxx:8080", "hugegraph");
GraphManager graph = hugeClient.graph();
        
Vertex vertex = graph.getVertex("sysUser_xxxxxxxxx");
System.out.println(vertex);
vertex.attachManager(null);
vertex.property("name","测试1");
List<Vertex> vertexList=new ArrayList<Vertex>();
vertexList.add(vertex);

Map<String, UpdateStrategy> updateStrategyMap=new HashMap<String, UpdateStrategy>();
updateStrategyMap.put("name",UpdateStrategy.OVERRIDE);
updateStrategyMap.put("code",UpdateStrategy.OVERRIDE);
updateStrategyMap.put("login_name",UpdateStrategy.OVERRIDE);
updateStrategyMap.put("sex",UpdateStrategy.OVERRIDE);
updateStrategyMap.put("email",UpdateStrategy.OVERRIDE);

BatchVertexRequest.Builder build =BatchVertexRequest.createBuilder();
build.vertices(vertexList);
build.updatingStrategies(updateStrategyMap);
build.createIfNotExist(true);
BatchVertexRequest batchVertexRequest =build.build();
graph.updateVertices(batchVertexRequest);

hugeClient.close();
