### ISSUE TITLE
postgresql初始化数据报错

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#888]
### Expected behavior 期望表现
正常导入

### Actual behavior 实际表现
报错
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to obtain database info
	at com.baidu.hugegraph.backend.store.postgresql.PostgresqlSessions.existsDatabase(PostgresqlSessions.java:61)
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.initialized(MysqlStore.java:202)
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:88)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:99)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87)
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to access jdbc:postgresql://192.168.32.134:5432
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.openWithoutDB(MysqlSessions.java:194)
	at com.baidu.hugegraph.backend.store.postgresql.PostgresqlSessions.existsDatabase(PostgresqlSessions.java:57)
	... 4 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:postgresql://192.168.32.134:5432?socketTimeout=0
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.connect(MysqlSessions.java:261)
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.openWithoutDB(MysqlSessions.java:192)
	... 5 more

### Steps to reproduce the problem 复现步骤
1.配置hugegraph.properties信息如下
gremlin.graph=com.baidu.hugegraph.HugeFactory

backend=postgresql
serializer=postgresql

store=postgres

search.text_analyzer=jieba
search.text_analyzer_mode=INDEX

jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://192.168.32.134:5432
jdbc.username=postgres
jdbc.password=postgres
jdbc.reconnect_max_times=3
jdbc.reconnect_interval=3
jdbc.sslmode=false

2.执行初始化操作

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- hugegraph backend: postgresql-9.6.17

**Comment by zhoney** [comment]
@I-DO-NOT-KNOW 

```
jdbc.url=jdbc:postgresql://192.168.32.134:5432/
```
最后面的那个”/“不能忽略
