### ISSUE TITLE
访问图数据库服务器不稳定

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph#897]
### Expected behavior 期望表现
{type something here...}
返回正常结果

### Actual behavior 实际表现
{type something here...}
写一个正常的gremlin语句，一般会返回正常结果，但是偶尔服务器报错

### Steps to reproduce the problem 复现步骤
1. {step 1}在studio中执行命令g.V().limit(10)

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- hugegraph backend: mysql 5.7

报错内容如下：
```
[gremlin-server-exec-8] [WARN ] org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler [] - Invalid request - responding with 500 Internal Server Error and Error encountered evaluating script: g.V().limit(10)
java.lang.NullPointerException: null
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.execute(MysqlSessions.java:463) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions$Session.reconnectIfNeeded(MysqlSessions.java:434) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.BackendSessionPool.detectSession(BackendSessionPool.java:89) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.store.BackendSessionPool.getOrNewSession(BackendSessionPool.java:68) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.session(MysqlSessions.java:94) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.opened(MysqlStore.java:150) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.AbstractBackendStore.checkOpened(AbstractBackendStore.java:57) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.store.mysql.MysqlStore.query(MysqlStore.java:260) ~[hugegraph-mysql-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.query(AbstractTransaction.java:105) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.query(GraphTransaction.java:391) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.queryVerticesFromBackend(GraphTransaction.java:592) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.queryVerticesFromBackend(CachedGraphTransaction.java:150) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.queryVertices(GraphTransaction.java:561) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph.vertices(HugeGraph.java:411) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.vertices(HugeGraphStep.java:99) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.lambda$new$0(HugeGraphStep.java:67) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:155) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:197) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.fill(IteratorUtils.java:62) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.list(IteratorUtils.java:85) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils.asList(IteratorUtils.java:382) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler.lambda$channelRead$1(HttpGremlinEndpointHandler.java:245) ~[gremlin-server-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.util.function.FunctionUtils.lambda$wrapFunction$0(FunctionUtils.java:36) ~[gremlin-core-3.4.3.jar:3.4.3]
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:272) ~[gremlin-groovy-3.4.3.jar:3.4.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_231]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_231]
	at com.baidu.hugegraph.auth.HugeGraphAuthProxy$ContextTask.run(HugeGraphAuthProxy.java:282) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

**Comment by javeme** [comment]
@I-DO-NOT-KNOW 这个问题已经在 #872 中解决了，请使用新的补丁尝试。具体cherry-pick #874
