### ISSUE TITLE
Cassandra 作为存储后端初始化图报错

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph#900]
### Expected behavior 期望表现

HugeGraph 0.10.4 以 Cassandra 作为后端，初始化图能够成功。

### Actual behavior 实际表现

提示 `Column family ID mismatch`

### Steps to reproduce the problem 复现步骤
1. 部署一个简单的 Cassandra 3节点集群（版本3.11.6）
2. 使用 HugeGraph 0.10.0，配置两个图
3. init-store.sh 过程报错

```java
 ....   Unexpected exception during request
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 235462f0-6840-11ea-991b-abb60f005d76; expected 056ac360-6840-11ea-991b-abb60f005d76)
at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:443) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.MigrationManager.announce(MigrationManager.java:572) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:369) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:354) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:349) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.cql3.statements.CreateTableStatement.announceMigration(CreateTableStatement.java:89) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.cql3.statements.SchemaAlteringStatement.execute(SchemaAlteringStatement.java:123) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:225) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:256) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:241) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:116) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.transport.Message$Dispatcher.processRequest(Message.java:686) [apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.transport.Message$Dispatcher.lambda$channelRead0$0(Message.java:592) [apache-cassandra-3.11.6.jar:3.11.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_181]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:165) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```
之前用 c 作为后端比较少，想问下这个问题是什么原因造成的呢？（看起来像是建 schema 的时候产生了 race）。

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system: Debian 4.9.88
- hugegraph backend: like cassandra 3.11.6, cluster with 3 nodes, 1TB HDD disk each node

**Comment by zhoney** [comment]
@suesunss 是否执行了多次init-store.sh脚本呢？

这个是Cassandra创建表的时候出现的Race Condition问题。出现的原因是Cassandra集群节点间数据不一致。比如：
- 第一次init时，连接的是node1且创建了table1和table2，node2刚刚同步了table1
- 再次init时，连接的是node2，发现没有table2，就会创建table2，此时在集群中就会有两个名字都为table2但是UUID不同的table，就会出现cf id mismatch

> 建议：如果一次init-store因超时导致没有成功，需等待所有节点的table都相同的时候（cqlsh登录各个节点查看），再次init-store

**Comment by suesunss** [comment]
@zhoney 

感谢回复。

- 比较奇怪，我几次尝试都是第一次 `init-store.sh` 就会出现这个问题。
- 后来，我看了下节点的 status，每个节点看起来都追上了，然后执行 `init-store.sh`，还是会出现这个问题。
