### ISSUE TITLE
HugeGraph 0.10.4 Vertex/Edge Batch API 报错

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph#912]
### Expected behavior 期望表现

HugeGraph 0.10.4 利用 

```txt
POST http://localhost:8080/graphs/hugegraph/graph/vertices/batch
```

或者 

```txt
POST http://localhost:8080/graphs/hugegraph/graph/edges/batch
```

批量创建多个顶点/边能够成功插入。

数据每次的批量是500。 

### Actual behavior 实际表现

之前使用这个 API 插入数据都是 OK 的，但是突然出现了如下的 RocksDB 异常：

```java
2020-03-27 15:03:22 351265178 [grizzly-http-server-2] [ERROR] com.baidu.hugegraph.server.RestServer [] - Failed to commit
com.baidu.hugegraph.backend.BackendException: Exception in backend
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:600) ~[hugegraph-rocksdb-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:537) ~[hugegraph-rocksdb-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStore.commitTx(RocksDBStore.java:481) ~[hugegraph-rocksdb-0.10.4.jar:?]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commitMutation2Backend(AbstractTransaction.java:246) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.cache.CachedGraphTransaction.commitMutation2Backend(CachedGraphTransaction.java:209) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.IndexableTransaction.commit2Backend(IndexableTransaction.java:57) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.AbstractTransaction.commit(AbstractTransaction.java:167) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.backend.tx.GraphTransaction.commit(GraphTransaction.java:369) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph$Txs.commit(HugeGraph.java:805) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.doCommit(HugeGraph.java:692) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104) ~[gremlin-core-3.4.3.jar:3.4.3]
	at com.baidu.hugegraph.HugeGraph$TinkerpopTransaction.commit(HugeGraph.java:658) ~[hugegraph-core-0.10.4.jar:0.10.4.0]
	at com.baidu.hugegraph.api.API.commit(API.java:94) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at com.baidu.hugegraph.api.graph.BatchAPI.commit(BatchAPI.java:75) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:111) [hugegraph-api-0.10.4.jar:0.48.0.0]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.1.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.1.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.28.jar:2.3.28]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593) [grizzly-framework-2.3.28.jar:2.3.28]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573) [grizzly-framework-2.3.28.jar:2.3.28]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: org.rocksdb.RocksDBException: While appending to file: /hugegraph_data/wal/{{my_graph_name}}/g/001248.log: Input/output error
	at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-6.3.6.jar:?]
	at org.rocksdb.RocksDB.write(RocksDB.java:1421) ~[rocksdbjni-6.3.6.jar:?]
	at com.baidu.hugegraph.backend.store.rocksdb.RocksDBStdSessions$StdSession.commit(RocksDBStdSessions.java:597) ~[hugegraph-rocksdb-0.10.4.jar:?]
	... 39 more
```

### Specifications of environment 环境信息
- hugegraph version: 0.10.4
- operating system: ubuntu 18.04
- hugegraph backend: RocksDB compatible with HugeGraph 0.10.4

**Comment by javeme** [comment]
@suesunss 看起来可能是磁盘出问题了，可以搜索一下“Input/output error”，详细定位下。
