### ISSUE TITLE
mysql作为存储后端时，init-store.sh 失败？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph#923]
./bin/init-store.sh启动错误日志如下：
Initing HugeGraph Store...
Wed Apr 01 14:58:54 CST 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to obtain database info
    at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.existsDatabase(MysqlSessions.java:144)
    at com.baidu.hugegraph.backend.store.mysql.MysqlStore.initialized(MysqlStore.java:202)
    at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:88)
    at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:99)
    at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87)
Caused by: com.baidu.hugegraph.backend.BackendException: Failed to access jdbc:mysql://127.0.0.1:3306
    at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.openWithoutDB(MysqlSessions.java:194)
    at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.existsDatabase(MysqlSessions.java:135)
    ... 4 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 543 milliseconds ago.  The last packet sent successfully to the server was 533 milliseconds ago.
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
    at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:203)
    at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4901)
    at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659)
    at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:247)
    at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.connect(MysqlSessions.java:261)
    at com.baidu.hugegraph.backend.store.mysql.MysqlSessions.openWithoutDB(MysqlSessions.java:192)
    ... 5 more
Caused by: javax.net.ssl.SSLKeyException: RSA premaster secret error
    at sun.security.ssl.RSAClientKeyExchange.<init>(RSAClientKeyExchange.java:87)
    at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:912)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
    at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:188)
    ... 24 more
Caused by: java.security.NoSuchAlgorithmException: SunTlsRsaPremasterSecret KeyGenerator not available
    at javax.crypto.KeyGenerator.<init>(KeyGenerator.java:169)
    at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:223)
    at sun.security.ssl.JsseJce.getKeyGenerator(JsseJce.java:251)
    at sun.security.ssl.RSAClientKeyExchange.<init>(RSAClientKeyExchange.java:78)
    ... 33 more

请问这是什么原因？

**Comment by javeme** [comment]
@597477803 看起来是包冲突导致的，请检查java环境下是否有多个版本的 javax.crypto包

**Comment by 597477803** [comment]
> javax.crypto包

能说详细点么？没太懂

**Comment by 597477803** [comment]
> @597477803 看起来是包冲突导致的，请检查java环境下是否有多个版本的 javax.crypto包

我查了一下，不存在多个版本的java环境，而且我再mac和ubuntu上都试过了，一样的错误；也用低版本的hugegraph试过，基本是一样的错误；应该就是hugegraph里的mysql有关的jar包有问题？

**Comment by zacharyzhao123** [comment]
老哥问题解决了吗

**Comment by 597477803** [comment]
> 老哥问题解决了吗

用源码本地编译一版的没有这个问题，应该是对方编译好的jar包有些冲突

**Comment by zacharyzhao123** [comment]
能否请教下我初始化没错，但是启动就提示 failed，也没有日志输出。

**Comment by 56333178** [comment]
在线等答案，mysql要求什么版本，试了好几个版本了初始化数据都会报这个错

**Comment by liuzhilong** [comment]
> 在线等答案，mysql要求什么版本，试了好几个版本了初始化数据都会报这个错

首先这是因为``hugegraph.properties``里面的设置``jdbc.ssl_mode=false``未生效，导致出现上面的``WARN``，目前已有pr修复并合并到master分支了，看[这里](https://github.com/hugegraph/hugegraph/pull/842)，所以就像 @597477803 说的，下载master分支的代码并编译可以解决这个问题，如果你不想这么做的话，往下看：

前面说的是``WARN``的原因，但mysql不强制设置useSSL=false的话，应该只报warn，不应该抛出下面的异常。
这些异常的原因是``init-store.sh``脚本里最后一句代码的问题：
``-Djava.ext.dirs=$LIB:$PLUGINS``覆盖了``ExtClassLoader``类加载器的默认行为，使得``jre/lib/ext``下的jar包未被加载，这些扩展jar包里包含一些加密算法，所以抛出了``NoSuchAlgorithmException``。

**解决办法：**
把``-Djava.ext.dirs=$LIB:$PLUGINS``改为``-Djava.ext.dirs=$LIB:$PLUGINS:$JAVA_HOME/jre/lib/ext``(你需要设置
``JAVA_HOME``环境变量)，再次执行``init-store.sh``，可以看到仍然有``WARN``，但数据库初始化可以完成。
