### ISSUE TITLE
NPE with test HasTest.g_V_hasIdXwithinXemptyXX_count()

### ISSUE THREAD

**Issue by javeme** [hugegraph/hugegraph#938]
error with test HasTest.g_V_hasIdXwithinXemptyXX_count():
```
java.lang.NullPointerException
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.hashCode(GraphStep.java:176)
	at com.baidu.hugegraph.traversal.optimize.HugeGraphStep.hashCode(HugeGraphStep.java:204)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.equals(AbstractStep.java:192)
	at org.apache.tinkerpop.gremlin.process.traversal.Step.equals(Step.java:173)
	at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalHelper.stepIndex(TraversalHelper.java:229)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal$Admin.removeStep(Traversal.java:379)
	at com.baidu.hugegraph.traversal.optimize.HugeCountStepStrategy.apply(HugeCountStepStrategy.java:106)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversalStrategies.applyStrategies(DefaultTraversalStrategies.java:84)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.applyStrategies(DefaultTraversal.java:124)
	at org.apache.tinkerpop.gremlin.AbstractGremlinTest.printTraversalForm(AbstractGremlinTest.java:278)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.HasTest.g_V_hasIdXwithinXemptyXX_count(HasTest.java:518)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.tinkerpop.gremlin.process.GremlinProcessRunner.runChild(GremlinProcessRunner.java:53)
	at org.apache.tinkerpop.gremlin.process.GremlinProcessRunner.runChild(GremlinProcessRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:229)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:51)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at com.baidu.hugegraph.tinkerpop.ProcessBasicSuite$1.evaluate(ProcessBasicSuite.java:293)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite$1.evaluate(AbstractGremlinSuite.java:238)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```
set `GraphStep.ids=null` GraphStep.addIds(Object... newIds)
```
Thread [main] (Suspended (breakpoint at line 119 in GraphStep))	
	HugeGraphStep<S,E>(GraphStep<S,E>).addIds(Object...) line: 119	
	GraphStep<S,E>.processHasContainerIds(GraphStep<?,?>, HasContainer) line: 202	
	TraversalUtil.extractHasContainer(HugeGraphStep<?,?>, Admin<?,?>) line: 104	
	HugeGraphStepStrategy.apply(Admin<?,?>) line: 60	
	DefaultTraversalStrategies.applyStrategies(Admin<?,?>) line: 84	
	DefaultGraphTraversal<S,E>(DefaultTraversal<S,E>).applyStrategies() line: 124	
	HasTest$Traversals(AbstractGremlinTest).printTraversalForm(Traversal) line: 278	
	HasTest$Traversals(HasTest).g_V_hasIdXwithinXemptyXX_count() line: 518	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 498	
	FrameworkMethod$1.runReflectiveCall() line: 50	
	FrameworkMethod$1(ReflectiveCallable).run() line: 12	
	FrameworkMethod.invokeExplosively(Object, Object...) line: 47	
	InvokeMethod.evaluate() line: 17	
	RunBefores.evaluate() line: 26	
	RunAfters.evaluate() line: 27	
	TestWatcher$1.evaluate() line: 55	
	RunRules.evaluate() line: 20	
	GremlinProcessRunner.runChild(FrameworkMethod, RunNotifier) line: 53	
	GremlinProcessRunner.runChild(Object, RunNotifier) line: 37	
	ParentRunner$3.run() line: 290	
	ParentRunner$1.schedule(Runnable) line: 71	
	GremlinProcessRunner(ParentRunner<T>).runChildren(RunNotifier) line: 288	
	ParentRunner<T>.access$000(ParentRunner, RunNotifier) line: 58	
	ParentRunner$2.evaluate() line: 268	
	GremlinProcessRunner(ParentRunner<T>).run(RunNotifier) line: 363	
	ProcessBasicSuite(Suite).runChild(Runner, RunNotifier) line: 128	
	ProcessBasicSuite(AbstractGremlinSuite).runChild(Runner, RunNotifier) line: 229	
	ProcessBasicSuite(AbstractGremlinSuite).runChild(Object, RunNotifier) line: 51	
	ParentRunner$3.run() line: 290	
	ParentRunner$1.schedule(Runnable) line: 71	
	ProcessBasicSuite(ParentRunner<T>).runChildren(RunNotifier) line: 288	
	ParentRunner<T>.access$000(ParentRunner, RunNotifier) line: 58	
	ParentRunner$2.evaluate() line: 268	
	ProcessBasicSuite$1.evaluate() line: 293	
	AbstractGremlinSuite$1.evaluate() line: 238	
	ProcessBasicSuite(ParentRunner<T>).run(RunNotifier) line: 363	
	JUnit4TestReference.run(TestExecution) line: 86	
	TestExecution.run(ITestReference[]) line: 38	
	RemoteTestRunner.runTests(String[], String, TestExecution) line: 459	
	RemoteTestRunner.runTests(TestExecution) line: 678	
	RemoteTestRunner.run() line: 382	
	RemoteTestRunner.main(String[]) line: 192	

```

**Comment by javeme** [comment]
tinkerpop fixed: https://github.com/apache/tinkerpop/pull/1184
