### ISSUE TITLE
gremlin 单机离线模式不能启动，groovy脚本不能运行

### ISSUE THREAD

**Issue by wangzhanxd** [hugegraph/hugegraph#953]
bin/gremlin-console.sh scripts/example.groovy

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
Exception in thread "main" java.lang.NullPointerException: Cannot invoke method activate() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.invokeGroovyObjectInvoker(IndyGuardsFiltersAndSignatures.java:163)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
        at org.apache.tinkerpop.gremlin.console.Console$_closure18.doCall(Console.groovy:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356)
        at org.codehaus.groovy.runtime.dgm$186.doMethodInvoke(Unknown Source)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
        at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:145)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
        at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:502)

**Comment by javeme** [comment]
@wangzhanxd 这是一个bug，最新版本已解决，同时0.10.4版本也可使用新的补丁包：https://github.com/hugegraph/hugegraph/releases/download/v0.10.4/hugegraph-0.10.4_2020-06-19.tar.gz

**Comment by thoughtway** [comment]
#\cp -Rf hugegraph-server-patch hugegraph-server

发生同样的错误。

**Comment by zhengyingying** [comment]
版本0.11.2，使用bin/gremlin-console.sh scripts/example.groovy仍然无法像说明文档中那样正确执行，执行命令后无响应。

[root@slave1 hugegraph-0.11.2]# bin/gremlin-console.sh scripts/example.groovy

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: HugeGraph
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
plugin activated: tinkerpop.sparql
gremlin> g.V()
No such property: g for class: groovysh_evaluate
Type ':help' or ':h' for help.
Display stack trace? [yN]

**Comment by javeme** [comment]
@zhengyingying 请先定义变量'g'：
```java
gremlin> graph = HugeFactory.open("conf/hugegraph.properties")
==>standardhugegraph[hugegraph]

gremlin> g=graph.traversal()
==>graphtraversalsource[standardhugegraph[hugegraph], standard]

gremlin> g.V()
```

**Comment by hjrowen** [comment]
我也遇到同样的问题。
版本0.11.2，使用bin/gremlin-console.sh scripts/example.groovy仍然无法像说明文档中那样正确执行，执行命令后无响应。

[root@iZwz9b3jqdssps5unenqhiZ hugegraph-0.11.2]# bin/gremlin-console.sh scripts/example.groovy

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: HugeGraph
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin>

**Comment by javeme** [comment]
@hjrowen 请问执行的是什么命令没有响应？

**Comment by elroyxiao** [comment]
> @hjrowen 请问执行的是什么命令没有响应？

遇到同样的问题，example.groovy这个脚本没有运行，zhengyingying提到的也是同一个问题，按理来讲g在example.groovy已经定义过了。如果这个脚本运行了命令行会print （>>>> query all vertices: size=" + g.V().toList().size()）但是执行bin/gremlin-console.sh scripts/example.groovy时并没有print
