### ISSUE TITLE
hugegraph使用hbase作为存储时，hbase是kerberos认证的，通过认证后报Failed to obtain table info，目前怀疑是listnamespace这一块没获取到。

### ISSUE THREAD

**Issue by llaimm** [hugegraph/hugegraph#955]
bin/init-store.sh 
```
Initing HugeGraph Store...
2020-04-17 18:18:03 715   [main] [INFO ] com.baidu.hugegraph.cmd.InitStore [] - Init graph with config file: conf/hugegraph.properties
2020-04-17 18:18:03 769   [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Opening backend store 'hbase' for graph 'sjzy2'
2020-04-17 18:18:04 1268  [main] [INFO ] com.baidu.hugegraph.backend.store.hbase.HbaseSessions [] - 成功连接Hbase Configuration: core-default.xml, core-site.xml, hbase-default.xml, hbase-site.xml
2020-04-17 18:18:04 1700  [main] [INFO ] com.baidu.hugegraph.backend.store.hbase.HbaseSessions [] - 成功连接Hbase Configuration: core-default.xml, core-site.xml, hbase-default.xml, hbase-site.xml
2020-04-17 18:18:05 2553  [main] [INFO ] com.baidu.hugegraph.backend.store.hbase.HbaseSessions [] - 成功连接Hbase Configuration: core-default.xml, core-site.xml, hbase-default.xml, hbase-site.xml
2020-04-17 18:22:14 251850 [main] [INFO ] com.baidu.hugegraph.HugeGraph [] - Close graph hugegraph[sjzy2]
Exception in thread "main" com.baidu.hugegraph.backend.BackendException: Failed to obtain table info
	at com.baidu.hugegraph.backend.store.hbase.HbaseStore.initialized(HbaseStore.java:307)
	at com.baidu.hugegraph.backend.store.BackendStoreSystemInfo.exists(BackendStoreSystemInfo.java:88)
	at com.baidu.hugegraph.cmd.InitStore.initGraph(InitStore.java:99)
	at com.baidu.hugegraph.cmd.InitStore.main(InitStore.java:87)
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=16, exceptions:
Fri Apr 17 18:18:15 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:18:15 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:18:16 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:18:16 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:18:16 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.io.IOException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on local exception: org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:18:27 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:18:39 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:18:54 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:19:14 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:19:34 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:19:54 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:20:14 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:20:44 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:21:14 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:21:44 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
Fri Apr 17 18:22:14 CST 2020, RpcRetryingCaller{globalStartTime=1587118685445, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:145)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3055)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3047)
	at org.apache.hadoop.hbase.client.HBaseAdmin.listNamespaceDescriptors(HBaseAdmin.java:2235)
	at com.baidu.hugegraph.backend.store.hbase.HbaseSessions.existsNamespace(HbaseSessions.java:150)
	at com.baidu.hugegraph.backend.store.hbase.HbaseStore.initialized(HbaseStore.java:296)
	... 3 more
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
	at org.apache.hadoop.hbase.client.ConnectionImplementation$MasterServiceStubMaker.makeStub(ConnectionImplementation.java:1154)
	at org.apache.hadoop.hbase.client.ConnectionImplementation.getKeepAliveMasterService(ConnectionImplementation.java:1213)
	at org.apache.hadoop.hbase.client.ConnectionImplementation.getMaster(ConnectionImplementation.java:1202)
	at org.apache.hadoop.hbase.client.MasterCallable.prepare(MasterCallable.java:57)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:105)
	... 8 more
Caused by: java.net.ConnectException: Call to hf-zww-2j05-u31-ma-003/10.15.36.4:60000 failed on connection exception: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:165)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:390)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:95)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:410)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:406)
	at org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:103)
	at org.apache.hadoop.hbase.ipc.Call.setException(Call.java:118)
	at org.apache.hadoop.hbase.ipc.BufferCallBeforeInitHandler.userEventTriggered(BufferCallBeforeInitHandler.java:92)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1377)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:929)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection.failInit(NettyRpcConnection.java:179)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection.access$500(NettyRpcConnection.java:71)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:267)
	at org.apache.hadoop.hbase.ipc.NettyRpcConnection$3.operationComplete(NettyRpcConnection.java:261)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:269)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hbase.thirdparty.io.netty.channel.ConnectTimeoutException: connection timed out: hf-zww-2j05-u31-ma-003/10.15.36.4:60000
	at org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	... 8 more
```

**Comment by javeme** [comment]
@llaimm 根据日志`ConnectTimeoutException: connection timed out`判断，可能是你发送给hbase的网络包被丢弃了，可以直接在hbase服务器上发送请求试试，或者trace下看看是网络设备哪个环节出问题了，并检查一下TCP配置参数。
