### ISSUE TITLE
用工具导入数据显示property key with name '?aname' does not exist

### ISSUE THREAD

**Issue by SmilingMonkey** [hugegraph/hugegraph#984]
### Expected behavior 期望表现
使用的hugegraph为0.10.4
hugegraph-loader版本为0.10.0
想利用工具将数据导入到hugegraph中。
数据格式如下：
**author.csv(vertices)**

aname
--
[以]约瑟夫·布伦纳
彭霞
[荷]迪克·斯瓦伯（Dick Swaab）
傅景华
王大淳
张清苓
王庆其 陈彤云

**books.csv(vertices)**

bname | date | kind
-- | -- | --
天下无癌：癌症补充替代疗法完全手册 | 2016/1/1 | 保健、养生
教你74个美容瘦身秘方 | 2014/10/22 | 保健、养生
我即我脑：在子宫中孕育，于阿茨海默氏病中消亡 | 2011/9/1 | 保健、养生
黄帝内经素问译注（中医古籍名著编译丛书） | 2010/1/1 | 保健、养生
景岳全书译注（全六册）中医古籍名著编译丛书 | 2010/1/1 | 保健、养生
金匮要略心典译注（中医古籍名著编译丛书） | 2009/12/21 | 保健、养生
脾胃论译注·刘涓子鬼遗方译注（中医古籍名著编译丛书） | 2010/4/14 | 保健、养生
神农本草经译注·难经译注（中医古籍名著编译丛书） | 2010/4/14 | 保健、养生

**edge_write.json(edges)**
{"source_name": "[以]约瑟夫·布伦纳", "target_name": "天下无癌：癌症补充替代疗法完全手册"}
{"source_name": "彭霞", "target_name": "教你74个美容瘦身秘方"}
{"source_name": "[荷]迪克·斯瓦伯（Dick Swaab）", "target_name": "我即我脑：在子宫中孕育，于阿茨海默氏病中消亡"}
{"source_name": "傅景华", "target_name": "黄帝内经素问译注（中医古籍名著编译丛书）"}
{"source_name": "王大淳", "target_name": "景岳全书译注（全六册）中医古籍名著编译丛书"}
{"source_name": "张清苓", "target_name": "金匮要略心典译注（中医古籍名著编译丛书）"}
{"source_name": "王庆其 陈彤云", "target_name": "脾胃论译注·刘涓子鬼遗方译注（中医古籍名著编译丛书）"}

**schema.groovy**

schema.propertyKey("kind").asText().ifNotExist().create();
schema.propertyKey("date").asText().ifNotExist().create();
schema.propertyKey("bname").asText().ifNotExist().create();
schema.propertyKey("aname").asText().ifNotExist().create();
schema.vertexLabel("book").properties("bname", "date", "kind").primaryKeys("bname").ifNotExist().create();
schema.vertexLabel("author").properties("aname").primaryKeys("aname").ifNotExist().create();
schema.edgeLabel("write").sourceLabel("author").targetLabel("book").ifNotExist().create();

**struct.json**
{
    "vertices": [{
            "label": "author",
            "input": {
                "type": "file",
                "path": "/root/hugegraph-loader-0.10.0/bin/data/author.csv",
                "format": "CSV",
                "charset": "UTF-8"
            }
        },
        {
            "label": "book",
            "input": {
                "type": "file",
                "path": "/root/hugegraph-loader-0.10.0/bin/data/book.csv",
                "format": "CSV",
                "charset": "UTF-8"
            }
        }
    ],
    "edges": [{
        "label": "write",
        "source": ["source_name"],
        "target": ["target_name"],
        "input": {
            "type": "file",
            "path": "/root/hugegraph-loader-0.10.0/bin/data/edge_write.json",
            "format": "JSON"
        }
    }]
}

### Actual behavior 实际表现
运行后，提示报错信息。信息为：
2020-05-03 08:22:24 [main] [INFO ] com.baidu.hugegraph.loader.struct.GraphStruct [] - Checking vertex struct descriptions
2020-05-03 08:22:24 [main] [INFO ] com.baidu.hugegraph.loader.struct.GraphStruct [] - Checking edge struct descriptions
2020-05-03 08:22:25 [main] [INFO ] com.baidu.hugegraph.loader.HugeGraphLoader [] - Start loading vertices
2020-05-03 08:22:25 [main] [INFO ] com.baidu.hugegraph.loader.reader.file.FileReader [] - Opening struct 'VertexStruct(author-cfeceffe)'
2020-05-03 08:22:26 [main] [INFO ] com.baidu.hugegraph.loader.HugeGraphLoader [] - Start parsing and loading 'VertexStruct(author-cfeceffe)'
2020-05-03 08:22:26 [main] [ERROR] com.baidu.hugegraph.loader.HugeGraphLoader [] - ERROR: Failed to load
com.baidu.hugegraph.exception.ServerException: property key with name '﻿aname' does not exist
	at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:44) ~[hugegraph-client-1.8.0.jar:1.8.0.0]
	at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:100) ~[hugegraph-client-1.8.0.jar:1.8.0.0]
	at com.baidu.hugegraph.rest.RestClient.get(RestClient.java:220) ~[hugegraph-common-1.6.11.jar:1.6.11.0]
	at com.baidu.hugegraph.api.schema.PropertyKeyAPI.get(PropertyKeyAPI.java:73) ~[hugegraph-client-1.8.0.jar:1.8.0.0]
	at com.baidu.hugegraph.driver.SchemaManager.getPropertyKey(SchemaManager.java:95) ~[hugegraph-client-1.8.0.jar:1.8.0.0]
	at com.baidu.hugegraph.loader.builder.SchemaCache.getPropertyKey(SchemaCache.java:49) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.getPropertyKey(ElementBuilder.java:180) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.validatePropertyValue(ElementBuilder.java:192) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.addProperties(ElementBuilder.java:173) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:64) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.VertexBuilder.build(VertexBuilder.java:35) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.builder.ElementBuilder.next(ElementBuilder.java:110) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:186) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:161) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:132) ~[hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:89) [hugegraph-loader-0.10.0.jar:?]
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:66) [hugegraph-loader-0.10.0.jar:?]
2020-05-03 08:22:26 [main] [INFO ] com.baidu.hugegraph.loader.HugeGraphLoader [] - Stop loading then shutdown HugeGraphLoader
2020-05-03 08:22:26 [main] [INFO ] com.baidu.hugegraph.loader.task.TaskManager [] - Waiting for the insert tasks of vertices finish
2020-05-03 08:22:26 [main] [INFO ] com.baidu.hugegraph.loader.task.TaskManager [] - The batch-mode tasks finished
2020-05-03 08:22:26 [main] [INFO ] com.baidu.hugegraph.loader.task.TaskManager [] - The single-mode tasks finished

个人感觉应该是schema.groovy的错误，但是研究了许久不知道错在哪里。望指教。

**Comment by imbajin** [comment]
可以先从报错看看, `property key with name '﻿aname' does not exist`. 

这说明属性没有在server成功查询到, 但是你也声明过了, 可以先查一下server的所有PropertyKey和VertexLabel, 看看
```javascript
GET http://localhost:8080/graphs/hugegraph/schema/propertykeys
```

然后如果不好确定属性缺失原因, 可以也清空schema后, 重新导入一次试试.

**Comment by SmilingMonkey** [comment]
> 可以先从报错看看, `property key with name '﻿aname' does not exist`.
> 
> 这说明属性没有在server成功查询到, 但是你也声明过了, 可以先查一下server的所有PropertyKey和VertexLabel, 看看有没有, 没有可以试着定位原因, 或者手动用[API创建](https://hugegraph.github.io/hugegraph-doc/clients/restful-api/propertykey.html), 再导入试试
> 
> ```js
> GET http://localhost:8080/graphs/hugegraph/schema/propertykeys
> ```
> 
> 然后如果不好确定属性缺失原因, 可以也清空schema后, 重新导入一次试试.
感谢您的答疑。
后期尝试过两种方式，第一种是重新安装了一下hugegraph，在利用原有文件进行导入，仍然报相同的错。
第二种方式尝试过用API创建schema.groovy里面的内容，在导入数据，发现利用API创建后，但是还是相同的报错。就抛弃了这种方式
后来选择将要导入的数据利用全部API来创建，最后将数据导入进数据库中了。可能是我写的文件里面或者其他方面的原因，暂时找不到。
