### ISSUE TITLE
使用mysql作为数据源导入时报错Exception in thread "main" com.baidu.hugegraph.rest.SerializeException: Failed to deserialize json

### ISSUE THREAD

**Issue by 17600592579** [hugegraph/hugegraph#986]
### Expected behavior 期望表现
可以正常导入

### Actual behavior 实际表现
导入失败

### Steps to reproduce the problem 复现步骤
1. {step 1}
使用hugegraph提供的example/mysql/下的案例
2. {step 2}
创建mysql数据库，我使用的是mariadb，导入sql建表语句
```
hugegraph version: v0.14.0
linux环境是：redhat7.4,
mariadb版本是：mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1
```

3. {step 3}
导入sql建表语句正常。
但是执行数据导入hugegraph时失败，部分日志如下
`hugegraph-loader -g hugegraph -f example/mysql/struct.json -s example/mysql/schema.groovy`
```
Exception in thread "main" com.baidu.hugegraph.rest.SerializeException: Failed to deserialize json
	at com.baidu.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:70)
	at com.baidu.hugegraph.loader.struct.GraphStruct.of(GraphStruct.java:67)
	at com.baidu.hugegraph.loader.HugeGraphLoader.<init>(HugeGraphLoader.java:71)
	at com.baidu.hugegraph.loader.HugeGraphLoader.main(HugeGraphLoader.java:65)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid json, expect 'vendor' in '{"driver":"com.mysql.cj.jdbc.Driver","url":"jdbc:mysql://xx.xx.xx.xx:3306","database":"exam
ple","table":"person","username":"root","password":"123456","batch_size":500}' (through reference chain: com.baidu.hugegraph.loader.struct.GraphStruct["vertices"]->java.util.ArrayList[0])	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:189)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:262)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3564)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2580)
	at com.baidu.hugegraph.loader.util.JsonUtil.fromJson(JsonUtil.java:68)
	... 3 more
Caused by: com.baidu.hugegraph.loader.serializer.DeserializeException: Invalid json, expect 'vendor' in '{"driver":"com.mysql.cj.jdbc.Driver","url":"jdbc:mysql://xx.xx.xx.xx:3306","database
":"example","table":"person","username":"root","password":"123456","batch_size":500}'	at com.baidu.hugegraph.loader.serializer.DeserializeException.expectField(DeserializeException.java:41)
	at com.baidu.hugegraph.loader.serializer.InputSourceDeser.getNode(InputSourceDeser.java:80)
	at com.baidu.hugegraph.loader.serializer.InputSourceDeser.readInputSource(InputSourceDeser.java:65)
	at com.baidu.hugegraph.loader.serializer.InputSourceDeser.deserialize(InputSourceDeser.java:48)
	at com.baidu.hugegraph.loader.serializer.InputSourceDeser.deserialize(InputSourceDeser.java:38)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:416)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	... 13 more

```

**Comment by 17600592579** [comment]
# 找到原因了，没注意看，错误提示已经给了
`Caused by: com.baidu.hugegraph.loader.serializer.DeserializeException: Invalid json, expect 'vendor' in '{"driver":"com.mysql.cj.jdbc.Driver","url":"jdbc:mysql://xx.xx.xx.xx:3306","database
":"example","table":"person","username":"root","password":"123456","batch_size":500}'	at com.baidu.hugegraph.loader.serializer.DeserializeException.expectField(DeserializeException.java:41)`
缺少vendor,加上即可
